### ISSUE TITLE
Question: Best way to truncate log file.

### ISSUE THREAD

**Issue by david-webill** [uber-go/zap#1022]
We use Datadog to ingest and store our logs, so I dont need to rotate or keep logs, just truncate the log file every so often.
Would there be any concerns about calling os.Truncate, should I disable logging while truncating?

Thanks!

**Comment by abhinav** [comment]
Yeah, there's probably a race condition with deleting the file
while Zap has an open os.File that it's writing to.

One way to accomplish what you want is with a custom zapcore.WriteSyncer.
You can build a WriteSyncer that periodically pauses writing,
and during that pause it closes, deletes, and re-opens the file.
During this, ensure that everything written so far has been uploaded
before you delete the file.

Closing.
Feel free to create a reopen or create a new issue if I missed something or if you have more questions.
Thanks!
