### ISSUE TITLE
Can I do not use defer logger.Sync()?

### ISSUE THREAD

**Issue by TedBaker1117** [uber-go/zap#1038]
if I do not use defer logger.Sync(), when system is interrupted, will zap lost some logs?

The reason I can't use defer logger.Sync() is that I'm writing a go-sdk for a middleware, so I don't where to use defer logger.Sync().

**Comment by wuhongbing** [comment]
Logger instance can be created outside the middleware, then injected into the middleware through dependency injection.

**Comment by abhinav** [comment]
Thanks @wuhongbing!
Closing because answered.
