### ISSUE TITLE
make capturing logs for testing easy

### ISSUE THREAD

**Issue by grosser** [uber-go/zap#1040]
I'm copy-pasting this our projects to be able to test logging, it would be great something similar would be available inside zap to make testing easy.

```go
func captureLogs(fn func(logger *zap.Logger)) (logs string) {
	config := zapcore.EncoderConfig{LevelKey: "level", EncodeLevel: zapcore.LowercaseLevelEncoder, MessageKey: "msg"}
	buffer := bytes.NewBufferString("")
	zap.NewExample()
	core := zapcore.NewCore(zapcore.NewJSONEncoder(config), zapcore.AddSync(buffer), zapcore.DebugLevel)
	logger := zap.New(core)
	fn(logger)
	return strings.TrimRight(buffer.String(), "\n") // trim because `` does not support \n well
}
```

then used like this (simplified: usually it would be running a method and then checking that logs include what I expect):
```go
Expect(captureLogs(func(logger *zap.Logger) {
	Expect(func() {
		logger.Panic("error", zap.Error(errors.New("must fail")))
	}).To(Panic())
})).To(Equal(`{"level":"panic","msg":"error","error":"must fail"}`))
```

**Comment by abhinav** [comment]
@grosser, apologies for the delayed response. Does [zaptest/observer](https://pkg.go.dev/go.uber.org/zap/zaptest/observer) not meet your needs with regards to testing your log output? It's encoding-agnostic, so it'll work whether you're using the JSON encoder or the console encoder.
(Internally, we use the console encoder during development and JSON in production, so cases where we want to test the log output need to work with both.)

**Comment by grosser** [comment]
that works, thanks!
