### ISSUE TITLE
AddCallerSkip() on a single logging output call?

### ISSUE THREAD

**Issue by adamwoolhether** [uber-go/zap#1050]
Is there a way to call this function on a specific call to my already instantiated logger?

In my case, I am handling both logs and errors via a chain of middleware, loggers first and errors second.

Naturally If I add the `AddCallSkip(1)` to my main log instantiation, all error logs now list the logger middleware as caller.
I could give it `2`, but then all normal looks are giving too deep of information.

Is it possible to call `AddCallerSkip(2)` only  to a specific call to my logger (in this case, inside my errors middleware)?

**Comment by prashantv** [comment]
In your middleware, take the existing logger, and then use [`WithOptions`](https://pkg.go.dev/go.uber.org/zap#Logger.WithOptions) to pass an additional `AddCallerSkip(1)`. Your original logger will be at caller skip = 1, and your middleware creates a new logger with caller skip 1+1=2, which should give you the intended behaviour.
