### ISSUE TITLE
 LoggerTo not declared by package zap

### ISSUE THREAD

**Issue by gshirazi** [uber-go/zap#1054]
LoggerTo not declared by package zap when upgrading to latest version . why there is no documentation on this?
What should be used instead of LoggerTo ?

**Comment by abhinav** [comment]
@gshirazi could you clarify what you need?
AFAIK Zap has never provided a type named "LoggerTo" in any release.

**Comment by gshirazi** [comment]
sorry my bad, I opened issue on a wrong repo
