### ISSUE TITLE
Set log level from string

### ISSUE THREAD

**Issue by theprobugmaker** [uber-go/zap#1056]
How can I change/set the log level from a string? Thank you

**Comment by sywhang** [comment]
Hey there

An API for parsing a string to a Zap log level was added in a recent commit: https://github.com/uber-go/zap/commit/e751939b68425b6aedd6bbf93704363c482880da. We don't have an official release that contains this yet, but the next release will have this API. In the meantime you could pin Zap to master and use it.

Will close this as it's already been completed.
