### ISSUE TITLE
ctx: store logger in context when missing or different that stored one

### ISSUE THREAD

**Issue by robsonpeixoto** [uber-go/zap#1057]
I really love the feature https://github.com/rs/zerolog/pull/81 because make easier implement features like this https://github.com/jackc/pgx/blob/cf0de913ee8facdfef0a7611d41cd67522b12c76/log/zerologadapter/adapter.go#L83-L92

**Comment by wuhongbing** [comment]
> I really love the feature [rs/zerolog#81](https://github.com/rs/zerolog/pull/81) because make easier implement features like this https://github.com/jackc/pgx/blob/cf0de913ee8facdfef0a7611d41cd67522b12c76/log/zerologadapter/adapter.go#L83-L92

I encapsulated a zap package to support context,you can try it. [zapctx](https://github.com/wuhongbing/zapctx)

**Comment by robsonpeixoto** [comment]
@lehoqi, would be amazing see this on the core project.
