### ISSUE TITLE
go mod tidy

### ISSUE THREAD

**Issue by shenghui0779** [uber-go/zap#1067]
```sh
go.uber.org/zap/zapcore tested by
        go.uber.org/zap/zapcore.test imports
        gopkg.in/yaml.v2 loaded from gopkg.in/yaml.v2@v2.2.8,
        but go 1.16 would select v2.4.0

To upgrade to the versions selected by go 1.16:
        go mod tidy -go=1.16 && go mod tidy -go=1.17
If reproducibility with go 1.16 is not needed:
        go mod tidy -compat=1.17
For other options, see:
        https://golang.org/doc/modules/pruning
```

**Comment by abhinav** [comment]
@shenghui0779 when/where are you seeing this error?

**Comment by shenghui0779** [comment]
I use `zap` in my project  and run `go mod tidy`

**Comment by abhinav** [comment]
I suspect if you run `go mod tidy -go=1.16 && go mod tidy -go=1.17`, this issue will resolve itself.
That said, following #1075, the next release will also not hit this issue for anyone.

Closing for now.
Please feel free to re-open or create a new issue if the problem surfaces after running the command above.

**Comment by fscomfs** [comment]
ambiguous import: found package cloud.google.com/go/compute/metadata in multiple modules
