### ISSUE TITLE
custom callerSkipOffset variable

### ISSUE THREAD

**Issue by surandor** [uber-go/zap#1070]
line: go.uber.org\zap@v1.17.0\logger.go:261
if I wrap the log method with some custom funcion, the log caller would be wrong.

**Comment by prashantv** [comment]
When you wrap the logger, you should also use the [`AddCallerSkip`](https://pkg.go.dev/go.uber.org/zap#AddCallerSkip) option to create a logger which increases the caller skip.

See an example here: https://github.com/uber-go/zap/issues/981#issuecomment-886790340

**Comment by surandor** [comment]
Thankyou.

**Comment by e-nikolov** [comment]
@prashantv Calling `WithOptions(AddCallerSkip(...))` will clone the existing logger, resulting in an extra allocation. Wouldn't this be a performance issue if used on every call to the custom function?

**Comment by juampynr** [comment]
Shall we mark this issue as solved?
