### ISSUE TITLE
Add WithOptions() for SugaredLogger

### ISSUE THREAD

**Issue by e-nikolov** [uber-go/zap#1072]
Currently there is WithOptions() only for unsugared loggers, so Desugar() and then Sugar() needs to be called in order to add options to a SugaredLogger.

**Comment by abhinav** [comment]
Hey @e-nikolov!
This is a reasonable request.
We'll be happy to review a PR for this.

**Comment by craigpastro** [comment]
Happy to give this a shot if that is okay?

**Comment by abhinav** [comment]
> Happy to give this a shot if that is okay?

Oops, I missed this @craigpastro. Sure! Feel free to create a PR for this.

**Comment by craigpastro** [comment]
Thanks! Created a PR.
