### ISSUE TITLE
Specify log level by parameter

### ISSUE THREAD

**Issue by adrianlungu** [uber-go/zap#1084]
Hello!

Would it be possible to have something like the following added to the logger ?

```
func (log *Logger) Log(level zapcore.Level, msg string, fields ...Field) {
	if ce := log.check(level, msg); ce != nil {
		ce.Write(fields...)
	}
}
```

this would allow anyone to also make dynamic calls i.e. `log.Log(ErrorLevel, "message", fields...)`. 

Thanks!

**Comment by mway** [comment]
Hey @adrianlungu, thanks for the suggestion! Could you give some more detail about the use case you're trying to solve for?

**Comment by adrianlungu** [comment]
Hey @mway , 

We use `zap` in a router middleware and currently compute a `zapcore.Level` based on the `statusCode`, i.e.

```
func DefaultLogLevel(status int) zapcore.Level {
	switch {
	case status >= 500:
		return zapcore.ErrorLevel
	case status >= 400:
		return zapcore.WarnLevel
	default:
		return zapcore.InfoLevel
	}
}
```

This allows us to use different levels based on the status code without having to switch between different logger functions or loggers.

**Comment by adrianlungu** [comment]
@prashantv yes, that is what we currently use, i.e.

```
func logWithLevel(logger *zap.Logger, level zapcore.Level, msg string, fields ...zapcore.Field) {
	if ce := logger.Check(level, msg); ce != nil {
		ce.Write(fields...)
	}
}
```

**Comment by mway** [comment]
The calls would likely be inlined, so that would just result in code deduplication which is always nice.
