### ISSUE TITLE
Question: How to get []zap.field inside the hook.

### ISSUE THREAD

**Issue by chimanjain** [uber-go/zap#1096]
I am new to zap and trying to figure out how to get the `Field` set in the logger inside the hook as the `Field` value is not present inside `zapcore.Entry`. Is there any other api to fetch the fields?

**Comment by prashantv** [comment]
There was a PR adding this feature, see #760

**Comment by abhinav** [comment]
Hey @chimanjain,  it looks like that PR got stalled.
Someone will need to take over those changes and create a new PR per [this comment](https://github.com/uber-go/zap/pull/760#issuecomment-759879391).
We don't currently have the bandwidth to take over that change, but we'll be happy to review another such PR.
(If you take over the change, please credit the original author as well.)
