### ISSUE TITLE
zap cannot log fields in a struct which are not exposed

### ISSUE THREAD

**Issue by unmarshall** [uber-go/zap#1097]
Hello,

We use `logr` along with `zapr` and in a k8s custom controller created via `controller-runtime`.
Initially i raised the issue on `logr` and it was concluded that the actual limitation is in `zap`, therefore raising this issue here.
For details of the issue please refer to https://github.com/go-logr/logr/issues/142

Best Regards,
Madhav

**Comment by pohly** [comment]
I am not sure whether zap "cannot" or "doesn't" log such fields.

https://stackoverflow.com/questions/42664837/how-to-access-unexported-struct-fields has some code that shows how values of unexported fields could be read for logging them.

**Comment by unmarshall** [comment]
>https://stackoverflow.com/questions/42664837/how-to-access-unexported-struct-fields has some code that shows how values of unexported fields could be read for logging them.

Using unsafe pointer directly to access un-exposed struct fields for logging for every consumer is not ideal IMHO. Which is why go natively provides this ability via `fmt` package. I would therefore argue that this feature should also be provided out of a logging lib.

**Comment by pohly** [comment]
> I would therefore argue that this feature should also be provided out of a logging lib.

And how?

**Comment by abhinav** [comment]
Hey @unmarshall, thanks for the ticket.

We don't intend for Zap to perform unsafe operations like accessing unexported fields. For Zap to do that would be a surprising behavior. It also does not match the behavior of APIs like [`json.Marshal`](https://pkg.go.dev/encoding/json#Marshal) which we rely on, and aim to emulate to some degree.

If you have a struct that needs to log unexported fields, we suggest implementing [zapcore.ObjectMarshaler](https://pkg.go.dev/go.uber.org/zap/zapcore#ObjectMarshaler) on it and logging those fields.

```go
func (nv *nameValue) MarshalLogObject(enc zapcore.ObjectEncoder) error {
  enc.AddString("name", nv.name)
  enc.AddInt("value", nv.value)
  return nil
}
```

Hope this helps.

**Comment by juampynr** [comment]
Shall we close this issue?

**Comment by pohly** [comment]
I think we should.

/close

**Comment by abhinav** [comment]
Fair. Closing since we do not intend to support this functionality.
