### ISSUE TITLE
Add support for Uint and Uint64

### ISSUE THREAD

**Issue by creiht** [uber-go/zap#110]
I would like to be able to log unsigned ints as part of the structured data.

**Comment by akshayjshah** [comment]
Makes sense. I'm happy to add this, but it'll have to wait until after the 1.0 release work is done. If you have time to work on a PR, we can land it earlier - ping this issue and I'll suggest an implementation.

**Comment by creiht** [comment]
I can take a stab at it.  I had looked at the code a bit, and it didn't look too bad.  If it will require anything besides following the pattern for what has been done for int and int64, let me know.

**Comment by akshayjshah** [comment]
Sounds great! Unsigned int handling should follow the pattern for `int` and `int64`, casting to/from `int64` to re-use `Field.ival`.

You may want to hold off until the end of the day, though, since we're in the midst of landing a bunch of large refactorings.
