### ISSUE TITLE
Use of placeholders

### ISSUE THREAD

**Issue by javasopp** [uber-go/zap#1119]
Hello, I would like to ask, does zap support the placeholder method? For example: logger.Info("string info :{}", numberId), like this, I don't seem to find the corresponding support, if not, is there a plan to support it, thank you

**Comment by mway** [comment]
[`zap.Logger`](https://pkg.go.dev/go.uber.org/zap#Logger) does not, but [`zap.SugaredLogger`](https://pkg.go.dev/go.uber.org/zap#SugaredLogger) does, for example:

```go
logger, err := zap.NewProduction()
if err != nil {
  // handle err
}

sugared := logger.Sugar()
sugared.Infof("hello %s", "world")
```

Any of the `f`-suffixed methods on `SugaredLogger` - e.g. `Infof`, `Warnf`, etc - work the same way as [`fmt.Sprintf`](https://pkg.go.dev/fmt#Sprintf).

Hope that helps!

**Comment by javasopp** [comment]
谢谢，这个已经能够解决我的问题了，不过还是希望zap.Logger能够支持类似于这种的语法，例如：
`
logger, err := zap.NewProduction()
if err != nil {
  // handle err
}

logger.Info("hello {}", "world") // logged message: "hello world"
`
谢谢

**Comment by javasopp** [comment]
Thanks, this has solved my problem, but I still hope that zap.Logger can support a syntax similar to this, for example:
```
logger, err := zap.NewProduction()
if err != nil {
   // handle err
}

logger.Info("hello {}", "world") // logged message: "hello world"
```
Thank you
