### ISSUE TITLE
How is this used locally?

### ISSUE THREAD

**Issue by magicalbanana** [uber-go/zap#112]
So I know there's a request to support fancier outputs when doing development, but currently, how are you handling the logs if you are prettifying it (assuming someone is doing this)? Is there a process manager that redirects the STDOUT to an ELK node (vagrant or docker) that is being setup? 

This is more for my personal preference really more than anything. So feel free to close this issue if currently reading to STDOUT is what is done.

**Comment by akshayjshah** [comment]
Hey @magicalbanana - you'd use zap the same way you use the standard library's logger. Zap can log to standard out, standard error, files, or any other `WriteSyncer` implementation. Tailing those logs and sending them to ELK, Papertrail, Splunk, or another aggregation system is up to you.
