### ISSUE TITLE
SugaredLogger: Turn error into zap.Error

### ISSUE THREAD

**Issue by abhinav** [uber-go/zap#1184]
**Is your feature request related to a problem? Please describe.**

With Zap's sugared logger, if you provide a plain error object to Infow/Errorw/etc.,
it does not desugar the error into a zap.Field.

```go
log.Warnw("something happened", err) // bad

log.Warnw("something happened", "err", err) // good
// desugars to
log.Desugar().Warn("something happened", zap.NamedError("err", err))
```

This is inconvenient for the majority case where there will be only one error.

**Describe the solution you'd like**

We should turn the first case into,

```go
log.Desugar().Warn("something happened", zap.Error(err))
```

We could even be smart about it in desugarFields
and make sure there's only one instance of "err".
Others have to have a field name.

**Describe alternatives you've considered**

Add "err" next to every err argument.

**Is this a breaking change?**
No

**Comment by craigpastro** [comment]
I would like to try giving this a shot if that's okay?

**Comment by abhinav** [comment]
Sure, @craigpastro!
