### ISSUE TITLE
how to write stacktrace into msg?

### ISSUE THREAD

**Issue by lxxwilliam** [uber-go/zap#1197]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Is this a breaking change?**
We do not accept breaking changes to the existing API. Please consider if your proposed solution is backwards compatible. If not, we can help you make it backwards compatible, but this must be considered when we consider new features.

**Additional context**

**Comment by alxn** [comment]
Did you mean https://pkg.go.dev/go.uber.org/zap#Stack ?

**Comment by lxxwilliam** [comment]
> 
`{
    "level": "error",
    "ts": 1641371801.0257752,
    "caller": "main/main.go:31",
    "msg": "function error",
    "stacktrace": "main.main\n\t/Users/romber/work/source_code/go/src/github.com/romberli/golang-test/test06/main/main.go:31\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225"
}`
you know, just like this. i wanna write stacktrace into msg

**Comment by alxn** [comment]
That looks correct:

https://go.dev/play/p/XS8-iuShk8R

`{"level":"info","ts":1257894000,"caller":"sandbox3992485392/prog.go:10","msg":"We are in two","the-stack":"main.two\n\t/tmp/sandbox3992485392/prog.go:10\nmain.one\n\t/tmp/sandbox3992485392/prog.go:13\nmain.main\n\t/tmp/sandbox3992485392/prog.go:19\nruntime.main\n\t/usr/local/go-faketime/src/runtime/proc.go:250"}`

```
"main.two
    /tmp/sandbox3992485392/prog.go:10
main.one
    /tmp/sandbox3992485392/prog.go:13
main.main
    /tmp/sandbox3992485392/prog.go:19
runtime.main
    /usr/local/go-faketime/src/runtime/proc.go:250"
```

**Comment by lxxwilliam** [comment]
> 

sorry, I mean, do I  have any way to get the info of stacktrace like "main.two
    /tmp/sandbox3992485392/prog.go:10..." and write them into the msg. The result which I want to see just like : "msg":"We are in two ,main.two\n\t/tmp/sandbox3992485392/prog.go:10 ..."

**Comment by alxn** [comment]
https://go.dev/play/p/QX7yvYeb4Wv

I'd take a look at the implementation of `debug.PrintStack()`, then it's just a string format.

**Comment by lxxwilliam** [comment]
> https://go.dev/play/p/QX7yvYeb4Wv
> 
> I'd take a look at the implementation of `debug.PrintStack()`, then it's just a string format.

thanks. I've tried this before.However, I thought there was an implementation in this package.
