### ISSUE TITLE
Return logger name

### ISSUE THREAD

**Issue by djarbz** [uber-go/zap#1200]
**Is your feature request related to a problem? Please describe.**
I am writing an application that overall should have a user specified log level, ie INFO.
But they can overwrite the log level for certain "actions" that would be handled on a case by case basis.
Since we are unable to change the log level of a cloned logger, I am instantiating a new logger set to the DEBUG level.
Currently, this new logger does not have the inherited name for the existing logger.
I would like a function such as `zapLog.GetName()` that would return a string of the current log name that I can then pass on to the new logger.

**Is this a breaking change?**
I do not believe this would be a breaking change as it would add a function to the current interface.

**Comment by prashantv** [comment]
It seems reasonable to add `Name() string` to `*Logger` that exposes the name.

**Comment by rexywork** [comment]
Hi, I try to create PR for this issues here:
https://github.com/uber-go/zap/pull/1273

Please check the comment so I can double check what I need to do

**Comment by rnemeth90** [comment]
Is this being actively worked on? If not, please assign to me and I'll submit a PR.

**Comment by prashantv** [comment]
This was released in https://github.com/uber-go/zap/releases/tag/v1.25.0
