### ISSUE TITLE
How to disable sampling

### ISSUE THREAD

**Issue by pdorrestijn** [uber-go/zap#1211]
On stackoverflow i see some references towards zap code on how to disable sampling.
However, this all refers to using a zap.Config type while I'm using zap with lumberjack and I can't seem to find a way to disable sampling.
I tried to investigate how to disable sampling, but I can't find it.
Sampling is really undesirable for me, please help me out.
This is how I managed to build the zap logger using a lumberjack writer which is added to zap using zapcore.AddSync:
`
core = zapcore.NewCore(getEncoder(), getLogWriter(_globalLogConfiguration), _level)

_logger = zap.New(core)
`

**Comment by abhinav** [comment]
If you're constructing a logger like that code sample -- with `zapcore.NewCore` followed by `zap.New`,
sampling is already disabled.

To *enable* sampling on top of that, you'd have to use [zapcore.NewSamplerWithOptions](https://pkg.go.dev/go.uber.org/zap/zapcore#NewSamplerWithOptions).

```go
core = zapcore.NewSamplerWithOptions(...)
```

But as-is, without any additional wrapping, sampling is already disabled.

The other way you could've been constructing the logger is with [`zap.Config`](https://pkg.go.dev/go.uber.org/zap#Config).[`Build()`](https://pkg.go.dev/go.uber.org/zap#Config.Build),
in which case, to disable sampling you'd have to set [`Config.Sampling`](https://pkg.go.dev/go.uber.org/zap#Config.Sampling) to nil.

**Comment by pdorrestijn** [comment]
Hi Abhinav,
Thnx for the reply.
Maybe then something else is preventing from log events being written (stdout or file).
I assumed that sampling would be the cause of the missing log events.
But in fact the problems arise when I enable the debug level.
When I enable this level, I barely get any logging (just a few debug, info and warn events while I should get a lot more).
If I start my app with level info I do see the logging.
I've been banging my head around this behavior for quite some time and can't figure out why the debug level is not working properly with zap.

I have found a different way to setup zap with lumberjack:
https://github.com/uber-go/zap/blob/master/FAQ.md#why-sample-application-logs

My environment is: Go 1.17.10
	go.uber.org/zap v1.23.0
	gopkg.in/natefinch/lumberjack.v2 v2.0.0

I'm going to try that and hope for improvement. if not my hopes are for tips here or else I unfortunatly need to reconcider the use of zap.

**Comment by pdorrestijn** [comment]
Nevermind :)
I found the issue, zap rocks!
