### ISSUE TITLE
Noticeable slowdown when using Sugar on a no-op logger

### ISSUE THREAD

**Issue by gregorygaines** [uber-go/zap#1217]
**Describe the bug**
When using the logger normally, my application runs at full speed.

```
plainLogger, _ := zap.NewDevelopment()
app := NewApp(plainLogger.Sugar())
```

**To Reproduce**
When I change `plainLogger` into a no-op logger and pass the sugar logger, my entire application slows down.

```
plainLogger := zap.NewNop()
app := NewApp(plainLogger.Sugar())
```

**Expected behavior**
I expect the same if not a higher performance when I switch to a no-op logger.

**Comment by gregorygaines** [comment]
The work I'm doing is **extremely sensitive** to performance slowdowns, and 12864 ns/op	is a huge penalty vs 4.9 ns/op which operates smoothly.

If this can't be lower then nothing can be done and the issue can be closed.

**Comment by prashantv** [comment]
The huge ~13000 ns/op is for the development logger, while the low ~5ns/op is for the no-op logger.

In the original issue you stated:
> When I change plainLogger into a no-op logger and pass the sugar logger, my entire application slows down.

However, the benchmark shows that the no-op logger is significantly faster which doesn't match the original report, which is what I meant by not being able to reproduce the issue.

Are you seeing slower performance from the no-op logger?

**Comment by gregorygaines** [comment]
Apologies, I read that wrong. I've switched to another logger now so I can't verify my accounts. This can be closed, thanks!
