### ISSUE TITLE
Go build err with version 1.17

### ISSUE THREAD

**Issue by Allen9012** [uber-go/zap#1222]
It seems that Go build err with version 1.17
In previous zap version such as 1.20.0, it works successfully
But in version 1.24.0 with go version under 1.16 
error happens when exec go build
![image](https://user-images.githubusercontent.com/86969944/213848530-bf7d60d9-0669-4313-8424-2f265a7d8532.png)

//go:build comment without // +build comment

**Comment by sywhang** [comment]
Hey there, 

As it says on our README, we only support the two most recent minor versions of Go, which is Go 1.18 and Go 1.19 right now. 

> Note that zap only supports the two most recent minor versions of Go.

Hope that helps!
