### ISSUE TITLE
Add `slog` to performance benchmarks

### ISSUE THREAD

**Issue by Dentrax** [uber-go/zap#1229]
> [slog](https://pkg.go.dev/golang.org/x/exp/slog) is a new standard library package which could provide structured logging with levels. [^1]

* Add slog package into [benchmarks](https://github.com/uber-go/zap/tree/master/benchmarks)
* * Add slog package into [Performance](https://github.com/uber-go/zap#performance) section at README. (I think it's auto-generated)

I can submit a PR for this, let's discuss before.

[^1]: https://www.youtube.com/watch?v=gd_Vyb5vEw0

**Comment by sywhang** [comment]
Thanks for the suggestion. We'll have someone take a look at this shortly.

**Comment by JacobOaks** [comment]
Internal Ref: GO-1885

**Comment by ChannyClaus** [comment]
i took a stab at it: https://github.com/uber-go/zap/pull/1245 let me know if it looks good

wasn't sure how to generate the snippets in the `README.md`, though.

**Comment by Dentrax** [comment]
https://github.com/golang/go/issues/56345#issuecomment-1470506816

**Comment by sywhang** [comment]
Closing this as it was completed with #1245

**Comment by robsonpeixoto** [comment]
Are there plans to add zapslog?
