### ISSUE TITLE
When I am using zap logger, How to automatically add space between number and string  field?

### ISSUE THREAD

**Issue by yxw2014** [uber-go/zap#1231]
**logger.Info("TestStart", 1, 2, "vfgf", 23, errors.New("eeeeeee"))**

**Output:** 
2023-02-14T10:31:09+08:00       INFO    TestStart1 2vfgf23 eeeeeee

**Expect:**
2023-02-14T10:31:09+08:00       INFO    TestStart 1 2 vfgf 23 eeeeeee

Zap has many problems with even the most basic functions, and the user experience is very bad.
😭😭

**Comment by sywhang** [comment]
Please use the provided template to file issues like this so that discussions can be [constructive](https://github.com/uber-go/zap/blob/master/CODE_OF_CONDUCT.md). 

cc @r-hang

**Comment by abhinav** [comment]
@yxw2014 You're using the SugaredLogger, but the "Print(..)" equivalent function. That only inserts spaces between two arguments only if they're both not strings.
If you want spaces between all arguments, use the "Println(..)" equivalent function: Infoln. That will insert blanks between all arguments.

For context, the SugaredLogger Info, Warn, Error, etc. methods are all based on fmt.Print which says:

> Spaces are added between operands when neither is a string.

Whereas the equivalent Infoln, Warnln, etc. methods are based on fmt.Println:

> Spaces are always added between operands

Lastly, there are `*w` methods: Infow, Warnw, etc. that all accept key-value pairs for structured logging, which is Zap's primary use case.

**Comment by abhinav** [comment]
Closing because the question was answered.

We've also added additional comments to the individual log methods so that you don't have to be aware of the difference between print and println.
