### ISSUE TITLE
When I am using zap logger, How to automatically add space between number and string  field?

### ISSUE THREAD

**Issue by yxw2014** [uber-go/zap#1232]
**logger.Info("TestStart", 1, 2, "vfgf", 23, errors.New("eeeeeee"))**

**Output:** 
2023-02-14T10:31:09+08:00       INFO    TestStart1 2vfgf23 eeeeeee

**Expect:**
2023-02-14T10:31:09+08:00       INFO    TestStart 1 2 vfgf 23 eeeeeee

Zap has many problems with even the most basic functions, and the user experience is very bad.
😭😭😄

**Comment by sywhang** [comment]
closing as dup of #1231.
