### ISSUE TITLE
panic: runtime error: SIGSEGV when permission denied on log file

### ISSUE THREAD

**Issue by oernii** [uber-go/zap#1244]
**Describe the bug**
App crashes when zap tries to create a logfile in a directory where there user has no permission to write

**To Reproduce**
- have non-root user
- start app in / for example or any non-writable dir
- crash:
```
 panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6b95ca]

goroutine 1 [running]:
go.uber.org/zap.(*Logger).check(0x0, 0x0, {0x74735b, 0x17})
        /root/go/pkg/mod/go.uber.org/zap@v1.23.0/logger.go:291 +0x6a
go.uber.org/zap.(*Logger).Info(0xc0000186b8?, {0x74735b?, 0x0?}, {0x0, 0x0, 0x0})
        /root/go/pkg/mod/go.uber.org/zap@v1.23.0/logger.go:212 +0x3b
main.main()
        /builds/build/app/main.go:30 +0x1a5

```

**Expected behavior**
Zap should crash with an "permission denied" error, not SEGV

**Additional context**
Similar to https://github.com/uber-go/zap/issues/390

**Comment by JacobOaks** [comment]
Hey, thanks for reporting this.

How are you building your logger? This is indicating the logger itself is nil. I was able to reproduce this by creating a logger from a config with a sink to a file in / but all I had to do to avoid the sigsegv was check for an error from `config.Build()`:
```go
func main() {
    conf := zap.NewProductionConfig()
    conf.OutputPaths = append(conf.OutputPaths, "/output.log")
    logger, err := conf.Build()
    if err != nil {
        fmt.Printf("err creating logger: %v\n", err)
        return
    }
    defer logger.Sync()
    logger.Info("my log msg")
    // ...
}
```
Output:
`err: open sink "/output.log": open /output.log: permission denied`

**Comment by oernii** [comment]
That worked nicely, thanks for the hint.
