### ISSUE TITLE
zap.L().Fatal() and zap.L().Sync() do not flush logs

### ISSUE THREAD

**Issue by rmardini-figma** [uber-go/zap#1247]
**Describe the bug**
- If a logger is configured to print to the console, `logger.Fatal()` does not flush the log buffer. According to [this FAQ](https://github.com/uber-go/zap/blob/master/FAQ.md#why-include-dedicated-panic-and-fatal-log-levels) `Fatal` should flush the log buffer.
- Manually flushing does not succeed as a workaround: `logger.Sync()` doesn't flush logs and returns the error mentioned in [this thread](https://github.com/uber-go/zap/issues/880) (see 'Additional Context')
```
sync /dev/stderr: inappropriate ioctl for devicetest
```

**To Reproduce**
- Configure logger to print to console (in my case I've also configured the logger to be the global logger though I don't think that should matter)
```
cfg := zap.Config{
	Encoding:         "console",
	Level:            "info",
	OutputPaths:      []string{"stderr"},
	ErrorOutputPaths: []string{"stderr"},
	EncoderConfig: zapcore.EncoderConfig{
	    MessageKey: "message",
        }
}

logger := zap.Must(cfg.Build())
defer logger.Sync()
zap.ReplaceGlobals(logger)
```
- Add a log statement followed immediately by a fatal
```
zap.L().Info("info-test")
zap.L().Fatal("fatal-test")
```

**Expected behavior**
```
info-test
fatal-test
```

**Actual behavior**
```
fatal-test
```

**Additional Context**
Error logs are successfully printed before fatal (presumably because error writes aren't buffered)
```
zap.L().Error("error-test")
zap.L().Fatal("fatal-test")

gives

error-test
fatal-test
```

Also, calling `zap.L().Sync()` before `zap.L().Fatal`  (i.e. ignoring the error) does not succeed in flushing the log buffer 
```
zap.L().Info("info-test")
zap.L().Sync()
zap.L().Fatal("fatal-test")

gives

fatal-test
```

**Comment by prashantv** [comment]
I'm not able to reproduce this on Mac OS (13.2.1) or on a Linux VM,

```go
	zap.L().Info("info-test")
	zap.L().Fatal("fatal-test")
```

output:
```
$ go run ./main.go
info-test
fatal-test
exit status 1
```

I tried on both go 1.19 and 1.20.

**Comment by rmardini-figma** [comment]
Thanks for checking, turns out this is just user error. We were unexpectedly setting the log level to 'warn' instead of 'info'.
