### ISSUE TITLE
Panic and Fatal do not currently panic or exit when using Check and the level is disabled

### ISSUE THREAD

**Issue by prashantv** [uber-go/zap#125]
If the logger level is set to ignore all panic/fatal logs (e..g, by using `FatalLevel+1`), then there is an inconsistency in how we handle the logs.

If we do `logger.Panic(...)`, then the log is skipped, but the process crashes.
If we use the `Check` method and pass in `PanicLevel` or `FatalLevel`, then we return a not-OK checked message and we don't actually panic or fatal.

Normally, check will cause a panic on the `Write` if the level is enabled.

I've written some tests to reproduce this behaviour:
https://github.com/uber-go/zap/compare/pv_panic_always?expand=1

I think the best option is for `Check` to always return `true` for `PanicLevel` and `FatalLevel`.

**Comment by akshayjshah** [comment]
Ouch - good catch.
