### ISSUE TITLE
Configurable `fields` name

### ISSUE THREAD

**Issue by magicalbanana** [uber-go/zap#131]
I am not sure if this is already supported but I propose that the `fields` section of the log be configurable to a name desired by the user of this package.

**Comment by prashantv** [comment]
There was a large refactoring recently which removed the `fields` section, it's now flattened, and if you want to add a fields, you can by using using a nested field.

See the example:
https://godoc.org/github.com/uber-go/zap#ex-package

Output looks like:
```
{"level":"error","msg":"Oh no!","user":"jane@test.com","visits":42}
```

If we add support for nested loggers (https://github.com/uber-go/zap/issues/132), then the user can choose to have fields nested under any name they choose.
