### ISSUE TITLE
Support nested loggers that can only add context to a nested field

### ISSUE THREAD

**Issue by prashantv** [uber-go/zap#132]
Copying from https://github.com/uber-go/zap/issues/81#issuecomment-235629205

Currently a logger always has a reference to the top level fields. This is more likely to cause field clashes as the logger is passed between multiple libraries. 

We could add support for a logger that only had a reference to a nested field:

``` go
logger := New(...)
_ = newConnection(logger.Nested("conn"))
_ = newRequest(logger.Nested("request"))
```

The nested logger would not be able to add anything to the top level fields, so you could pass in the logger to other components (internal or external) without having to worry about clashes.

**Comment by akshayjshah** [comment]
Landed on dev.
