### ISSUE TITLE
Please release new tag ext/v0.2.0

### ISSUE THREAD

**Issue by micronull** [uber-go/zap#1343]
**Describe the bug**

It is currently not possible to use the adapter to handle log/slog.

```
cannot use zapHandler (variable of type *zapslog.Handler) as "log/slog".Handler value in argument to slog.New: *zapslog.Handler does not implement "log/slog".Handler (wrong type for method Enabled)
		have Enabled(context.Context, "golang.org/x/exp/slog".Level) bool
		want Enabled(context.Context, "log/slog".Level) bool
```

**To Reproduce**

1. `go get go.uber.org/zap/ext`
2. Write and trying to compile to go1.21:
```go
log := zap.NewExample()
log = log.With(zap.String("foo", "bar"))

zapHandler := zapslog.NewHandler(log.Core())

_ = slog.New(zapHandler) // <-- error
```

**Comment by sywhang** [comment]
v0.2.0 of zap/exp was tagged: https://github.com/uber-go/zap/releases/tag/exp%2Fv0.2.0

Note the constructor `zapslog.NewHandler` now takes in a HandlerOption so you need to modify that accordingly in your code.
