### ISSUE TITLE
JSON Array support

### ISSUE THREAD

**Issue by kazegusuri** [uber-go/zap#136]
zap supports nested JSON Objects with `zap.Nest` or `zap.Marshaler`, but does not support JSON Array yet.  Current workaround is to use `zap.Object` and implement `MarshalJSON` to output JSON Array. How about built-in support for JSON Array like `zap.Array`?

**Comment by akshayjshah** [comment]
That's definitely on our radar. For now, you can use `zap.Object` - if you don't mind falling back to the standard library's `json.Marshal`, you don't even have to implement `MarshalJSON`.

The best way I can think of to support JSON arrays (while keeping performance good) is to add specific helpers for each slice type. We'd end up with `zap.Ints`, `zap.Floats`, `zap.Durations`, etc.

Are you interested in working on this feature?

**Comment by jcorbin** [comment]
@akshayjshah , what do you think of the following approach:
```
diff --git a/keyvalue.go b/keyvalue.go
index cda24f5..862ebb3 100644
--- a/keyvalue.go
+++ b/keyvalue.go
@@ -38,4 +38,26 @@ type KeyValue interface {
 	// allocation-heavy. Consider implementing the LogMarshaler interface instead.
 	AddObject(key string, value interface{}) error
 	AddString(key, value string)
+	AddArray(key, valueAdder func(Values) error)
+}
+
+// Values is an encoding agnostic interface to add array data to a keyed value
+// within a logging context. Like slices, Values aren't safe for concurrent use
+// (though typical use shouldn't require locks).
+//
+// XXX example
+type Values interface {
+	AddBool(value bool)
+	AddFloat64(value float64)
+	AddInt(value int)
+	AddInt64(value int64)
+	AddUint(value uint)
+	AddUint64(value uint64)
+	AddUintptr(value uintptr)
+	AddMarshaler(marshaler LogMarshaler) error
+	// AddObject uses reflection to serialize arbitrary objects, so it's slow and
+	// allocation-heavy. Consider implementing the LogMarshaler interface instead.
+	AddObject(value interface{}) error
+	AddString(value string)
+	AddArray(valueAdder func(Values) error) // XXX to taste depending on how recursive you're feeling this morning ;-)
 }
```

**Comment by akshayjshah** [comment]
This is in-progress on the dev branch: #211

**Comment by akshayjshah** [comment]
Further support in #258.

**Comment by akshayjshah** [comment]
Landed on dev.
