### ISSUE TITLE
Extend `WithLazy` method to `SugaredLogger`

### ISSUE THREAD

**Issue by defval** [uber-go/zap#1377]
Hi, `zap` maintainers!

**Is your feature request related to a problem? Please describe.**

The recently added `WithLazy` method is amazing (PR: https://github.com/uber-go/zap/pull/1319). This capability is not yet available for `SugaredLogger`

**Describe the solution you'd like**
The straightforward idea is to expose a similar signature from `SugaredLogger` using `WithLazy` method :

```go
func (s *SugaredLogger) WithLazy(args ...interface{}) *SugaredLogger {
	return &SugaredLogger{base: s.base.WithLazy(s.sweetenFields(args)...)}
}
```

There is still overhead from the `sweetenFields` call, but it's nonetheless much less than using `With()`.

**Is this a breaking change?**
Nope

If you approve, I'm ready to work on that because it's somewhat blocking us

**Comment by r-hang** [comment]
Hey @defval, this feature makes sense to me. Feel free to send us something for review!

**Comment by defval** [comment]
@r-hang Hey, mate! The PR is ready. Could you take a look at it soon?
