### ISSUE TITLE
Clean up documentation

### ISSUE THREAD

**Issue by akshayjshah** [uber-go/zap#139]
Before releasing v1.0.0, we should clean up the documentation (both the README and the GoDoc). The current README is a bit text-heavy and doesn't show off enough code.

**Comment by magicalbanana** [comment]
What about doing the documentation using `mkdocs` or `readthedocs`?

**Comment by sectioneight** [comment]
In addition, should we pull in some of our fabulous tech writers? e.g. @beklapko

**Comment by akshayjshah** [comment]
Yeah, let's definitely recruit a ringer :)

@magicalbanana, I'd prefer to stick to a README and GoDoc until they're proven insufficient. The README isn't optional, since the project's on GitHub, and Go packages should always have complete GoDoc. If those aren't enough, we can explore a more general-purpose option like Github Pages, ReadTheDocs, or mkdocs.

**Comment by moitias** [comment]
Even a simple Contributing.MD would be nice, as the first indication of testing/linting practices I came up with a recent PR were displayed when making the PR (checklist that was automatically added to the PR). 

That checklist also seems to link to a different CLA (on Google Docs) than the one CLAssistant requires in the PR, which is confusing (even if they do work together?)

**Comment by akshayjshah** [comment]
Both good points. I'll update the PR template to mention the bot (instead of providing a direct link), and I'll make sure to add a contributing guide with the rest of the docs.

**Comment by akshayjshah** [comment]
Done! The PR template predated the CLA bot - thanks for reminding me that they pointed to different docs.

**Comment by akshayjshah** [comment]
The lion's share of this is done (finally!).
