### ISSUE TITLE
Move stdlib-compatible wrapper into core library?

### ISSUE THREAD

**Issue by akshayjshah** [uber-go/zap#141]
Discuss: should we move the stdlib compatibility wrapper into the core `zap` package? It doesn't pull in any extra dependencies.

Currently, the standard library compatibility wrapper lives in the [zwrap package](https://godoc.org/github.com/uber-go/zap/zwrap#Standardize). It's used via `zwrap.Standardize`.

Moving it into the core `zap` package would look like `zap.Standardize`.

**Comment by sectioneight** [comment]
Maybe suggest a vote via thumbsup/thumbsdown reactions? I've seen it work decently on other projects

**Comment by mofirouz** [comment]
I'm very interested in this as a few of the libraries that I have in my project allow logger overrides with stdlib logger package - but I can't pass Zap to them because of this incompatibly.

**Comment by prashantv** [comment]
@mofirouz Can you explain your situation more? All this issue would change is how you standardize the `zap.Logger`. Currently you have to import an [extra package](https://godoc.org/github.com/uber-go/zap/zwrap#Standardize) to use this. This issue is proposing moving it into the zap package, so it would be come `zap.Standardize` instead of `zwrap.Standardize`.

My preference is to keep the API minimal where possible, I don't see the subpackage as a big issue, it may be harder to discover, but examples can help with that.

I'm going to edit the original description to make it clear what the options are.

**Comment by prashantv** [comment]
Just realized, we also have https://github.com/uber-go/zap/issues/138, so if we move this wrapper to the core `zap` package, we'll most likely have 3 logger interfaces:
 - the core zap logger which uses `zap.Field`
 - less verbose logger
 - the standard library logger

Names like `StandardLogger` (which is currently what `zap.Standardize` returns) is going to get confusing when combined with `CoreLogger` and `Logger`.

Unless we come up with clear yet concise names for all the different loggers, my vote is no.

**Comment by mofirouz** [comment]
@prashantv Thanks for the quick comment on this ticket. I actually hadn't even seen the zwrap package - I'll give it a try although I get the feeling that this might not be the full solution to my problem:

I'm using [Hashicorp Memberlist](https://github.com/hashicorp/memberlist) library to connect my server nodes together. Membership allows you to override the logger with a custom logger with its [configuration struct](https://github.com/hashicorp/memberlist/blob/master/config.go#L181). It is sadly hardcoded to `*log.Logger` - can this be used with the `StandardLogger` interface?

On this specific issue, I think my vote is also `no` as it makes things look more complicated that it is, but I do agree that extra documentation is needed.

Thanks for the great work :)

**Comment by prashantv** [comment]
@mofirouz Ah, since they use a concrete type, there's no way to pass the `StandardLogger` interface to that struct.

However, they should probably create a logger interface (similar to `StandardLogger` that the `*log.Logger` would satisfy). That way users can pass custom loggers.

**Comment by akshayjshah** [comment]
I'm fine with leaving this in a separate package, but the current `zwrap` name is a bit obscure and difficult to discover. I'd prefer something more explicit and narrowly-scoped (e.g., `stdlib`, so you'd use `stdlib.Logger`).

**Comment by akshayjshah** [comment]
This is subsumed by #222.
