### ISSUE TITLE
Deadlock when calling `BufferedWriteSyncer.Stop`

### ISSUE THREAD

**Issue by Gordy96** [uber-go/zap#1428]
### Describe the bug
Upon calling `Stop` there's a small chance of deadlock. Happens sometimes on go `v1.21.3` zap `v1.22.0`. 
### To Reproduce
Can't really figure out how to reproduce it without touching said code yet.

#### This is what I suspect is happening:
When `Stop` is called, it spawns a goroutine that locks mutex,
https://github.com/uber-go/zap/blob/b15585bc7a2b383592004f75df35fa2088db5481/zapcore/buffered_write_syncer.go#L195-L196
stops timer and tells `flushLoop` to break
https://github.com/uber-go/zap/blob/b15585bc7a2b383592004f75df35fa2088db5481/zapcore/buffered_write_syncer.go#L208-L210
However if timer fired before stop occurred here
https://github.com/uber-go/zap/blob/b15585bc7a2b383592004f75df35fa2088db5481/zapcore/buffered_write_syncer.go#L176-L184
It calls `Sync` that tries to acuire locked mutex
https://github.com/uber-go/zap/blob/b15585bc7a2b383592004f75df35fa2088db5481/zapcore/buffered_write_syncer.go#L159-L160
So `Stop` goroutine holds mutex and waits for `flushLoop` to close channel on defer while `flushLoop` waits on `Sync` to finish, but it can't since mutex is locked in `Stop` goroutine

**Comment by prashantv** [comment]
Thank you for the detailed bug report, you're exactly right with your analysis, `Stop` holds the lock, which `flushLoop` will also try to acquire if the timer ticks around the same time. I was able to reproduce it consistently with the added test in #1430, and verified that it fixes the issue.
