### ISSUE TITLE
Use bit-shifting instead of modulus in sampling

### ISSUE THREAD

**Issue by akshayjshah** [uber-go/zap#143]
We can make the sampling wrapper ever so slightly faster if we use bit-shifting operations instead of the modulus operator. This may require rounding the sampling rates to the nearest (or next-lowest) power of two.

**Comment by gliptak** [comment]
Do you refer to https://github.com/uber-go/zap/blob/master/zwrap/sample.go#L172 here? Thanks

**Comment by akshayjshah** [comment]
Yep, that's the line!

**Comment by akshayjshah** [comment]
After @gliptak explored this in #178, the hoped-for performance gains didn't materialize. Closing this, since the gains aren't worth the API limitations.
