### ISSUE TITLE
Support tee'ing to multiple sinks

### ISSUE THREAD

**Issue by akshayjshah** [uber-go/zap#144]
Both for the output and error output, we should support a `Tee` constructor that works like the `tee` Unix utility, echoing output to multiple sinks. This is particularly useful in development, where we may want to send output to both the console and a file.

**Comment by sectioneight** [comment]
What's the priority / severity of this? Do we want to add a `help-wanted` tag?

I've been participating in an OSS project in my free time and have found the maintainer's priority/severity/type/"help wanted" tags invaluable in jumping in
