### ISSUE TITLE
go-licenses is not able to find license

### ISSUE THREAD

**Issue by pavelzw** [uber-go/zap#1441]
When running `go-licenses` on a project that depends on `go.uber.org/zap/exp/zapslog` (like caddy), I get the following error:

```
E0530 10:04:20.840357   13917 library.go:122] Failed to find license for go.uber.org/zap/exp/zapslog: cannot find a known open source license for ".../gopath/pkg/mod/go.uber.org/zap/exp@v0.2.0/zapslog" whose name matches regexp ^(?i)((UN)?LICEN(S|C)E|COPYING|README|NOTICE).*$ and locates up until ".../gopath/pkg/mod/go.uber.org/zap/exp@v0.2.0"
```

It seems like you don't bundle the LICENSE in your uploaded go package.

Also see https://pkg.go.dev/go.uber.org/zap/exp@v0.2.0

![image](https://github.com/uber-go/zap/assets/29506042/27dbdad5-d319-452e-856a-525c3fa7df1b)

It would be nice to bundle the license file of this project in the go packages.

**Comment by mway** [comment]
Hey @pavelzw, thanks for reporting - we do have a [LICENSE](https://github.com/uber-go/zap/blob/master/LICENSE) file, but not in the [exp/](https://github.com/uber-go/zap/tree/master/exp) module. #1442 should address this.

**Comment by sbruens** [comment]
@mway Are there any plans to release this in a new version for the exp/ module? I just ran into this same issue (incidentally also with Caddy).
