### ISSUE TITLE
There are many '\n' in the json-style log

### ISSUE THREAD

**Issue by yangyang233333** [uber-go/zap#1455]
**Describe the bug**
There are many '\n' in the json-style log

**To Reproduce**
```go
func main() {
	config := zap.NewProductionConfig()
	logger, err := config.Build()
	if err != nil {
		panic(err)
	}
	Log := logger.Sugar()

	Log.Infof("key", "value1 \n value2 ...")
}
```
**Expected behavior**
Want:
```json
{"level":"info","ts":1722577303.808197,"caller":"gotest/main.go:32","msg":"key%!(EXTRA string=value1
 value2 ...)"}
```
Actual:
```json
{"level":"info","ts":1722577303.808197,"caller":"gotest/main.go:32","msg":"key%!(EXTRA string=value1 \n value2 ...)"}
```
**Additional context**

**Comment by tchung1118** [comment]
Our [JSONEncoder](https://pkg.go.dev/go.uber.org/zap/zapcore#NewJSONEncoder) is meant to encode logs into JSON format, and it escapes all keys and values appropriately to meet the JSON specification. You can choose to display JSON-encoded logs however you want, but this is out of zap's control.
