### ISSUE TITLE
Possibility of Reflected Cross-Site Scripting (XSS) attack is detected by static code analysis

### ISSUE THREAD

**Issue by visheshtanksale** [uber-go/zap#1476]
**Describe the bug**
The attacker would be able to alter the returned web page by simply providing modified data in the user input Body, which is read by the decodePutRequest method [here](https://github.com/uber-go/zap/blob/0ba452dbe15478739ad4bab1067706018a3062c6/http_handler.go#L114). This input then flows through the code straight to the output web page, without sanitization.

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**
The input should be validated

**Additional context**

**Comment by abhinav** [comment]
Thanks for reporting, @visheshtanksale. I believe that this is a false positive in the static analysis tool.

decodePutRequest decodes the JSON blob. It produces a level out to the response body if and only if it's a recognized level. All other values result in error. The original input is reproduced to the user only with escaping (e.g. encoding/json's HTML escaper).

I do not believe it's possible to produce arbitrary HTML on the page through this means.
I've put up PR #1477 to demonstrate this.

If you think this is incorrect, please provide more details on how to reproduce this.

**Comment by sywhang** [comment]
Closing this issue as demonstrated by #1477. Please feel free to reopen if you disagree.
