### ISSUE TITLE
Clean up API for timestamp formatting in JSON encoder and text encoder

### ISSUE THREAD

**Issue by prashantv** [uber-go/zap#149]
See https://github.com/uber-go/zap/pull/123#r73206733 for context.

Currently, we have EpochFormatter, NoTime, RFC3339Formatter, TextNoTime, and TextTimeFormat.

We can create a separate option for setting the timestamp key in the JSON encoder, and share the time formatters between the JSON encoder and the text encoder.

**Comment by akshayjshah** [comment]
Landed on dev as part of #264.
