### ISSUE TITLE
Access all fields `*zap.Entry`

### ISSUE THREAD

**Issue by CentaurWarchief** [uber-go/zap#153]
Hi. I was trying to create a `Hook` to report messages to Sentry, but I wasn't able to access the fields to report them as tags. Not sure if I'm doing it in the right way, but `e.Fields()` seems to be a `KeyValue` which I am unable to read:

```Go
func Hook(...) zap.Option {
	return zap.Hook(func(e *zap.Entry) error {
		...
    
		// TODO: capture fields as Sentry tags
		if e != nil {
			packet := &raven.Packet{
				Message:   e.Message,
				Level:     raven.Severity(e.Level.String()),
				Timestamp: raven.Timestamp(e.Time),
				Logger:    Logger,
			}

			_, errChan := raven.Capture(packet, nil)
		}

		return nil
	})
}
```

Thoughts?

**Comment by Kailun2047** [comment]
Running into exactly the same situation. How did you access the specific field after creating your customized encoder? Could you provide some sample code to refer to?

**Comment by Kailun2047** [comment]
Figured it out. You can implement a new zapcore.Core and access the fields in the With() and Write() methods in your own zapcore.Core.

**Comment by axiaoxin** [comment]
@Kailun2047 Could you provide some sample code? thanks

**Comment by feiguoL** [comment]
> Solution was to create a custom encoder and use a decorator to wrap multiple implementing the Encoder interface.
> 
> /cc @txgruppi

how to create a custom encoder and use a decorator to wrap multiple implementing the Encoder interface?

**Comment by vmlellis** [comment]
@axiaoxin  I developed a solution to log in CloudWatch using the zapcore.Core.
Here is a sample code: https://github.com/vmlellis/zapcloudwatchcore
