### ISSUE TITLE
Group test packages into testImport

### ISSUE THREAD

**Issue by imkira** [uber-go/zap#156]
Shouldn't we group test packages (benchmark, asserters, etc.) into `testImport` section as explained in the docs?

https://glide.readthedocs.io/en/latest/glide.yaml/

A simple check with the latest glide did not yield any problems like fetching of unnecessary dependencies, but who knows in the future.

**Comment by akshayjshah** [comment]
Probably, yes! Glide has added quite a few features since we started this project. Feel like opening a PR?

**Comment by imkira** [comment]
Good good! @akshayjshah I just send #165 addressing these and other issues.

**Comment by akshayjshah** [comment]
PR merged - thanks for the contribution!
