### ISSUE TITLE
AddCaller() with JSON output

### ISSUE THREAD

**Issue by maticmeznar** [uber-go/zap#157]
I used to be able to use AddCaller() with JSON output, but since updating Zap, I cannot. Is it ever going to be added back? If yes, when? If no, whats the last version of Zap where it still worked?

Error:
`cannot use zap.AddCaller() (type zap.Option) as type zap.JSONOption in argument to zap.NewJSONEncoder`

**Comment by jdknezek** [comment]
I think the issue is that `AddCaller()` is an `Option` for a `Logger`, whereas you're trying to add it as a `JSONOption` to a `JSONEncoder`. You should change:

```go
logger := zap.New(zap.NewJSONEncoder(zap.AddCaller()))
```

to

```go
logger := zap.New(zap.NewJSONEncoder(), zap.AddCaller())
```

**Comment by akshayjshah** [comment]
@jdknezek is correct - `AddCaller` is an option for the logger, not the encoder. Be aware that `AddCaller` is a bit broken at the moment, and may be removed in the future (see #40).

**Comment by maticmeznar** [comment]
My bad, thank you!
