### ISSUE TITLE
Logger with encoding differing by output?

### ISSUE THREAD

**Issue by jcorbin** [uber-go/zap#159]
So I see that I can have a logger tee'd, e.g. to stdout and a file.  But I'd really like to encode the differently (e.g. text to stdout, json to the file).

Is this presently possible by, at worse, an (ab)use of Hooks?

What would it take to get support for this, if it's not currently supported?

**Comment by prashantv** [comment]
I think this would require a `TeeLogger` which takes multiple underlying loggers and call all functions on both. That way we can have very separate logging configurations (e.g., console gets everything using the TextEncoder, log file only contains warnings or higher encoded using JSON).

**Comment by akshayjshah** [comment]
This was resolved in #161.
