### ISSUE TITLE
Next Steps wrt level

### ISSUE THREAD

**Issue by jcorbin** [uber-go/zap#166]
Capturing the highlights of an offline conversation with @prashantv and @akshayjshah : 

- [x] make it so that `.Log` doesn't actually `panic` or `os.Exit` for `PanicLevel` and `FatalLevel`; this will allow for higher level loggers like `TeeLogger` to correctly fan out to more than one internal logger

We seem to have at least fundamental agreement that the `SetLevel` and `Level` methods weren't actually necessary; most of the conversation centered around instrumental differences in how else to do it.  The key feature that `SetLevel` is providing is dynamic runtime change (e.g. by the http `levelHandler`).  An initial way to eliminate them may look like:
- [x] create an explicit "dynamic level" zap option #180 
  - a first cut of this may first be specific to the http handler
  - follow up work could generalize, e.g. so that the "dynamic level" option constructor, also returns a "controller" that could be shared by more than one runtime mechanism
- ~~this would also set us up well to factor out a "level logger" higher level logger that implements only the level filter logic; this would allow sharing between things like the spy logger and the primary concrete logger~~ (this turned out to not be necessary; DynamicLevel suffices)

- [x] make CheckedMessage "compose better"; it wasn't entirely clear what the benefits were here, I'm hoping @prashantv can reply here with details since he had a clearer handle on this part than I #182

**Comment by prashantv** [comment]
The `CheckedMessage` composition is basically allowing creation of a `CheckedMessage` from other checked messages.

E.g.,
```go
func MultiCheckedMessage(msgs... *CheckedMessage) *CheckedMessage
```

The behaviour I'd expect is:
 - If all of them are `!OK()`, it returns `nil`
 - If only one is `OK()`, it returns that specific instance
 - If there are multiple non-nil entities, we'll need to have a field `[]*CheckedMessage` inside the `CheckedMessage` struct that contains the non-nil entries. This `CheckedMessage` would just call `Write` on the list of `CheckedMessage` rather than using the logger/level.

Does that sound reasonable?

**Comment by akshayjshah** [comment]
That's more or less what I had in mind. Note that it should be safe to pool the `[]*CheckedMessage` and free it at the end of `Write`, since we already ensure that checked messages aren't re-used.

**Comment by jcorbin** [comment]
The only rub there @prashantv:
- as seen in #168, `(*CheckedMessage).Write` must call `.Panic` and '.Fatal` directly to make a `logger.Check(PanicLevel, "lol").Write` equivalent to a `logger.Panic`
- I think this can still work tho, if we introduce an unexpected `(*CheckedMesasge).writeLog` method:
  - will just call `logger.Log(m.lvl, ...)`, which won't panic or exit
  - that will be used by the, potentially multi-level tree, of checked message recursion
  - then `(*CheckedMessage).Write` will start out with "if I have any sub-checked messages, call their writeLogs, and then maybe panic or exit"

**Comment by jcorbin** [comment]
Per comments on #161, I think we should also change the way "DFatal" level works, to also be "just a level" with special handling in its namesake method.  TBD whether "Log" should pass through the level, or map it to "error" if we end up trying to directly log at the "DFatal level".

**Comment by jcorbin** [comment]
Another bead on the "DFatal is weird" thread: in #172, I noticed that sampler's `DFatal` logic never even did "always fatal in dev", unless I misunderstand the code.

**Comment by jcorbin** [comment]
Done.
