### ISSUE TITLE
Make DPanic an actual level and replace DFatal

### ISSUE THREAD

**Issue by jcorbin** [uber-go/zap#175]
DFatal not being an explicit log level, but instead an implementation detail of Meta, hurts composability:
- as mentioned on #166
- as discussed during review of #172 (this is the requested tracking issue)

**Comment by jcorbin** [comment]
My proposal:
- add `DFatalLevel` before `PanicLevel`, or before `FatalLevel` (putting it after `FatalLevel` requires more code change, as `FatalLevel` is assumed maximal; yes that means we're missing a semantic name for "maximal logging level", but that's _another_ issue ;-) )
- add a `Meta.DFatal(log, msg, fields)` convenience method that can be used to ease implementation (e.g. `func (log TConcreteLogger) DFatal(...) { log.Meta.DFatal(log, ...) }`), all it will do is delegate to `logger.Error` or `logger.Fatal` depending on `Meta.Development`

**Comment by akshayjshah** [comment]
@jcorbin Plan makes sense, but let's replace DFatal with DPanic. It accomplishes the same blow-up-in-dev goal (and actually dumps a stack trace with the panic), and it fits more neatly into the level hierarchy between `ErrorLevel` and `PanicLevel`.
