### ISSUE TITLE
Passing *zap.Entry around?

### ISSUE THREAD

**Issue by vadimyer** [uber-go/zap#199]
In logrus you can pass Entry type around and use an included *Logger reference so you have access to Logger's functions. I've got a project built with logrus where you have to change lots of logic because of zap's inability to pass Entry around like in logrus. Could this be implemented here in any way?

**Comment by akshayjshah** [comment]
Hi @vadimyer - if you're passing `logrus.Entry` around your application and you'd like to migrate to zap, you probably want to start passing `zap.Logger` instead. It serves the same purpose - it accumulates key-value pairs and exposes logging functions.
