### ISSUE TITLE
Rename project to go.uber.org/zap

### ISSUE THREAD

**Issue by breerly** [uber-go/zap#203]
I've setup zap on go.uber.org, so that we can take advantage of this import path.

I'd like to get ahead of this breaking change before we 1.0, and before YARPC takes on zap as a hard-dependency.

**Comment by akshayjshah** [comment]
A+, let's do this before 1.0.

**Comment by akshayjshah** [comment]
Landed on the dev branch in #206, which will take effect as part of the 1.0 release.
