### ISSUE TITLE
Is there anyway to output the different level log into separate file?

### ISSUE THREAD

**Issue by arthurkiller** [uber-go/zap#204]
Hey dude, I have a question there. I have update the project log from see-log into zap. But we need to  put the different level log into different file.
Is there anyway to output the different level log into separate file?

**Comment by arthurkiller** [comment]
Or just make several loggers to print the log?

**Comment by akshayjshah** [comment]
A very small addition would allow this - see @jcorbin's comment on #205. If you'd like to add `LevelEnablerFunc` and some unit tests, we're happy to accept a PR.

**Comment by arthurkiller** [comment]
#208

**Comment by arthurkiller** [comment]
I have added this , hope it works! @akshayjshah

**Comment by akshayjshah** [comment]
PR landed, so I'm closing this issue. We'll refine our approach to these sorts of use cases further as we push to 1.0.
