### ISSUE TITLE
Attach an arbitrary amount of fields to log message

### ISSUE THREAD

**Issue by vadimyer** [uber-go/zap#209]
For example, I have a log call like this, predefined in a function:

```
log.Info("Something", log.String("someField", someValue), log.String("someSecondField", someSecondValue"))
```

How do you "attach" an arbitrary set of fields to this one? I'm planning to pass various unknown fields to this call. Surely, my function should be rewritten, but I couldn't find a way how you do that in zap.

**Comment by prashantv** [comment]
You should either pass a logger in to the function, so the calling function can add any number of fields using `log.With(..)`, or you can have the caller pass in `fields []zap.Field` and do `log.With(fields...).Info("Something", log.String("someField", someValue), ...)`

This should be similar regardless of the logger you use -- you can either pass a logger with the context build up, or you can pass the context in explicitly and add that to the logger in the function.
