### ISSUE TITLE
How do I change the format of the JSON log?

### ISSUE THREAD

**Issue by dxvgef** [uber-go/zap#217]
How do I change the format of the JSON log to '2006-01-02 15:04:05'?
I can use `zap.TextTimeFormat("2006-01-02 15:04:05")` in the text log, but how do I do in the JSON log?

**Comment by prashantv** [comment]
The [`TimeFormatter`](https://godoc.org/github.com/uber-go/zap#TimeFormatter) implements the `JSONOption` interface, so you can use that to customize the JSON time formatting.

This allows you to pass in a custom function that encodes a `time.Time` into a `zap.Field` to customize either the key, or the time formatting.

There are some default time formatters you can use too:
https://godoc.org/github.com/uber-go/zap#EpochFormatter
https://godoc.org/github.com/uber-go/zap#RFC3339Formatter

This API may change, I'd like to combine the text options with the JSON options before 1.0.
