### ISSUE TITLE
Support json.RawMessage

### ISSUE THREAD

**Issue by magicalbanana** [uber-go/zap#218]
Any plans to support json.RawMessage anytime soon?

**Comment by magicalbanana** [comment]
Nevermind, you can just do simple `string(json.RawMessage)`.

**Comment by prashantv** [comment]
You probably shouldn't do `string(json.RawMessage)` wince that will escape the underlying JSON blob. If you want to maintain the JSON structure and not just encode it as a string, you should use `zap.Object(json.RawMessage)`.

**Comment by magicalbanana** [comment]
@prashantv but if I did this the output is not JSON though, I think it's base64 encoded.

**Comment by prashantv** [comment]
@magicalbanana It looks like the `MarshalJSON` method on the `json.RawMessage` is on the pointer,
https://golang.org/pkg/encoding/json/#RawMessage.MarshalJSON

So instead of passing the `json.RawMessage` directly, pass it as a pointer,
```go
raw := json.RawMessage(`{"a": "b"}`)
logger.Info("Data", zap.Object("nested", &raw))
```

The output looks like:
```
{"level":"info","msg":"Data","count":1,"nested":{"a":"b"}}
```

**Comment by JeanMertz** [comment]
Is this still supposed to work in the latest Zap version?

I have a JSON structured `[]byte` that I'd like to be included in the log as JSON objects, not as a string.

Using the above results in:

```
*json.RawMessage does not implement zapcore.ObjectMarshaler (missing MarshalLogObject method)
```

**Comment by billf** [comment]
`zap.Object` changed from the pre-release behavior to its current stable behavior.
Use its replacement, [zap.Any](https://godoc.org/go.uber.org/zap#Any).

```
    logger, _ := zap.NewProduction()
    raw := json.RawMessage(`{"a": "b"}`)
    logger.Info("Data", zap.Any("nested", &raw))
```
```
{"level":"info","ts":1496684810.104784,"caller":"tmp/zapjson.go:12","msg":"Data","nested":{"a":"b"}}
```

**Comment by sheshankkodam** [comment]
I didn't cast the message to Zap.Any but still works. 

```
s := `{"a": "b"}`
raw := json.RawMessage(s)
sugar.Infow("custom","msg", &raw)
```

```
{"level":"info","ts":1529364812.8971648,"msg":"custom","msg":{"a":"b"}}
```

**Comment by MarloGrayhat** [comment]
@prashantv  what am I doing wrong?
When using
```go
logger, _ := zap.NewProduction()
raw := json.RawMessage(`{“a”: “b”}`)
logger.Info(“Data”, zap.Any(“nested”, &raw))
```

I get 
```json
{"level":"info","ts":1716902133.7899282,"caller":"ws/client.go:186","msg":"Data","nested":"eyJhIjogImIifQ=="}
```
