### ISSUE TITLE
Consider separating leaf and middleware Facilities

### ISSUE THREAD

**Issue by akshayjshah** [uber-go/zap#224]
(Relevant only to the `dev` branch. See the large "Facilities could be further broken up" comment on #201.)

Facilities are either (1) middleware for other facilities (e.g., sampling or teeling) or (2) leaves, like the `ioFacility`. Consider separating these types so that implementors need to write less boilerplate.

**Comment by jcorbin** [comment]
Prior thought on this direction describe in https://github.com/uber-go/zap/pull/201#issuecomment-266893762

**Comment by akshayjshah** [comment]
We ended up punting on this.
