### ISSUE TITLE
how to use zap as io.writer

### ISSUE THREAD

**Issue by weisd** [uber-go/zap#229]
how to use zap as io.writer?

**Comment by akshayjshah** [comment]
I'm not sure what you're asking - can you clarify a bit? You can't use a logger as an `io.Writer`, since loggers expect their input to have some structure.

**Comment by russelldc** [comment]
I'm not sure exactly what he's asking either, but it could be what I've been trying to find out. The rolling log helper, [lumberjack](https://github.com/natefinch/lumberjack), claims that it "plays well with any logging package that can write to an **io.Writer**, including the standard library's log package". I'm not entirely sure how to connect the two, though.

**Comment by akshayjshah** [comment]
Zap outputs must implement the `SyncWriter` interface - since we may be calling `panic()` or `os.Exit(1)` immediately after writing data, we need to be able to force a sync. You can add a no-op `Sync` method to any `io.Writer` with the `AddSync` function.

**Comment by russelldc** [comment]
@akshayjshah Thanks, that worked for my issue

**Comment by akshayjshah** [comment]
Assuming that this is resolved now; feel free to re-open if there's still an open issue.

**Comment by obitech** [comment]
Here is another way to make it work, in case you initialise your logger at a different point or what to use `zap.L()`:

```
stdOutLogger, err := zap.NewStdLogAt(zap.L(), zapcore.ErrorLevel)
if err != nil {
	return nil, err
}

// stdOutLogger.Writer()
```

**Comment by abhinav** [comment]
@obitech If you're trying to obtain an `io.Writer` you can write to, that will in turn write to a Zap logger, you can use [zapio.Writer](https://pkg.go.dev/go.uber.org/zap/zapio#Writer). (Be sure to call Close on it!)
