### ISSUE TITLE
Prefer localtime for TextEncoder

### ISSUE THREAD

**Issue by tesujimath** [uber-go/zap#232]
Currently the TextEncoder outputs timestamps in UTC.  I suggest changing this to localtime, in the interest of being more human-legible.

This is a one-line change to logger.log(), which won't affect the JSONEncoder, since that is of course timezone-independent.

I considered whether this should be an option, but I don't think it's worth it, as I'm not really seeing a use for UTC over localtime for human-legible output.

Will you accept such a pull request?

**Comment by akshayjshah** [comment]
Good point, this should be configurable. Please hold off on opening any PRs for now, since the current `TextEncoder` will be almost entirely replaced in version 1.0 - any work you do now will be wasted.

Thanks for putting this on my radar, though.

**Comment by tesujimath** [comment]
OK, that sounds good.

**Comment by dxvgef** [comment]
@akshayjshah I also have such a demand, when will the 1.0 version be released?

**Comment by akshayjshah** [comment]
We're hoping for the end of the month, though it may slip by a bit. You can follow the [1.0 milestone](https://github.com/uber-go/zap/milestone/1) for details.

**Comment by dxvgef** [comment]
@akshayjshah Thank you, come on!

**Comment by akshayjshah** [comment]
RC1 for version 1.0 is landing on master tonight, and this has been fixed. Closing.
