### ISSUE TITLE
Order of fields added using logger.With

### ISSUE THREAD

**Issue by madhuravi** [uber-go/zap#233]
Hello,

I am using logger.With from here https://github.com/uber-go/zap/blob/master/logger.go#L75 to inject context/trace information to application logs.

Usage https://github.com/uber-go/fx/blob/master/modules/uhttp/filters.go#L77
logger.With("trace id", "12345")
I am envisioning logs to be:
"trace id": 12345, "msg":"Received request"
"trace id": 12345 "msg":"Processing request"

Right now I see the fields added at the end of the logs like 
"msg":"Received request","trace id":12345

Contextual information seems most useful at the beginning since log line length can vary and readability is greatly enhanced if contextual information is in the same place. Thoughts?

Thanks,
Madhu

**Comment by akshayjshah** [comment]
Hey Madhu - yep, sounds reasonable. Context should probably be last-in, first-out, so that the most recently-added fields are furthest to the left in the printed output. However, I still think that the level, timestamp, and log message should be the left-most elements, followed by all the context fields.

Is that a reasonable compromise?

**Comment by madhuravi** [comment]
Yep definitely, makes sense.

**Comment by jcorbin** [comment]
Given the current shape of dev, we could pretty easily achieve: `time,level,msg,log-site-fields,all-with-fields-in-fifo-order`. I'm not sure how we can achieve lifo order on that final component without incurring some performance hit (however only benchmarking can tell how material such hit may be).

However doing LIFO order invokes precedence problems unless we also take advantage of #192 to actually replace any conflicts.

All-in-all I think it's possible to do, but to me this whole topic is trying to optimizing the json encoder for human consumption; I'm not sold that we want to compromise on anything towards human consumption of json being an external tools affair.

**Comment by madhuravi** [comment]
Apologies I just read Akshay's message again. That's not what I'm looking for. I'm not really concerned about LIFO or FIFO for context fields. I just want the context fields to appear before the message.

time, level, context fields, message

My main goal is readability. Messages can be of arbitrarily length and I want the context fields in one place so logs can be read easier,

**Comment by prashantv** [comment]
I think having the message first is very important -- no point seeing fields like "service: foo" if I don't have the context for the log.

For readability, I think multi-line output is the best option:
```
time LEVEL this is the message
  service:foo error:message
```

That way the context is always easy to find, but we still have the message right there too.

**Comment by madhuravi** [comment]
> I think having the message first is very important -- no point seeing fields like "service: foo" if I don't have the context for the log.

Aren't the context log fields (trace id, span id) what establish the context for the logs? They really indicate a unique id for the request. Look at a comparison here:

Context first:
level: INFO, requestID: 12345 msg: "The Go programming language is an open source project that is concurrent, class-based, object-oriented"
level: INFO, requestID: 22222 msg: "Java is a general-purpose computer programming language"
level: INFO, requestID: 12345 msg: "Go is expressive, concise, clean, and efficient. Its concurrency mechanisms make it easy to write programs that get the most out of multicore and networked machines, while its novel type system enables flexible and modular program construction."
level: INFO, requestID: 12345 msg: "Go compiles quickly to machine code"

Message first:
level: INFO, msg: "The Go programming language is an open source project that is concurrent, class-based, object-oriented" requestID: 12345
level: INFO, msg: "Java is a general-purpose computer programming language" requestID: 22222
level: INFO, msg: "Go is expressive, concise, clean, and efficient. Its concurrency mechanisms make it easy to write programs that get the most out of multicore and networked machines, while its novel type system enables flexible and modular program construction." requestID: 12345
level: INFO, msg: "Go compiles quickly to machine code" requestID: 12345

The "Context first" option is intuitive, you can see all the traceID/requestIDs in one place.

>  For readability, I think multi-line output is the best option
Multi-line outputs are not very "grep" friendly. In past teams, we've had a hard time with multi-line grep-ing. I much prefer one line log statements.

**Comment by jcorbin** [comment]
Putting the message last should be possible, and a relatively performant encoder option to add; TBD before or after 1.0.  That said my issue is mainly with your goal being readability of json: our json format intentionally trades off for machine consumption, leaving consumption ease (like field re-ordering) to external tools like jq.

**Comment by jcorbin** [comment]
In my opinion, the ordering that makes most sense towards a default is `time,level,all-with-fields,msg,log-site-fields`; in other words:
- time and level are special; despite being log-site specific, they come first
- next comes all contextual fields
- then the log site message
- then any additional log site fields

I believe that this would be a decent compromise towards @madhuravi's readability concerns, while not impinging speed, requiring replacement, or putting the even-more-variable fields before the message?

**Comment by prashantv** [comment]
> Aren't the context log fields (trace id, span id) what establish the context for the logs? They really indicate a unique id for the request.

Specific fields may establish context, but what about "host", or "commit", or "error". Does it make sense to see an "error" field before you've seen the message that produced the error?

> Look at a comparison here:
> The "Context first" option is intuitive, you can see all the traceID/requestIDs in one place.

I don't think your logs aren't very indicative of a real world log, which will contain so much context that the message won't be visible. Here is a more real-world example:
```
12:12:03 INFO, host=my-test-server service=my-service commit=235cffa connID=5 error=net.Dial failed requestID: 12345 msg: "Failed to connect to client"
```

(That's actually less than 1/3rd of the fields available from a real log)

All of these are just fields as far as the logger is concerned. The logger shouldn't and won't know which fields are "useful" to display first. If you really know what you want, then like @jcorbin said, maybe you want to just log JSON, and pipe through a `jq` to select specific fields.

> Multi-line outputs are not very "grep" friendly. In past teams, we've had a hard time with multi-line grep-ing. I much prefer one line log statements.

Agreed. `grep -C` can help a little with this, but it's not ideal.

**Comment by madhuravi** [comment]
Agreed, the logging context or fields can easily get bloated. I think the problem may be that the log "fields" seemed to be used for many different reasons. 
I think certain fields like timestamp, log level and requestID are more important than others. These are relevant every time someone's looking at logs. Certain others like service, connId etc. I think are secondary fields that the user probably already knows or cares about only in specific cases. These secondary fields probably don't even need to be present at every log line.

If there a way the API can distinguish between "meta" or important fields coming first versus secondary fields at the end? Or should we only consider "meta" fields as fields even and log secondary fields differently?

Another thing to potentially look at is grouping fields under different logs for eg.
main log:
time, level, reqID, msg

perf/debug log:
time, reqID, commitID, connID, numConns etc.

**Comment by akshayjshah** [comment]
I'd assumed that we were only discussing the text encoding; JSON output isn't, and shouldn't, be optimized for human consumption. We should instead assume that all JSON output is piped through some combination of `grep` and `jq` (or ingested into ElasticSearch and viewed in Kibana).

> Aren't the context log fields (trace id, span id) what establish the context for the logs? They really indicate a unique id for the request.

No, I don't think so. It's a fallacy to think that there's even a request in flight when many logs are generated. Consider an ETL service, errors on startup, or anything else not in a request handler.

> Multi-line outputs are not very "grep" friendly. In past teams, we've had a hard time with multi-line grep-ing. I much prefer one line log statements.

Readability is only a concern when there's a human reading the logs. This is, ipso facto, not the case when you're piping logs to `grep` or `jq`. If there's an interactive console connected, we should default to logging text in whatever form makes the most sense for humans (we can iterate separately on single- vs. multi-line). If the output is being piped to another command or a file, we should default to logging JSON.

Overall, I'm unconvinced that this is a significant issue in practice. Virtually all JSON and text logs from our current Go services are going through Logrus. Since Logrus uses `encoding/json` to encode a `map[string]interface{}`, the fields are just blindly alphabetized. (See https://play.golang.org/p/S-1cpKqBF2 for an example.) I have yet to hear a groundswell of complaints about the *ordering* of the resulting JSON.

**Comment by madhuravi** [comment]
I see. I was thinking about text encoding. As a service owner, manually retrieving and parsing logs for debugging. It looks like the decision was to keep JSON and build tooling around it so the user is not expected to read raw logs. It does not really matter in that case since the tooling will retrieve and display relevant fields in the right order. Is that right?

I think the user has a lot of flexibility reading raw logs that tools such as ELK don't sufficiently provide sometimes. This is the use case I was after. Yes the user can use commands to order it but it's nice to have a consistent pattern so the user can see and navigate through logs easily without extra commands. If this is a non-goal, then ordering is not relevant.

**Comment by akshayjshah** [comment]
The console encoder that's shipping as part of 1.0 has landed on the dev branch; it keeps field ordering largely the same as the JSON logger. Closing this, since we don't have any plans to change this before the stable release.

If we later decide that we want a different console encoding, we can always add more config options or a completely separate encoder.
