### ISSUE TITLE
Colored log output

### ISSUE THREAD

**Issue by kujenga** [uber-go/zap#234]
I'm wondering if there are any plans to implement colorized log output in this library. While it might not be something one would enable in a production environment, for local development it can be quite nice. Alternatives like logrus provide this sort of functionality.

Just based on the public API, it seems like this could be implemented as a [TextOption](https://godoc.org/github.com/uber-go/zap#TextOption). If it isn't slated for development, would you be open to a contribution with it?

**Comment by akshayjshah** [comment]
I'm definitely open to a contribution that colorizes the text encoder output, but it'll be best if you hold off for a little bit - we're refactoring very aggressively on the `dev` branch in preparation for a 1.0 release, and any work you put in now will likely be wasted.

**Comment by kujenga** [comment]
Very cool, fair enough! I'll keep tabs on the milestone https://github.com/uber-go/zap/milestone/1

**Comment by kujenga** [comment]
@akshayjshah are you just cleaning up or is there any new info on this issue?

**Comment by akshayjshah** [comment]
Support for coloring landed in #307, at least in part.

**Comment by cup** [comment]
https://github.com/uber-go/zap/issues/234
https://github.com/uber-go/zap/issues/489
https://github.com/uber-go/zap/issues/648
https://github.com/uber-go/zap/issues/688
https://github.com/uber-go/zap/pull/307
