### ISSUE TITLE
Clarify how to use the `zwrap.Standardize()` as *log.Logger replacement

### ISSUE THREAD

**Issue by djui** [uber-go/zap#246]
I like the idea to `zwrap` but I can't see how to use it as a `log.Logger` replacement, but I can't see how to use it as a drop-in replacement?

I can image the use case would be where on library or framework allows for an interface that matches the `log.Logger`, however, often in the `stdlib` that's not the case, e.g. `net/http.Server`.

Since the only way I know to customise the standard logger is to provide a custom `io.Writer`, I wonder if that approach might be a good addition or even better.

I think the comment `// StandardLogger is the interface exposed by the standard library's log.Logger.` is a bit misleading.

**Comment by akshayjshah** [comment]
See the discussion on #187. Before releasing 1.0, we're dropping the `StandardLogger` interface in favor of exactly the approach you describe.
