### ISSUE TITLE
Request for comments about a LTSV encoder

### ISSUE THREAD

**Issue by hnakamur** [uber-go/zap#253]
First of all, thanks for a nice logging library for Go!

I created a [Labeled Tab-separated Values (LTSV)](http://ltsv.org/) encoder for zap.
https://github.com/hnakamur/zap-ltsv

Could you take a look and give some comments to issues?

- [Ask about copyright holder notice · Issue #1 · hnakamur/zap-ltsv](https://github.com/hnakamur/zap-ltsv/issues/1)
- [Should the LTSV encoder be a separate package or be a part of the original package? · Issue #2 · hnakamur/zap-ltsv](https://github.com/hnakamur/zap-ltsv/issues/2)

Thanks for your time in advance.

**Comment by akshayjshah** [comment]
Awesome - I'm glad to hear that zap was useful for you! I haven't worked with the LTSV encoding before - from the docs, I can see that it's accepted by a variety of logging tools. Are you aware of any common software that *emits* LTSV logs by default?

I'm going to defer this until after the 1.0 release, since the encoder API is changing (though nearly all the code you have should still work, it'll just require some find&replace updates). Once we've released 1.0, I'll take a closer look at your code and figure out whether we should include it in zap itself.

**Comment by hnakamur** [comment]
Thanks for your kind words.
I don't know anything that _emits_ LTSV logs by default config.
However it is easy to setup Apache or nginx configs to _emit_ LTSV logs.

Apache config example:

```
LogFormat "host:%h\tident:%l\tuser:%u\ttime:%t\treq:%r\tstatus:%>s\tsize:%b\treferer:\%{Referer}i\tua:%{User-Agent}i" combined_ltsv
```

nginx config example:

```
log_format ltsv "time:$time_local"
                "\thost:$remote_addr"
                "\tforwardedfor:$http_x_forwarded_for"
                "\treq:$request"
                "\tstatus:$status"
                "\tsize:$body_bytes_sent"
                "\treferer:$http_referer"
                "\tua:$http_user_agent"
                "\treqtime:$request_time"
                "\tcache:$upstream_http_x_cache"
                "\truntime:$upstream_http_x_runtime"
                "\tvhost:$host";
```

Also, with [Fluentd | Open Source Data Collector | Unified Logging Layer](http://www.fluentd.org/), you can convert logs in other formats to LTSV using [Text Formatter Overview | Fluentd](http://docs.fluentd.org/v0.12/articles/formatter-plugin-overview).

I understand that you defer this pull request after zap 1.0 release.
I'll update the LTSV encoder for API changes.

Thanks!

**Comment by akshayjshah** [comment]
Hey @hnakamur - the encoder APIs are stable now, so this is a good time to update your encoder. Since I'm not familiar with this encoding and we don't use it internally, let's keep it in a separate package.

#330 may be relevant to you, though.

**Comment by akshayjshah** [comment]
Closing this issue, since there's no active work to do in zap.

**Comment by hnakamur** [comment]
Sorry for being late. I noticed your mention yesterday.
I've updated the LTSV encoder at https://github.com/hnakamur/zap-ltsv/pull/5.
Thanks again for a great logging library!
