### ISSUE TITLE
LevelFlag should support flag.FlagSet

### ISSUE THREAD

**Issue by mark-adams** [uber-go/zap#256]
The current implementation of `LevelFlag` doesn't support `flag.FlagSet`. This makes it difficult to use with some logging configurations.

The two simplest solutions are:

1. Modify LevelFlag to take a `flag.FlagSet` as the first argument; or
2. Create a new function called `LevelFlagForSet` or something like that.

Essentially, I'm proposing changing `LevelFlag` to have the following signature:

```
func LevelFlag(flags *flag.FlagSet, name string, defaultLevel Level, usage string) *Level
```

I'm more than happy to create a PR once the maintainers weigh in

**Comment by akshayjshah** [comment]
Hey @mark-adams - thanks for taking a look at zap! All current development is happening on the `dev` branch, where we're getting close to a stable 1.0 release.

On that branch, `Level` implements `flag.Value`, so it's easy to use with `FlagSet.Var`. I've added some tests to verify and demonstrate this in #257. As part of our final documentation push (#139), we'll add examples for this.

**Comment by akshayjshah** [comment]
Landed on dev.
