### ISSUE TITLE
Add first-class encoder support for times and durations

### ISSUE THREAD

**Issue by akshayjshah** [uber-go/zap#259]
Remove the `Time` field constructor in favor of more-explicit `Epoch` (floating-point seconds since epoch) and `ISO8601` constructors.

If necessary, we can also include `EpochMillis` (int64 milliseconds since epoch).

**Comment by jcorbin** [comment]
I find going this route a little unfortunate: I'd rather stay with `Time` and get the encoders looped in "what does it mean to encode time", rather than have it variable per-field-per-log-site.

At any rate, an `EpochMillis` should probably be `float64` rather than `int64`.

**Comment by akshayjshah** [comment]
That's a fair point, particularly for concepts so intimately connected with logging. I'll amend the title of this issue to reflect that.

**Comment by akshayjshah** [comment]
Landed on dev.
