### ISSUE TITLE
Is it possible to change the log level on the fly?

### ISSUE THREAD

**Issue by katzien** [uber-go/zap#261]
Hey folks!

I couldn't find any examples of changing the log level "on the fly", without having to recreate the Logger. I'm wondering if it's possible at all?

Thanks,
Kat

**Comment by ansel1** [comment]
you can set the loggers level to a zap.DynamicLevel(). Retain a reference
to that level object. it's a strict with methods for changing its current
level.

**Comment by akshayjshah** [comment]
@ansel1 has it right.

```go
dyn := zap.DynamicLevel() // defaults to Info
logger := zap.New(zap.NewJSONEncoder(), dyn)
logger.Debug("foo") // disabled
dyn.SetLevel(DebugLevel) // safe for concurrent use
logger.Debug("foo") // now this is enabled
```

**Comment by akshayjshah** [comment]
Keep in mind that, while something very similar will be possible in the upcoming 1.0 release, the way loggers are constructed will change somewhat.

**Comment by katzien** [comment]
Ah, thank you very much @ansel1 and @akshayjshah, that's awesome! Thanks for the heads up as well, I already assumed that things will change somewhat with 1.0 so I'm mentally prepared for all the upcoming refactoring ;) Love zap though so it'll be totally worth it!

**Comment by jinleileiking** [comment]
seems not work now.

**Comment by jinleileiking** [comment]
not work now.

**Comment by billf** [comment]
> seems not work now.
> not work now.

these are not actionable bug reports.

**Comment by jinleileiking** [comment]
I just say 
```
dyn := zap.DynamicLevel() // defaults to Info
logger := zap.New(zap.NewJSONEncoder(), dyn)
logger.Debug("foo") // disabled
dyn.SetLevel(DebugLevel) // safe for concurrent use
logger.Debug("foo") // now this is enabled
``

 this codes not worked now.

**Comment by billf** [comment]
things have changed quite a bit since Feb 1. 

https://godoc.org/go.uber.org/zap#AtomicLevel is now the way to dynamically change levels.

if you have problems with `zap.AtomicLevel` please open this a new issue with a reproduction case and the error messages or compilation errors you see.
