### ISSUE TITLE
Lossy nanosecond timestamps with EpochFormatter

### ISSUE THREAD

**Issue by errnoh** [uber-go/zap#275]
While doing nanosecond level logging I noticed that some of the events were happening in wrong order.
After investigating I noticed that the EpochFormatter is doing lossy conversion due to float64 rounding errors:

(see example [here](https://play.golang.org/p/y8tRt8ebY_) )

time: 1486215887.584922537
zap : 1486215887.584922552

time: 1486215941.624710199
zap : 1486215941.624710083

While RFC3339Formatter strips the sub-second information. (time.RFC3339Nano is there for nanoseconds)

**Comment by akshayjshah** [comment]
Fixed in your PR - thanks again!
