### ISSUE TITLE
Import path changed

### ISSUE THREAD

**Issue by arthurkiller** [uber-go/zap#292]
package github.com/uber-go/zap
        imports go.uber.org/zap/internal/bufferpool: use of internal package not allowed
package github.com/uber-go/zap
        imports go.uber.org/zap/internal/multierror: use of internal package not allowed

seems github.com/zap has dependent in internal package in go.uber.org . 
Are you going to move this package to there?

**Comment by arnoudhgz** [comment]
Same issue here, can't build a bunch of packages anymore

**Comment by naibaf0** [comment]
If you switch to `"go.uber.go/zap"` it works as it should.

**Comment by yacloud** [comment]
@naibaf0  so the work around is switch to `go.uber.org/zap` ? or permanently

**Comment by naibaf0** [comment]
I am doing it as a workaround, until someone answers this in an official capacity. :)

**Comment by arnoudhgz** [comment]
The switch to `"go.uber.org/zap"` was not working because I use external dependencies too, that depend on the same "zap" package.

I started using [`"govendor"` ](https://github.com/kardianos/govendor) and fetched this commit `govendor fetch github.com/uber-go/zap@35cd7966cc81adc0449c91b3f6b1939812be73aa`

This is a temporarely workaround for me, but I am having deadlines for projects, so this is the way to go for me.

**Comment by arthurkiller** [comment]
yes and yes it can not be fixed by change into github.com

But I don't think vendor is a good way to solve this.

Best regards 
✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️
Arthur lee

**Comment by akshayjshah** [comment]
Apologies for the confusion - I'll update the release notes and the changelog to document this better. 

The official import path for the project is now "go.uber.org/zap" - as part of updating to v1.0.0-rc.1, you'll need to update your import paths. If you have dependencies that use zap, they'll also need to upgrade; in the meantime, you can pin to v0.1.0. If any of those dependencies are public, let me know - I can (slowly) help to migrate them.

**Comment by arthurkiller** [comment]
can not wait for it！ finally v1.0 comes out！

Best regards 
✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️
Arthur lee

**Comment by akshayjshah** [comment]
Readme, changelog, and release notes all updated.

**Comment by Vish17agr** [comment]
Hi akshayjshah,
 I am new to influxDb. I am getting the below error while compiling the influxDB thorugh cmd.

C:\Go\projects\src\github.com\influxdata\influxdb>go get -u -f ./...
package github.com/uber-go/zap: code in directory C:\Go\projects\src\github.com\uber-go\zap expects import "go.uber.org/zap"

How can change the import path in influxDB to resolve this issue.

any help is very much appreciated

**Comment by naibaf0** [comment]
See here: https://github.com/influxdata/influxdb/issues/8733

Influxdb uses gdm for dependecy management and they use another version of zap.

**Comment by Vish17agr** [comment]
Hi naibaf0,

Not able to run gdm restore 
C:\Go\projects\src\github.com\influxdata\influxdb>gdm restore
'gdm' is not recognized as an internal or external command,
operable program or batch file.

Sorry for annoying you

**Comment by naibaf0** [comment]
Yes, because gdm is an external dependency management program, you need to install it first ;)
This should help: https://github.com/sparrc/gdm

Otherwise maybe ask at the influxdb repo, I think this is more an issue with influxdb code than with zap

**Comment by Vish17agr** [comment]
Hi naibaf0,

Can you help be changing the official import path.
I think that might work.

Thanks

**Comment by naibaf0** [comment]
Hi,
> panic: open C:\Go\projects\bin\Godeps: The system cannot find the file specified.

from what I can tell you are missing godeps, which seems to be a dependency rfom gdm.

You should ask for help from the influxdb community/maintainers, it is their code you have an issue with.

Changing the import paths in code won't work I think, because zap had various breaking changes before version 1.0 was released, so influxdbs code won't work unless you use the dependency management and the correct version.

**Comment by Vish17agr** [comment]
Thanks for your response.

I have uninstalled everything and then installed the influxdb after installing the gdm dependency.
This way it worked for me.
