### ISSUE TITLE
Unable to download zap package 

### ISSUE THREAD

**Issue by udbhav1990** [uber-go/zap#295]
Hi,

I am trying to download zap package using below command

"go get github.com/uber-go/zap"

I am using go version 1.7.4 and I am getting below error

package .
	imports github.com/uber-go/zap
	imports go.uber.org/zap/internal/bufferpool: use of internal package not allowed
package .
	imports github.com/uber-go/zap
	imports go.uber.org/zap/internal/multierror: use of internal package not allowed

Please let know how to fix this issue?

Thanks,
OverKill.

**Comment by Smadarl** [comment]
I'm having this same issue.  How did you fix it?

**Comment by akshayjshah** [comment]
The import path of zap has changed as part of the 1.0 release candidate: https://github.com/uber-go/zap/releases/tag/v1.0.0-rc.1

You'll need to `go get go.uber.org/zap` and update import paths in your code to match.

**Comment by Smadarl** [comment]
Thanks.  Just saw the other issue already on this.  Probably why this was closed, I just happened to see this issue first.
