### ISSUE TITLE
Confusion about import url, Project description not up to date

### ISSUE THREAD

**Issue by naibaf0** [uber-go/zap#296]
With the 1.0.0-rc1 release, it is (apparently) not possible anymore to use `"github.com/uber-go/zap"` as import path. (#292)

However the project description in Github (first line of text at the top) links to the github godoc (https://godoc.org/github.com/uber-go/zap) which in turn gives the installation instruction in the first line to import the package with the wrong path.

It would be nice if this could be clearer, possibly at least linking to https://godoc.org/go.uber.org/zap in the description.

**Comment by akshayjshah** [comment]
Thanks for letting me know - I neglected to update the Github UI to reflect the change. Done now!
