### ISSUE TITLE
Truncate file paths to $GOPATH

### ISSUE THREAD

**Issue by akshayjshah** [uber-go/zap#304]
When adding caller annotations, it's irritating to use the absolute path - the caller annotations become quite long. We should instead report the file's location with $GOPATH stripped off (which should leave files outside $GOPATH unchanged).

**Comment by skipor** [comment]
[go-stack have nice implementation of this ](https://github.com/go-stack/stack/blob/master/stack.go#L344) that can be used as starting point

**Comment by akshayjshah** [comment]
Closing in favor of #319.
