### ISSUE TITLE
Make caller formatting configurable

### ISSUE THREAD

**Issue by skipor** [uber-go/zap#319]
I have problem like #304, but I want truncate file paths to <parent_folder_name/file_name>. Because of really long  my app package path, even truncating to $GOPATH is not enough.
I know that in #201 decided that 
> Support for mutative external hooks has been deemed "not supported", and won't be coming back.

And, as result, there is no way no modify `Entry.Caller` via `Option`
So I found only way to do this: wrap `zapcore.Encoder`, and truncate `Entry.Caller.File` before calling wrapped `Encoder`. But that is really ugly way, and can't be used with beautiful `Config` helpers.

My best idea how to improve usability in this case is add kind of `EncodeCaller` into `EncoderConfig` and use it to encode `Caller`. Also, this is nice way to solve #304.

Other ways to improve usability:
- Add modifying hooks, that are called after `Core` check
  - Not best idea.
- Allow wrap `Encoder` easier.
  - Make `Config` methods exported to add ability for manual `Logger` build.

**Comment by akshayjshah** [comment]
Good point - I hadn't thought about making the caller formatting configurable, but it's a good idea. Since you have a PR open, I'll move discussion there.

**Comment by akshayjshah** [comment]
Fixed in #327.
