### ISSUE TITLE
Add a package with context utilities

### ISSUE THREAD

**Issue by skipor** [uber-go/zap#323]
In backend develop, it's common pattern to add request scope values to context via `context.WithValue`, and pass it further, to next handler, middleware, transport, dialer, etc.
Logger with request scope fields is such value. 

Usually, packages that have values that will be put in context, have helper functions to do that. `httptrace.WithClientTrace` and `httptrace.ContextClientTrace` are well known examples.
I think it would be nice to add `zapctx` package with such functions in zap to not to make backend developers make their own.

My concept of `zapctx` package.
```go
// Like zap.L, zap.S. Both non-nil after WithLogger or WithSugared
func L(ctx context.Context) *zap.Logger
func S(ctx context.Context) *zap.SugaredLogger

// Like httptrace.WithClientTrace and etc.
func WithLogger(ctx context.Context, l *zap.Logger) context.Context
func WithSugared(ctx context.Context, s *zap.SugaredLogger) context.Context
```

Possible optimisation: after `WithLogger`, `SugaredLogger` can be lazy allocated on demand.

**Comment by akshayjshah** [comment]
My experience is that most developers who want these APIs also want to add some specific request-scoped context to their loggers. If that's the case, these APIs aren't sufficient; they'll end up writing their own wrappers anyways.

Again, I'll leave this open - I'm willing to consider this in an upcoming point release, but for now I'd prefer to focus on issues critical to the 1.0 release.

**Comment by zet4** [comment]
I've been using [github.com/juju/zaputil/zapctx](https://godoc.org/github.com/juju/zaputil/zapctx) in last project before the breaking changes, would love to see API similar to that one.

**Comment by akshayjshah** [comment]
Closing this as part of an issues cleanup; we won't be introducing a package like this in zap. If there's a well-done third-party package that implements this functionality, I'm happy to direct users there.

**Comment by frankgreco** [comment]
For those looking for this functionality, it can easily be accomplished with a few lines of code. Find an example (https://github.com/northwesternmutual/kanali/blob/kanali.io/v2alpha1/pkg/logging/logger.go#L73-L84).

**Comment by Sauraus** [comment]
☝️ anyone have that code handy? the link broken 😞

**Comment by frankgreco** [comment]
https://github.com/northwesternmutual/kanali/blob/master/pkg/log/log.go

**Comment by yurishkuro** [comment]
Related #654

**Comment by yuseferi** [comment]
@Sauraus this could help you if you still need it .

 https://pkg.go.dev/github.com/yuseferi/zax
