### ISSUE TITLE
logrotate with new zap 1.x

### ISSUE THREAD

**Issue by ipfans** [uber-go/zap#342]
I want to use ```logrotate``` with zap and lumberjack. Now I using following code to init a SurgaredLogger:

```go
conf = zap.NewProductionConfig()
conf.EncoderConfig.EncodeTime = timeEncoder
z, err := conf.Build()
...
logger = z.Sugar()
...
```

As #229 said, I should implement the ```SyncWriter``` interface, but I can not find the way to set it into ```SugaredLogger```.

**Comment by skipor** [comment]
Sadly, at that moment it could be done only in very hacky way. 
I wish `zap.Config` methods to be exported, to do such things less complicated.
Current workaround:
```go 
func Foo() {
	var sw zapcore.WriteSyncer
	conf := zap.NewProductionConfig()
	z, err := conf.Build(SetOutput(sw, conf))
        // Or, if your already have sugared logger.
	sugar := z.Sugar()
	sugar = sugar.Desugar().WithOptions(SetOutput(sw, conf)).Sugar()
}

// SetOutput replaces existing Core with new, that writes to passed WriteSyncer.
func SetOutput(ws zapcore.WriteSyncer, conf zap.Config) zap.Option {
	var enc zapcore.Encoder
        // Copy paste from zap.Config.buildEncoder.
	switch conf.Encoding {
	case "json":
		enc = zapcore.NewJSONEncoder(conf.EncoderConfig)
	case "console":
		enc = zapcore.NewConsoleEncoder(conf.EncoderConfig)
	default:
		panic("unknown encoding")
	}
	return zap.WrapCore(func(zapcore.Core) zapcore.Core {
		return zapcore.NewCore(enc, ws, conf.Level)
	})
}
```

**Comment by akshayjshah** [comment]
For now, I'm unwilling to export the methods on the Config struct - I'm not ready to commit to API stability there.

In addition to repurposing the config struct as @skipor suggests, you can easily just build a logger yourself.

```go
logger := zap.New(zapcore.NewCore(
  zapcore.NewJSONEncoder(yourEncoderConfig),
  someRotatingWriter,
  zapcore.InfoLevel,
))
```

The bundled config struct is only intended for the most common use cases; there are too many ways to compose WriteSyncers, Encoders, and Cores to support all of them with declarative configuration.

**Comment by toefel18** [comment]
@ipfans I've written a log package that configures lumberjack and zap together: [zap-lumberjack.go](https://gist.github.com/toefel18/7f0b82127a4576d3a7d7b13d013b0f8b). Maybe it helps you.

**Comment by akshayjshah** [comment]
@toefel18 Cool, glad you're finding that the two packages work well together. Since there isn't a bug here and I don't plan to export more config methods (for now), I'm going to close this issue.

Don't hesitate to open further issues if you encounter problems.
