### ISSUE TITLE
Placing all fields into a single object

### ISSUE THREAD

**Issue by Southclaws** [uber-go/zap#351]
Question regarding encoding fields:

Our components conform to the following logging standard:

```
{
    "@message": "[2017-02-26T15:17:24+00:00] [REQUEST] [GET] /v1/test/health",
    "@timestamp": "2017-02-26T15:17:24.848Z",
    "@fields": {
        "ip": "::ffff:127.0.0.1",
        "query": {},
        "level": "info"
    }
}
```

Is there any way to make code like this:

```
qm.logger.Warn("something happened",
	zap.String("some_field", someData))
```

Output in our format?

I did wonder about using this:

```
qm.logger.Warn("something happened",
	zap.Object("@fields",
		(my fields)
	),
)
```
But not sure where to go from here, does this library support such usage?

**Comment by akshayjshah** [comment]
It certainly does! See the [`zap.Namespace`](https://godoc.org/go.uber.org/zap#Namespace) field.

As soon as you construct your root logger (probably in `main`), do this:

```
logger = logger.With(zap.Namespace("@fields"))
```

and all subsequent logs should work.

**Comment by akshayjshah** [comment]
Closing this issue; feel free to reopen if you're still running into trouble.

**Comment by xusss** [comment]
If more than one `zap.Namespace` in logger as the same level. Is there any way?
e.g.
```
{
    "@message": "[2017-02-26T15:17:24+00:00] [REQUEST] [GET] /v1/test/health",
    "@timestamp": "2017-02-26T15:17:24.848Z",
    "@fields1": {
        "ip": "::ffff:127.0.0.1",
        "query": {},
        "level": "info"
    },
    "@fields2": {
        "ip": "::ffff:127.0.0.1",
        "query": {},
        "level": "info"
    }
}
```

**Comment by Southclaws** [comment]
I don't think it's possible with namespaces since from what I can tell, setting a namespace implicitly makes all future fields go into that namespace and I don't see any way to specify a namespace on log calls.

You can however add an additional section using `With` when building, which I did in order to include a code version with every log line:

```go
	logger = _logger.With(
		zap.String("@version", os.Getenv("GIT_HASH")),
		zap.Namespace("@fields"),
	)
```

But if you want a separate field for individual log lines you could just use an object:

```go
			logger.Info("status",
				zap.Any("status", map[string]interface{}{
					"total_active_queues": len(qm.ActiveQueues),
					"total_buckets":       len(qm.api.buffer.taskBuckets),
					"awaiting_buffer":     len(qm.api.buffer.tasks),
					"awaiting_flush":      len(qm.api.buffer.readyBuckets),
					"awaiting_route":      len(qm.api.rm.input),
					"awaiting_ack":        len(qm.TasksToAck),
				}))
```

**Comment by xusss** [comment]
The `zap.Any` may be appropriately for me. Thanks a lot!

**Comment by akshayjshah** [comment]
Right now, each logger can have only one namespace (though they can be nested).

As @Southclaws points out, namespaces don't look like a good fit for your use case. `zap.Any` with a `map[string]interface{}` is a simple solution, but it's a bit slow. If you need something faster, implement `zapcore.ObjectMarshaler`:

```
type status struct {
  foo string
  bar int
}

func (s *status) MarshalLogObject(enc zapcore.ObjectEncoder) error {
  enc.AddString("foo", s.foo)
  enc.AddInt("bar", s.bar)
  return nil
}

func main() {
  log := zap.NewNop()
  log.Info("some status", zap.Object("status", &status{foo: "things", bar: 42}))
}
```

**Comment by xusss** [comment]
@akshayjshah Yes, the `zapcore.ObjectMarshaler` is more  performance. Thanks！

**Comment by JeanMertz** [comment]
This is an old question, but I wanted to extend it a bit and ask if it's possible what I want to do.

I'd like to have a custom marshaler that allows to easily _add_ key/value pairs to an existing object. So say I have (in JSON terms) `{ "labels": {} }`, I'd like to easily be able to add key/value pairs (strings only, but it doesn't really matter) to that `labels` object, without it overwriting any existing key/value pairs (unless of course, the key already exists).

Using this, I could have a logger using `With` to define a few labels, and then each specific log line being able to add its own labels, without overriding the ones added with `With`.

I also can't use `Namespace` here, since not all log attributes should be added to the `labels` object.

Is this possible to achieve?

**Comment by JeanMertz** [comment]
^ I solved this by [using a custom `zapcore.Core`](https://github.com/blendle/zapdriver/blob/af27c082ade7cf9f7c8cbb3cdcdf156795b41ff3/core.go#L100-L130) implementation that keeps state of the labels, and flushes them whenever a log gets printed. I am not sure if this is the right approach, but it seems to get the job done.
