### ISSUE TITLE
github.com/uber-go/zap  expects import "go.uber.org/zap"

### ISSUE THREAD

**Issue by AbijeetP** [uber-go/zap#352]
Getting the following error when running - `go get ./...`

```
log/logger.go:7:2: code in directory 
/home/abijeet/Programming/go/src/github.com/uber-go/zap 
expects import "go.uber.org/zap
```

My code is at - 

```
/home/abijeet/Programming/go/src/github.com/xxxx/xxx-xyz
```
My environment variables are the following - 
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/abijeet/Programming/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build140524652=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
```

**Comment by AbijeetP** [comment]
Please note that I've run the following command already - 

```
go get -u go.uber.org/zap
```
Find a file listing here,
```
abijeet@OSSLIN100:2014:19:$ ls -al /home/abijeet/Programming/go/src/go.uber.org/
total 16
drwxr-xr-x 4 abijeet abijeet 4096 Mar  7 20:32 .
drwxr-xr-x 6 abijeet abijeet 4096 Mar  7 20:32 ..
drwxr-xr-x 5 abijeet abijeet 4096 Mar  7 20:32 atomic
drwxr-xr-x 9 abijeet abijeet 4096 Mar  7 20:32 zap
```

**Comment by akshayjshah** [comment]
Hi @AbijeetP - the error message says it all 😄 

```
log/logger.go:7:2: code in directory 
/home/abijeet/Programming/go/src/github.com/uber-go/zap 
expects import "go.uber.org/zap
```

means that your code should reference this package with `import "go.uber.org/zap"`.

The *code* happens to be hosted on GitHub right now, but the *package* is in the `go.uber.org` namespace.

**Comment by AbijeetP** [comment]
Thanks @akshayjshah. I'm new to Go, and my interpretation of the error message was slightly different.

**Comment by akshayjshah** [comment]
No problem at all! Glad this sorted it out.

**Comment by Vish17agr** [comment]
What should be the correct way to write the command so that it works fine

**Comment by nonpcnpc** [comment]
_The code happens to be hosted on GitHub right now, but the package is in the go.uber.org namespace._

⬆ this is retarded

**Comment by prashantv** [comment]
Locking this thread, as the conversation above doesn't follow our [Code of Conduct](https://github.com/uber-go/zap/blob/master/CODE_OF_CONDUCT.md).
