### ISSUE TITLE
Different format per output

### ISSUE THREAD

**Issue by Civil** [uber-go/zap#361]
It's very useful to have separate encoders for different streams.

In current version you can specify multiple outputs, but they will use the same encoder (e.x. json).

Example usecase:
Send json to elasticsearch and have a "console" output in stderr for engineer to read in case of any failures.

**Comment by lomik** [comment]
https://godoc.org/go.uber.org/zap/zapcore#NewTee

**Comment by Civil** [comment]
Sorry, I've missed there is a "NewTee" feature.
