### ISSUE TITLE
Null pointer in jsonEncoder.EncodeEntry

### ISSUE THREAD

**Issue by sebastien-rosset** [uber-go/zap#378]
Until yesterday, I was able to use ZAP and the JsonEncoder without any problem, everything was working great.
I cleaned up my GOPATH environment, so as a side effect, a newer version of zap was downloaded (latest from master). With the new version, my program panics in zap/zapcore/json_encoder.go:310.

What is the recommended way to get a specific version of ZAP so I can try with version 1.0.0? Using gopkg.in does not work:

**go get gopkg.in/uber-go/zap.v1**
package gopkg.in/uber-go/zap.v1: code in directory /home/serosset/goroot/src/gopkg.in/uber-go/zap.v1 expects import "go.uber.org/zap"

... Panic: runtime error: invalid memory address or nil pointer dereference (PC=0x458AF8)

/usr/local/go/src/runtime/panic.go:489
  in gopanic
/usr/local/go/src/runtime/panic.go:63
  in panicmem
/usr/local/go/src/runtime/signal_unix.go:290
  in sigpanic
/home/serosset/goroot/src/go.uber.org/zap/zapcore/json_encoder.go:310
  in jsonEncoder.EncodeEntry
/home/serosset/goroot/src/go.uber.org/zap/zapcore/core.go:86
  in ioCore.Write
/home/serosset/goroot/src/go.uber.org/zap/zapcore/entry.go:203
  in CheckedEntry.Write
/home/serosset/goroot/src/go.uber.org/zap/logger.go:161
  in Logger.Info

**Comment by ansel1** [comment]
EncoderConfig has 4 properties, named Encode*

These are function pointers and cannot be nil.  They must be set to something.  The EncoderConfig constructor functions populate these fields with defaults.

**Comment by sebastien-rosset** [comment]
Thanks for the quick response, that works now. We were missing the EncodeCaller attribute. I'm not sure why it worked for weeks before the zap upgrade.

I still need to figure out what's the easiest way to go get a specific version of zap.

**Comment by ansel1** [comment]
EncodeCaller was just added, after rc3.

glide works, that's what we were using to pin versions, i.e. `version: v1.0.0-rc2`

**Comment by akshayjshah** [comment]
@ansel1 nailed it - this was added in the 1.0 release. All further releases will be backward-compatible, so you should pin to the 1.x major version (in glide, that's `^1`).

There are a bunch of tools for dependency management in Go; internally, we also use glide. The community is trying to build and polish [a single tool](https://github.com/golang/dep) and integrate it directly into the `go` tool.
