### ISSUE TITLE
runtime.CallersFrames is undefined

### ISSUE THREAD

**Issue by greenpau** [uber-go/zap#389]
Received the following error:

```
vendor/go.uber.org/zap/stacktrace.go:63: undefined: runtime.CallersFrames
```

The issue is with this line:

```
    frames := runtime.CallersFrames(programCounters.pcs)
```

Go version:

```
$ go version
go version go1.6.3 linux/amd64
$
```

**Comment by greenpau** [comment]
When I commented out the `runtime` code, I got the error I was looking for:

```
log.Infof undefined (type *zap.Logger has no field or method Infof)
```

**Comment by akshayjshah** [comment]
Hi @greenpau - thanks for including your Go version in the issue. 

Zap only supports the current stable Go release and one previous release; right now, that's 1.7 and 1.8. Since the CallersFrames API was added in 1.7, zap won't work properly on 1.6.

**Comment by akshayjshah** [comment]
Added a note about version support in the README (see #391).
