### ISSUE TITLE
Is zaptest.Buffer meant to be thread-safe?

### ISSUE THREAD

**Issue by yurishkuro** [uber-go/zap#399]
I have the following function used to create test logger in unit tests. When this logger was used in tests with multiple go-routines, `-race` detected a race condition (writes by different go-routines).

```go
// NewLogger creates a new zap.Logger backed by a zaptest.Buffer, which is also returned.
func NewLogger() (*zap.Logger, *Buffer) {
	encoder := zapcore.NewJSONEncoder(zapcore.EncoderConfig{
		MessageKey:     "msg",
		LevelKey:       "level",
		EncodeLevel:    zapcore.LowercaseLevelEncoder,
		EncodeTime:     zapcore.ISO8601TimeEncoder,
		EncodeDuration: zapcore.StringDurationEncoder,
	})
	buf := &Buffer{}
	logger := zap.New(
		zapcore.NewCore(encoder, buf, zapcore.DebugLevel),
	)
	return logger, buf
}
```

**Comment by akshayjshah** [comment]
It's not intended to be thread-safe; like an `*os.File`, it has to be locked before it's used concurrently in an application. You can do this pretty easily in the call to `zapcore.NewCore` by wrapping `buf` in `zapcore.Lock`.

**Comment by akshayjshah** [comment]
This should, of course, be reflected in the documentation :/
