### ISSUE TITLE
How to change zap logging to log to Stdout instead of Stderr?

### ISSUE THREAD

**Issue by nullbio** [uber-go/zap#400]
At the moment zap appears to log (zap.Info for example) to Stderr, how can I change it to log to os.Stdout? I tried log.SetOutput(os.Stdout) and it didn't seem to do the trick. I tried combing over the docs and the code, but I can't figure it out, I tried to use a syncwriter as well, but that didn't work either. Appreciate some guidance, thank you.

**Comment by akshayjshah** [comment]
`log.SetOutput` applies only to the standard library, and won't change any of zap's behavior. The easiest way to do this is with the `Config` struct:

```
cfg := zap.NewProductionConfig()
cfg.OutputPaths = []string{"stdout"}
logger, err := cfg.Build()
```
