### ISSUE TITLE
github.com/uber-go/zap expects import "go.uber.org/zap"

### ISSUE THREAD

**Issue by Papalloon** [uber-go/zap#401]
Same as #352 I'm not able to run my code.

I really don't understand the answer and I'm not able to run my go get -u -f ./... command.

What have I to do?

I'm really really new on go, I'm followinf this tutorial : http://www.vmkdaily.com/posts/how-to-guide-compiling-influxdb-on-windows

Thank you.

**Comment by akshayjshah** [comment]
Hey @Papalloon - this question is more appropriate for the InfluxDB project. They're using an older version of zap, which uses a different import path; if I remember correctly, they're also using their own dependency management system.

I keep meaning to open a PR to upgrade them to the latest zap, but haven't managed to free up a few hours to get it done.
