### ISSUE TITLE
Unsupported type when using zap.Reflect

### ISSUE THREAD

**Issue by tchap** [uber-go/zap#406]
Hi,

I tried passing `*http.Request` to Zap as `zap.Reflect("http_request", req)` and got

```
"http_requestError": "json: unsupported type: func() (io.ReadCloser, error)"
```

in console output.

Would it be possible to simply ignore fields that are not supported and try to print as much from the request as possible?

You might be also asking why I am passing the whole request to Zap. Well, I implemented a sink that is handling this particular key in a special way and I do need the request object. Although I could try to somehow serialize the request...

In any case, I would like to hear what the right solution is...

Cheers!

**Comment by akshayjshah** [comment]
Unfortunately, ignoring some fields isn't possible. Zap uses the standard library's `json` module for reflection-based JSON serialization, and the standard lib doesn't offer functionality like that for types from other packages.

However, you can achieve something very similar with a little extra work. Define a small wrapper type for `http.Request`, and have that type implement `zapcore.ObjectMarshaler`. That'll give you full control over how each field of the request is serialized, and it'll be quite a bit faster too.

**Comment by tchap** [comment]
@akshayjshah Thanks for the advice, makes sense :-)

**Comment by tchap** [comment]
Just for completion, here is my implementation: https://godoc.org/github.com/tchap/zapext/types#HTTPRequest

**Comment by mholt** [comment]
@akshayjshah @tchap Just wanted to _thank you both_ for describing how to do this and for following-up with your implementation. :) It was very helpful
