### ISSUE TITLE
Unable to change of log fields order

### ISSUE THREAD

**Issue by careermonk** [uber-go/zap#409]
**Sample Log:**

```{"level":"info","ts":"2017-04-18T08:07:14.374-0400","caller":"provisioner/subnet_watcher_test.go:36","msg":"Testing updateSubnet","crn":"test crn","field1":"data1"}```

**Expected output:**

```{"level":"info","ts":"2017-04-18T08:07:14.374-0400","caller":"provisioner/subnet_watcher_test.go:36","crn":"test crn","msg":"Testing updateSubnet","field1":"data1"}```

**Comment by careermonk** [comment]
Basically, not able to specify the order of fields while logging.

**Comment by careermonk** [comment]
If we have fields to logger.info, the order of message and fields were not in sequence.

**{"level":"info","ts":"2017-04-18T08:07:14.370-0400","caller":"test/softlayer_file_storage_mock.go:32","msg":"Created Mock Storage","crn":"crn:v1:CRN_CNAME:CRN_CTYPE:containers_kubernetes:CRN_REGION:CRN_INFRA_ID:storage_file:CRN_SERVICE_ID:log","podName":"","Size":20,"IOPS":4,"Location":""}**

**Comment by careermonk** [comment]
Order wanted for above is:

ts, level, crn, message, fields

**Comment by akshayjshah** [comment]
The order isn't configurable; that's a consequence of the low-level design that makes zap fast. Fields will *always* be level, timestamp, caller, message, user-defined context.

**Comment by careermonk** [comment]
If the message has objects they were not coming in sequence. In between other fields are coming.

**Comment by careermonk** [comment]
Is there a work around for this?

**Comment by akshayjshah** [comment]
Unfortunately, no - the order of the fields is fixed. All the common fields (level, timestamp, caller, and message) precede the user-defined context. The context you add to the logger (including crn) will appear in the order it was added.

**Comment by careermonk** [comment]
thanks @akshayjshah
