### ISSUE TITLE
Adding MarshalLogObject for zap.Config

### ISSUE THREAD

**Issue by jeffbean** [uber-go/zap#410]
In doing some introspection logs to log the logger configuration on setup, the `Config` doesn't have its own `MarshalLogObject` function. 

It would be nice to have its own zap.Object to log itself.

```
loggerConfig := zap.NewDevelopmentConfig()
logger, err := loggerConfig.Build()
if err != nil {
	return err
}
logger.Info("logger configured", zap.Object("config", loggerConfig))
```

**Comment by akshayjshah** [comment]
This is unlikely to be on the hot path, so letting `zap.Any` fall back to reflection is fine. Let's avoid introducing more code and tests unless the performance gain is worthwhile.
