### ISSUE TITLE
Ability to define line endings

### ISSUE THREAD

**Issue by alaczi** [uber-go/zap#412]
So I ran into a problem when I need to delivery logs to a Splunk Cloud instance.
The configuration of this Splunk instance is out of my reach, and by default it uses windows style line endings "\r\n" to separate each item. 
Current version of encoders have the line endings hardcoded to \n. My proposal is to allow configuring the line endings adding a LineSeparator string property the zapcore.EncoderConfig and using that to append in the encoders to the end of the generated log line.

**Comment by akshayjshah** [comment]
This is completely reasonable, and I'd love a PR that makes this change. Let's just make sure that we keep the zero value's behavior unchanged.

**Comment by alaczi** [comment]
@akshayjshah  thanks, created a PR for this change.
