### ISSUE TITLE
Support printing keys in Console Encoder 

### ISSUE THREAD

**Issue by ideahitme** [uber-go/zap#419]
In case I would like to have my logs structured without resorting to JSON format, it would be nice to have the keys visible. Currently there are only two options for encoder: `console` and `json`. If I understood correctly `console` encoder strips keys from the output, but it still would be nice to have this configurable. Another question would be if it is possible to support writing custom encoders ?

**Comment by ideahitme** [comment]
@akshayjshah thanks for reply :) 

Seems like I would need to write my own encoder, I would like to give it a try :) Closing this issue

**Comment by AkashKumar7902** [comment]
@ideahitme if you were successful in writing the encoder. Can you please share it here ? 
I am trying to write encoder to escape strings like : `\u001b[33mtest-set-0\u001b[0m` which evaluate to yellow colored `test-set-0`
