### ISSUE TITLE
how to log to file?

### ISSUE THREAD

**Issue by MonsieurHorse** [uber-go/zap#426]
this is an example, https://github.com/uber-go/zap/blob/747abfb0b3b130c9cf699e451f5aebfda379b5d1/example_test.go
but I can never imort NewJson method

what should I do?
thanks

**Comment by akshayjshah** [comment]
The easiest way to do this is to create a `zap.Config` struct, which allows you to configure the paths you'd like to use for logging output.

**Comment by MonsieurHorse** [comment]
thanks

**Comment by chmike** [comment]
You may also consider using using [funnel](https://github.com/agnivade/funnel).

**Comment by DevashishX** [comment]
[here](https://github.com/uber-go/zap/issues/294) is a better answer for Zap Logger output into a file
