### ISSUE TITLE
Why log to file not completed?

### ISSUE THREAD

**Issue by dgqypl** [uber-go/zap#427]
here is my code:
```
	cfg := zap.NewProductionConfig()
	cfg.OutputPaths = []string{"zapLog.log", }
	logger, _ := cfg.Build()

	defer logger.Sync()

	for i := 0; i < 200; i++ {
		logger.Info("hello world")
	}
```

in my mind, the file "zapLog.log" should have 200 lines,by the actual lines only 101:
![qq 20170505163548](https://cloud.githubusercontent.com/assets/25171658/25738662/ed9cc986-31b0-11e7-9d46-d8bbe487205f.png)

what cause that? Is it a bug ?

**Comment by momoneko** [comment]
It's not a bug. Zap seems to implement an I/O cap when multiple consecutive identical messages are logged. See this for details: https://github.com/uber-go/zap/blob/master/zapcore/sampler.go#L103

This logs all 200 lines. Note that every message logged is different:
```
	for i := 0; i < 200; i++ {
		logger.Info(fmt.Sprintf("hello world %d", i))
	}
```

**Comment by akshayjshah** [comment]
@momoneko is exactly right - the default production configuration samples your log output. You can disable this behavior by either (1) creating your own `zap.Config`, or (2) building your own logger with `zap.New` and `zapcore.NewCore`.
