### ISSUE TITLE
WriteSyncer as output.

### ISSUE THREAD

**Issue by MintyOwl** [uber-go/zap#428]
While browsing through the API, I noticed, WriteSyncer is only for errors and not output. Any idea how to use WriteSyncer as the output.

Thanks

**Comment by akshayjshah** [comment]
`WriteSyncer`s are also for output. To use your own `WriteSyncer` implementation, you need to construct a logger by hand:

```
core := zapcore.NewCore(
  zapcore.NewJSONEncoder(zapcore.NewProductionEncoderConfig()),
  yourWriteSyncerConstructor(),
  zapcore.InfoLevel,
)
logger := zap.New(core)
```

**Comment by MintyOwl** [comment]
Superb!
