### ISSUE TITLE
Unrecognized context pkg

### ISSUE THREAD

**Issue by Bunchhieng** [uber-go/zap#440]
![1](https://cloud.githubusercontent.com/assets/4691966/26708066/60cfde2c-4717-11e7-8933-fee504fccd13.JPG)

Is this a known issue?

**Comment by akshayjshah** [comment]
As far as I know, the buffalo web framework doesn't have anything to do with this package. You should [file this issue with buffalo](https://github.com/gobuffalo/buffalo/issues) instead.

**Comment by Bunchhieng** [comment]
My bad. I meant to post this issue on Buffalo repo.. Somehow it ended up here. Thanks
