### ISSUE TITLE
Lack of api to log to non-file target

### ISSUE THREAD

**Issue by xmxiaoq** [uber-go/zap#449]
**#450** 

What if our log targets are **NOT** named files, say io.Writer?
Unfortunately, there's no exported function to do this easily.
#
In old version, it's easy:
```go
var out io.Writer
logger := zap.New(
		zap.NewJSONEncoder(),
		zap.DebugLevel,
		zap.Output(zap.Tee(zap.AddSync(os.Stdout), zap.AddSync(out))),
	)
```

**Comment by akshayjshah** [comment]
Sorry for the long delay, @xmxiaoq - this is already possible with the exported APIs.

```
var out zapcore.WriteSyncer
// use zapcore.NewJSONEncoder, or implement your own encoder
var encoder zapcore.Encoder
core := zapcore.NewCore(
  encoder,
  zapcore.NewMultiWriteSyncer(out, os.Stdout),
  zapcore.DebugLevel,
)
logger := zap.New(core)
```

I'm very, very late writing good documentation for zap, so these APIs aren't super-obvious. Think of `zap.Config` as just one possible way to drive the `zapcore` APIs from configuration - there are many others that might be better for your use case. It's only a little code, so I expect that many users (especially in companies that need a standardized logging config format) to write their own configuration wrappers.
