### ISSUE TITLE
Stackdriver support proposal

### ISSUE THREAD

**Issue by piotrkowalczuk** [uber-go/zap#452]
Hi, 

[Stackdriver](https://cloud.google.com/stackdriver/) is part of google cloud infrastructure. It has [multiple differences](https://cloud.google.com/error-reporting/docs/formatting-error-messages) in compare to current `Production` configuration. 

# Reasoning

**stackdriver json payload**
```
{
  "eventTime": string,
  "serviceContext": {
    "service": string,     // Required.
    "version": string
  },
  "message": string,       // Required. Should contain the full exception
                           // message, including the stack trace.
  "context": {
    "httpRequest": {
      "method": string,
      "url": string,
      "userAgent": string,
      "referrer": string,
      "responseStatusCode": number,
      "remoteIp": string
    },
    "user": string,
    "reportLocation": {    // Required if no stack trace in 'message'.
      "filePath": string,
      "lineNumber": number,
      "functionName": string
    }
  }
}
```

Properties like `ts` or `level` are named and encoded differently, implementation using existing API would be straigthforward. `serviceContext` could be provided as a struct that implements `zapcore.ObjectMarshaler`. 

On the other hand `caller` and `logger` are represented by one object `reportLocation`. `msg` turns into `message` and should combine `msg`, `error` and `stacktrace` altogether. I can't see any way to solve this issue without breaking changes.

# Proposal

Potentially separate package (e.g. `zapstackdriver`)  could be introduced.

**config.go**
```go

// NewStackdriverEncoderConfig returns EncoderConfig that reflects Stackdriver requirements:
// LINK: https://cloud.google.com/error-reporting/docs/formatting-error-messages
func NewStackdriverEncoderConfig() zapcore.EncoderConfig {
	return zapcore.EncoderConfig{
		TimeKey:       "eventTime",
		LevelKey:      "level",
		NameKey:       "logger",
		CallerKey:     "caller",
		MessageKey:    "message",
		StacktraceKey: "stacktrace",
		LineEnding:    zapcore.DefaultLineEnding,
		EncodeLevel: func(l zapcore.Level, enc zapcore.PrimitiveArrayEncoder) {
			switch l {
			case zapcore.DebugLevel:
				enc.AppendString("DEBUG")
			case zapcore.InfoLevel:
				enc.AppendString("INFO")
			case zapcore.WarnLevel:
				enc.AppendString("WARNING")
			case zapcore.ErrorLevel:
				enc.AppendString("ERROR")
			case zapcore.DPanicLevel:
				enc.AppendString("CRITICAL")
			case zapcore.PanicLevel:
				enc.AppendString("ALERT")
			case zapcore.FatalLevel:
				enc.AppendString("EMERGENCY")
			}
		},
		EncodeTime:     zapcore.ISO8601TimeEncoder,
		EncodeDuration: zapcore.SecondsDurationEncoder,
		EncodeCaller:   zapcore.ShortCallerEncoder,
	}
}

// NewStackdriverConfig ...
func NewStackdriverConfig() Config {
	return Config{
		Level:       NewAtomicLevelAt(InfoLevel),
		Development: false,
		Sampling: &SamplingConfig{
			Initial:    100,
			Thereafter: 100,
		},
		Encoding:         "json",
		EncoderConfig:    NewStackdriverEncoderConfig(),
		OutputPaths:      []string{"stdout"},
		ErrorOutputPaths: []string{"stdout"},
	}
}
```
**logger.go**
```go
// NewStackdriver ...
func NewStackdriver(sc ServiceContext, options ...Option) (*Logger, error) {
	return NewStackdriverConfig().Build(append(options, Fields(Object("serviceContext", sc)))...)
}
```

**field.go**
```go
type ServiceContext struct {
	Service string `json:"service"`
	Version string `json:"version"`
}

func (sc ServiceContext) MarshalLogObject(enc zapcore.ObjectEncoder) error {
	if sc.Service == "" {
		return errors.New("service name is mandatory")
	}
	enc.AddObject("securityContext", sc)
	return nil
}
```

What would be your suggestion when it comes to `reportLocation` and `message` fields?

**Comment by akshayjshah** [comment]
Your timing is great. I'm not very familiar with Stackdriver right now, but I'm starting to use it a bit on some other projects. At some point in the next few months, we may prototype a complete zap-stackdriver integration.

For now, though, it sounds like you're on the right track. The stackdriver formatting requirements are strict enough that you may have better luck wrapping the existing `JSONEncoder` in a dedicated `StackdriverEncoder` type that lets you fix the `reportLocation` and `message` fields.

**Comment by piotrkowalczuk** [comment]
@akshayjshah im glad to hear that. I followed your suggestion and it works! 

Limitation I can see in such approach is that you can't sompose `context` step by step. In perfect world`context.httpRequest` and `context.user` could be filled in middleware. It is not possible at the moment. [Logger.With](https://godoc.org/go.uber.org/zap#Logger.With) encodes given input straight into byte stream.

**Comment by akshayjshah** [comment]
Glad to hear that it's working, even if it's not ideal. Hopefully I'll be able to comment more knowledgeably once I have some direct experience with Stackdriver.

**Comment by niels-s** [comment]
Hey @akshayjshah, just checking in to see if you gained some experience with StackDriver 😛 
We're using GCE quite extensively, if you would needed any help to implement it let me know.
Given some help I could start adding it myself since we're using zap for several project it would benefit us tremendously  😉

**Comment by tommy351** [comment]
Hi guys. We also use zap and Stackdriver a lot. I wrapped the built-in zap.Core and make it easier to add context to entry. You can check [tommy351/zap-stackdriver](https://github.com/tommy351/zap-stackdriver) for details.

**Comment by piotrkowalczuk** [comment]
FYI: LogEntry structure has changed quite a bit: https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry.

**Comment by akshayjshah** [comment]
We're no longer planning to use Stackdriver on GCP, so there's little realistic chance that I'm going to pursue this further. Any Stackdriver-zap integration should probably live in a separate package, since none of the zap maintainers will know enough about the Stackdriver APIs to maintain it.

I'm going to close this issue to avoid misleading future readers, but I'm definitely open to discussing any zap changes needed to support a third-party stackdriver integration.

**Comment by JeanMertz** [comment]
For those interested, we've built a small Zap-based Stackdriver library that handles most of the heavy lifting of getting Stackdriver-formatted logs:

https://github.com/blendle/zapdriver

It produces "[LogEntry v2](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry)" compatible logs to which @piotrkowalczuk pointed. It also includes some helper functions that produce the appropriate fields, such as `HTTP`, `SourceLocation`, `Label`, and `Operation`.

Feel free to take it for a spin and report any issues you find. I'm sure there is still some functionality missing, but it did get us going.

**Comment by akshayjshah** [comment]
Awesome! Can you open a PR to add your package to zap’s FAQ? I’d love to help send users your way.
