### ISSUE TITLE
BenchmarkAddingFields Zap.CheckSampled-4 vs Zap.Check-4

### ISSUE THREAD

**Issue by soulne4ny** [uber-go/zap#463]
Hi,

Running `BenchmarkAddingFields` multiple times I've noticed that on my machine [Zap.CheckSampled-4](/uber-go/zap/blob/02029bcd0250d31efd0f96eccdfc633cd67b71e3/benchmarks/scenario_bench_test.go#L498) is 5–7 times faster than [Zap.Check-4](/uber-go/zap/blob/02029bcd0250d31efd0f96eccdfc633cd67b71e3/benchmarks/scenario_bench_test.go#L487). When _Check_ takes 1633 ns/op (1000000), _CheckSampled_ is at 256 ns/op (5000000), when _Check_ takes 3840 ns/op (500000),  _CheckSampled_ is at 730 ns/op (2000000).

_Check_ and _CheckSampled_ are basically the same and the latter does a little more operations.
How could it be, that _CheckSampled_ is that much faster than _Check_?

```
$ go version
go version go1.8.3 darwin/amd64
```

**Comment by akshayjshah** [comment]
`CheckSampled` does much less work, since it's dropping many of the logs. The benchmark is there to validate that the overhead of sampling is worthwhile :)

**Comment by soulne4ny** [comment]
Got it!
By the way, how often do you use sampled logs in production?

**Comment by akshayjshah** [comment]
We sample logs in production by default. Otherwise, large batches of errors or warnings introduce lots of mutex contention (because they're all trying to write to the same file or network connection), which makes the problem even worse.
