### ISSUE TITLE
zap.Err breaks convention

### ISSUE THREAD

**Issue by pbnjay** [uber-go/zap#47]
All the other Field wrappers use the full type name, only zap.Err uses a shortened name.

**Comment by akshayjshah** [comment]
That's certainly true. Unfortunately, `Error` is already taken by the error logging level. Other libraries solve this by giving the level constants more verbose names (`InfoLevel`, `ErrorLevel`, etc.), but I found this approach a little nicer.

What would you suggest?

**Comment by pbnjay** [comment]
Yeah I'd argue for `ErrorLevel` et al as well, it's more descriptive for that value's context and probably used much less frequently. But I guess it's 6 of one and half-dozen of the other... Probably not worth breaking code on both sides.

**Comment by prashantv** [comment]
`Err` does seem a little abrupt compared to the other field names.

The level names shouldn't be used too often, mostly in the constructor as the default level. It doesn't seem too bad to have the levels be more verbose:
```go
zap.NewJSON(zap.Info, zap.Output(..))
```
vs
```go
zap.NewJSON(zap.InfoLevel, zap.Output(..))
```

I don't feel strongly about either approach though.

**Comment by akshayjshah** [comment]
Fair enough. I can get behind the `ErrorLevel`, `InfoLevel`, etc. change. I'll roll that into one of the upcoming refactorings.
