### ISSUE TITLE
Something about the log rotate

### ISSUE THREAD

**Issue by sunfaces** [uber-go/zap#474]
Hi all:
    I flush my logs to out.log at first, sometime later I  renmae out.log to out.log.1, and then create a new out.log, but zap still write the new logs to out.log.1 ,How can I write the new logs to the new out.log without restart the service.

**Comment by tsingson** [comment]
+1

i also seek for this.

**Comment by noxiouz** [comment]
> How can I write the new logs to the new out.log without restart the service.

You have to reopen the file. If you do
```bash
lsof -p <PID>
```
you may see that file is still open and probably marked as deleted.

**Comment by akshayjshah** [comment]
@noxiouz is correct. This isn't directly zap-related; it's how `os.Open` works.

If you're using `logrotate`, you can turn on `copytruncate` to avoid this problem (at the cost of *maybe* losing a handful of log statements).

**Comment by zplzpl** [comment]
If i want to use the KILL -USR1 command to gracefully reopen the log file, zap there is a safe way to reopen the log file?

**Comment by akshayjshah** [comment]
> If i want to use the KILL -USR1 command to gracefully reopen the log file, zap there is a safe way to reopen the log file?

You'll need to write a `zapcore.WriteSyncer` implementation that does this. You can trap whatever signal you'd like and reopen the file, and you can decide whether you want to block writes while you're doing that or buffer them in memory.

**Comment by danielbprice** [comment]
It would be amazingly helpful to expose this as a helper.  Or to post a blessed example.  This is a basic need for a lot of applications;  I would prefer not to use lumberjack (not ideologically, it's just that my users are used to `logrotate`).
