### ISSUE TITLE
runtime.Callers deprecated in 1.9

### ISSUE THREAD

**Issue by Southclaws** [uber-go/zap#492]
https://github.com/uber-go/zap/blob/e68420e36ce87d08dc24bb74bfc316a0a57c5f7b/stacktrace.go#L53

According to this: https://tip.golang.org/doc/go1.9#callersframes `runtime.CallersFrames` should be used instead running up to 1.9.

**Comment by akshayjshah** [comment]
Great point, @Southclaws! We've already updated to work with the preferred 1.9 APIs - the guidance is to use `runtime.CallersFrames` to look at the programs counters returned by `runtime.Callers`. If you look just a few lines below the code you've flagged, you'll see that zap does exactly that.
