### ISSUE TITLE
Console encoder order format

### ISSUE THREAD

**Issue by CGreenburg** [uber-go/zap#499]
Is there a way to change the order/format of of the console encoder? For example, swapping the order of time and level so that level is to the left of the time. 

If there isn't, this is a feature request for 2.0 (#388).

Another idea would be a custom format for the time so that development logger configs can specify an easier to read format when testing.

**Comment by akshayjshah** [comment]
Hey @CGreenburg - thanks for the suggestions! The field ordering isn't configurable today - I'll note that down in #388.

You can already change the time format - it's the `EncodeTime` field in `zapcore.EncoderConfig`. This is also exposed in the top-level zap `Config` object. The [basic configuration example](https://godoc.org/go.uber.org/zap#ex-package--BasicConfiguration) in the zap docs show how to configure the level formatting; it's very similar for time encoding. The human-readable option that ships with zap is `"iso8601"`.
