### ISSUE TITLE
a Fatal or Panic call should synchronize the logger before exiting/panicing

### ISSUE THREAD

**Issue by nhooyr** [uber-go/zap#500]
https://github.com/uber-go/zap/blob/3216c4c73e8ebbafff73c456dd27143f4a7c1f94/zapcore/entry.go#L227-L232

It doesn't look like the zap synchronizes the logger before panicing/exiting but it should.

**Comment by prashantv** [comment]
A little earlier in the code, the `Write` method calls `Write` on the cores:
```go
for i := range ce.cores {
	err = multierr.Append(err, ce.cores[i].Write(ce.Entry, fields))
}
```

When using the default IO core, the `Write` will call `Sync` for logs that will fatal/panic (this is from `ioCore.Write`:
```go
if ent.Level > ErrorLevel {
	// Since we may be crashing the program, sync the output. Ignore Sync
	// errors, pending a clean solution to issue #370.
	c.Sync()
}
```

Please let us know if you have a repro where `Sync` on the underlying `Writer` is not called when logging fatals or panics.
