### ISSUE TITLE
Dynamic logging verbosity

### ISSUE THREAD

**Issue by manojadinesh** [uber-go/zap#501]
Hi Team,
I am currently looking for a way to achieve the dynamic logging verbosity with zap logger.
Would somebody provide me point me to the right direction here.
--Dinesh

**Comment by akshayjshah** [comment]
See the [basic configuration example](https://godoc.org/go.uber.org/zap#ex-package--BasicConfiguration) in the GoDoc. Once you've unmarshaled your configuration into the `zap.Config` struct, you'll have access to `cfg.Level.SetLevel`. Using that method changes the logging level of all loggers created from that config.

**Comment by manojadinesh** [comment]
Thanks for the guidance, and it helps.
