### ISSUE TITLE
Support to log objects such as %v or %+v

### ISSUE THREAD

**Issue by leonj1** [uber-go/zap#505]
I did not find an example where one can log using these formats. Not sure if its possible with this lib.

**Comment by akshayjshah** [comment]
This is supported by all the `*SugaredLogger` formatted printing variants: `Infof`, `Debugf`, etc.

**Comment by albenik** [comment]
@leonj1 `log.Debug("Message", zap.Reflect(obj))`

**Comment by akshayjshah** [comment]
I think that this is resolved - there are a few different options, but if you're routinely doing this sort of thing you should be using the `SugaredLogger`.
