### ISSUE TITLE
Add Type() method to zapcore.Level to satisfy pflag's Value interface

### ISSUE THREAD

**Issue by micahhausler** [uber-go/zap#526]
The `zapcore.Level` (as of v1.7.1) satisfies the stdlib's [`flag.Value`](https://golang.org/pkg/flag/#Value) interface, so that [`zap.LevelFlag`](https://godoc.org/go.uber.org/zap#LevelFlag) can be used. 
```go
type Value interface {
        String() string
        Set(string) error
}
```

For lots of projects, the pflag library (by [spf13](https://github.com/spf13/pflag)) is used instead of the default flag lib. In order to have a pflag that takes a `zapcore.Level`, one addition `Type() string` method must be added to satisfy the [`Value` interface](https://godoc.org/github.com/spf13/pflag#Value) :
```go
type Value interface {
    String() string
    Set(string) error
    Type() string
}
```

I'd like to add a `Type() string` method to `zapcore.Level` to satisfy the `plfag.Value` interface.

**Comment by akshayjshah** [comment]
I'd prefer not to support this in zap itself - there are *lots* of CLI-building and flag-parsing libraries out there, and I don't want zap choosing among them. Instead, I'd encourage you to release a tiny library that wraps `Level` to satisfy the `pflag` interface.

If you do release that library, I'm happy to merge a PR that adds to zap's FAQ and directs `pflag` users to your project.
