### ISSUE TITLE
Errors with attached structured data

### ISSUE THREAD

**Issue by skipor** [uber-go/zap#529]
Have a complex `http.Hanlder`, with logging request errors in one place. 
[github.com/pkg/errors](https://godoc.org/github.com/pkg/errors) is used to wrap error, to attach stacktrace, and its `Wrapf` or `Errorf` constructors, to attach information to be logged.
It's looks like something like:
```go
func (h *Handler) ServeHTTP(rw http.ResponseWriter, req *http.Request) {
	var res *http.Response
	res, err := h.veryComplexMiddlewareStack.Serve(req)
	if err != nil {
		zap.L().Error("Request fail", zap.Error(err), zap.Stringer("url", req.URL))
		res = h.errorResponse(err)
	}
	h.writeResponse(res)
}

func doSmthDeepInMiddlewareStack(key string, data []byte) error {
	err := somepkg.DoSmth(key, data)
	if err != nil {
		return errors.Wrapf(err, "'DoSmth' failed with key: %s; data: %s; ", key, data)
	}
	return nil
}
```
**Problem** 
information attached to error as text, and logged unstructured.

**Proposal** (Raw, and should be discussed)
1.
in `zapcore` add 
```go
type RichError interface {
      Unwrap() (short error, info ObjectMarhaller)
     // maybe MarhalLogObjectKey(string, ObjectMarshaler) instead?
}

func encodeError(key string, err error, enc zapcore.ObjectEncoder) error {
	if richErr, ok := err.(RichError); ok {
		err, info := richErr.Unwrap()
		encodeError(key, err, enc) // FIXME: handle error
		return info.MashalLogObject(enc)
	}
        // Current logic bellow.
	... 
}
       
```

2.
Add as zap subpackage, package with `error` wrappers and constructors, with API similar to `github.com/pkg/errors`, but with  `filelds ... zapcore.Field` last argument in constructors to be attached to error. Let package name be `zaperr` (to be discussed).

`zaperr` errors with fields (consider stack be field too) attached should implement `zapcore.RichError`.

Add `zaperr.Encoder` global, configurable `zapcore.Encoder` that used to get `string` for `Error` methods of `zaperr` error types.

**Comment by akshayjshah** [comment]
I'd prefer to avoid more special-casing for third-party error packages, and I *definitely* don't want to include yet another rich errors package as part of zap - it's way out of scope for this project.

*However*, I completely understand I think you can achieve these goals without these additions - you can introduce an `errors` package in your own application that includes the sort of wrapping functionality you've described. If you make your custom error struct implement `zapcore.ObjectMarshaler`, you can always log them with `zap.Any` - it'll use the standard error field for regular errors, and it'll use the `MarshalLogObject` implementation for your special errors. This doesn't allocate, since errors are already an interface - passing them as `interface{}` is nearly free.

**Comment by skipor** [comment]
> I definitely don't want to include yet another rich errors package as part of zap - it's way out of scope for this project.

Ok, I understand.

> make your custom error struct implement `zapcore.ObjectMarshaler`, you can always log them with the `zap.Any`

That requires code changes. I really don't like that option.

Maybe, such complex logic should be implemented via wrapping `zapcore.Core`.
[Here](https://github.com/yandex/pandora/blob/9098adc45ebae1353709538c5561da5fbb5b4495/lib/zaputil/stack_extact_core.go) I implement logging stacktrace from [github.com/pkg/errors](https://github.com/pkg/errors) error as `zapcore.Entry.Stack`.

The approach seems good enough but such wrapping `zapcore.Core` breaks sampling logic of nested `Core`s, because you can't call `Check(ent Entry, ce *CheckedEntry)` of the nested `Core` because it's call adds nested to `CheckedEntry.cores` but `Core.Write`will call nested `Core` `Write` in such case, but `Write` of the wrapper. 

Any ideas, how to fix sampling?

**Comment by skipor** [comment]
Okay, maybe it's ok to error `zap.Any`, but we would like to log it not as an object, but as few fields, without nested namespace.
Will you accept special handling for something like:
```go
type StructuredObject interface {
	Unwrap(key string) []zapcore.Field
}
```
?

**Comment by akshayjshah** [comment]
No, I'm pretty firm on this - I *really* don't want more API surface area to support structured data on errors. Writing a wrapper around cores is a good way for you to implement this in your own project, though.

Wrapping sampled cores is tricky, as you've pointed out. If you're using this internally, I'd apply your wrapper before the sampling logic - you can do this either by using `zap.New` directly or by constructin a non-sampling logger from config and applying both your wrapper and the sampling wrapper with the [`zap.WrapCore`](https://godoc.org/go.uber.org/zap#WrapCore) logger option.

**Comment by hori-ryota** [comment]
I implemented error wrapper for zap. How about this?
https://github.com/hori-ryota/zaperr
