### ISSUE TITLE
Recommended way to print request UUID with every log line

### ISSUE THREAD

**Issue by frankietaylor** [uber-go/zap#532]
Wanted to check what is the recommended way to print request UUID with every log statement. In java (logback), we generally store it in MDC.

**Comment by akshayjshah** [comment]
I'd suggest writing a field constructor that takes the request's `context.Context` and includes any relevant request-scoped in the log. Internally, we use Jaeger for tracing, so we [added a `Trace` function](https://godoc.org/github.com/uber/jaeger-client-go/log/zap#Trace) there. Wherever you're logging on the request path, include `Trace(ctx)` as one of the log fields.
