### ISSUE TITLE
Build fails with use of internal package not allowed - conflicts with multiple repository names

### ISSUE THREAD

**Issue by jacobgreenleaf** [uber-go/zap#535]
Because zap can be imported both as `go.uber.org/zap` and `github.com/uber-go/zap`, the users of the latter can not build due to some places where `/internal` is used:

```
jacobg-C02RC3QCG8WM:onix jacobgreenleaf$ make
  GO BUILD (1.9.2 darwin/amd64)    onix
.tmp/.goroot/src/code.uber.internal/rt/onix/vendor/github.com/uber-go/zap/stacktrace.go:28:2: use of internal package not allowed
make: *** [onix] Error 1
```

I'm not sure if the right solution is to avoid using `internal/` or just punt the issue to clients, however I am opening this ticket so that others know to use `go.uber.org/zap` import form only.

**Comment by jacobgreenleaf** [comment]
Addressed in the FAQ: "Your code shouldn't contain any references to github.com/uber-go/zap."

**Comment by tobya** [comment]
A useful [link to the FAQ page](https://github.com/uber-go/zap/blob/master/FAQ.md)
