### ISSUE TITLE
Zap Logger from Context

### ISSUE THREAD

**Issue by domgreen** [uber-go/zap#539]
I would like to be able to add and retrieve a logger from the context and therefore not have to pass a logger through all function calls but get it off the context when it is needed. Most of the time a logger and its attached fields are request scoped so feels like it fits in well being stored on the context.
Methods for doing this would look something like:
```
func Extract(ctx context.Context) *Logger

func ToContext(ctx context.Context, logger *Logger)
```
We currently have an implementation that does this for our gRPC middleware projects that can be seen here:

https://github.com/grpc-ecosystem/go-grpc-middleware/blob/master/tags/zap/context.go

This allows our interceptors to attach a entry onto the context and use all the fields for the duration of the calls.

**Comment by frankgreco** [comment]
@domgreen I also had a need for this and ended up writing a few lines of code to take care of it. You can find them [here](https://github.com/northwesternmutual/kanali/blob/kanali.io/v2alpha1/pkg/logging/logger.go#L73-L84).

**Comment by akshayjshah** [comment]
We explored variants of these APIs in #323. In general, I don't think that the situation has changed much - implementing the `Extract` and `ToContext` functions you've proposed is just a few lines of code, and I'd prefer to keep that functionality out of zap.

Frank, you may want to leave a comment on #323 with the same code you've linked here - for anyone else who shares your opinions on logger config, it's a nice implementation of these APIs.

**Comment by yuseferi** [comment]
I think [Zax](https://github.com/yuseferi/zax) would help you.

sample:
```GO
func main() {
    logger, _ := zap.NewProduction()
    ctx := context.Background()
    s := NewServiceA(logger)
    ctx = zax.Set(ctx, logger, []zap.Field{zap.String("trace_id", "my-trace-id")})
    s.funcA(ctx)
}

type ServiceA struct {
logger *zap.Logger
}

func NewServiceA(logger *zap.Logger) *ServiceA {
    return &ServiceA{
        logger: logger,
    }
}

func (s *ServiceA) funcA(ctx context.Context) {
    s.logger.Info("func A") // it does not contain trace_id, you need to add it manually
    zax.Get(ctx).Info("func A") // it will logged with "trace_id" = "my-trace-id"
}
```
