### ISSUE TITLE
when should I call sync func?

### ISSUE THREAD

**Issue by hankji** [uber-go/zap#540]
I make a public func like this:

> 

`var glogger *zap.Logger`
`...`
`func WithFields(msg string, fields ...zapcore.Field) {`
`// defer gloggerlogic.Sync()`
`	fields = append(fields, zap.String("deploy", DEPLOY))`
`	fields = append(fields, zap.String("host", hn))`
`	glogger.Info(msg, fields...)`
`}`
sync() is commented or not ,it seem to work fine. 

Sync is must be call? or when call it is better?
thank u

**Comment by akshayjshah** [comment]
You should call `Sync` before the process exits. Depending on the logger configuration you're using, it may or may not be required - if the `zapcore.Core` implementation you're using buffers, you have to call `Sync` to flush the buffer before exiting.

**Comment by hankji** [comment]
thank you very much.
