### ISSUE TITLE
Mock Logger for testing log output

### ISSUE THREAD

**Issue by HJFinch** [uber-go/zap#541]
Have you thought about adding a mock logger to be used in tests
For now we are setting our loggers to NoOp when running tests but it would be cool to have a logger that allows to verify if log messages contain the values as expected.

As an example I would call
```
c.log.Info("running function", zap.String("path", path))
```
and now I want to verify if the logger received a new entry with message("running function") and fields[{key: "path", value: "test")}].
One thing i could imagine for this would be either listening on a Pipe or some channel...

Or how do you test logging internally?

**Comment by prashantv** [comment]
There's an existing package that lets you do this:
https://godoc.org/go.uber.org/zap/zaptest/observer

It lets you access all logs, and filter on them to ensure something was or wasn't logged.

This is used throughout zap for testing internally, as well as in other packages that use zap.
