### ISSUE TITLE
Viper support

### ISSUE THREAD

**Issue by srikrsna** [uber-go/zap#542]
Hi.

Zap is fantastic for logging, so is Viper for configuration.

Zap's `Config` struct can be used to configure Zap. This can be loaded from Viper if the config struct had ``mapstructure:"path_map"`` tags.

Please add these tags. I can also send a PR for this.

**Comment by djui** [comment]
I would appreciate if Zap as a library stays dependency-minimal. Adding the tags would not require a new dependency, but likely it should be tested and thus would include Viper. 

Is there no other way to construct a Config with individual viper tags and then pass this config to Zap?

**Comment by glibsm** [comment]
No comment on the tags, I will defer that to active maintainers.

> but likely it should be tested and thus would include Viper

If only for testing, importing Viper (or any other package) from test packages would not affect production code importing Zap. Zap already is tested and benchmarked by importing other libraries.

See the `testImport:` section of the `glide.yaml`: https://github.com/uber-go/zap/blob/master/glide.yaml#L8

**Comment by ash2k** [comment]
A user could copy the `Config` struct into their code, add annotations, use Viper to load data into it and then just cast copied type into zap's type. Types that differ only in annotations can be cast into each other. Try it. That way no changes are needed, no testing is needed and any config-loading library can be used.

**Comment by svetomir** [comment]
@ash2k Can you please write short example?

**Comment by ash2k** [comment]
@svetomir something like this https://play.golang.org/p/pa-Peh5qHCz

**Comment by akshayjshah** [comment]
Testing against viper wouldn't require users of zap to take on new dependencies, but it's still not something I'm comfortable with.

There are a whole bunch of more full-featured flag-parsing libraries out in the world, and there's no way for us to support all of them - we don't use any of these libraries ourselves, so we can't effectively debug, modify, and support integration code going forward. @ash2k has already suggested exactly what I'd do if I really needed all of zap's configuration options.

If you're using zap to build applications, I'd go even further - I'd define a much smaller struct that only exposes the options you intend to use, add the tags viper requires, and copy from that struct into a full `zap.Config`.
