### ISSUE TITLE
How to build package using zap in debug and release mode

### ISSUE THREAD

**Issue by jay11ca39** [uber-go/zap#543]
I am using Zap package, in my package.

I want to build my package in:
   (i) **release mode [disable zap logger]** 
   (ii) **debug mode [enable zap logger]**

Is there is any way to do this?
    
**System information:**
Ubuntu 14.04 [64-bit]
arch : x86_64 [64-bit]

Command used for building: go build 
   (i) **release mode [disable zap logger]** 
   (ii) **debug mode [enable zap logger]**

Is there is any way to do this?
    
**System information:**
Ubuntu 14.04 [64-bit]
arch : x86_64 [64-bit]

Command used for building: go build

**Comment by srikrsna** [comment]
I don't know about go build but we use [Viper](https://github.com/spf13/viper) to configure our apps and custom packages. Using the global shared instance we let the main package decide what configuration of **Zap** to be used with the help of `zap.ReplaceGlobals()` and any package imported then can use `zap.L()` global level logger to log messages.

**Comment by billf** [comment]
https://godoc.org/go.uber.org/zap#NewNop returns a logger that will never write logs.

As mentioned above, you can use [zap.ReplaceGlobals](https://godoc.org/go.uber.org/zap#ReplaceGlobals) as demonstrated in https://godoc.org/go.uber.org/zap#example-ReplaceGlobals to replace the global logger. This could be convenient if the logger behavior is conditional on a runtime flag.

If you're not using the global logger, use the [*zap.Logger](https://godoc.org/go.uber.org/zap#Logger) provided by [zap.NewNop](https://godoc.org/go.uber.org/zap#NewNop) wherever your current logger is used. This could be used to make the `*zap.Logger` returned conditional on a build tag.

https://dave.cheney.net/2014/09/28/using-build-to-switch-between-debug-and-release describes a method of making code conditional on build tags.

**Comment by jay11ca39** [comment]
@srikrsna  and @billf , 
Sorry for late reply. :)
Thanks for your help..
