### ISSUE TITLE
Make callerSkipOffset in logger.Check configurable

### ISSUE THREAD

**Issue by pcaneill** [uber-go/zap#544]
I already have a log library that is used inside my modules and would like to use zap instead.

In order to have the smoothest migration I want to still use my old log api but forward the calls to a zap logger.

This works well expect for the filepath/linenumber which are not the real caller of the log function

I propose to make callerSkipOffset (https://github.com/uber-go/zap/blob/de8aa9e8396ccd3e2c734089fe010747f74d60ce/logger.go#L259) a logger option.

I can make the PR, if you are interested by the feature.

**Comment by prashantv** [comment]
You can create the logger to configure this already:
https://godoc.org/go.uber.org/zap#AddCallerSkip

If you look at where `callerSkipOffset` is used, it's added to caller skip specified in the logger which can be customized by the above option.
