### ISSUE TITLE
Tag/Release latest commit with new version

### ISSUE THREAD

**Issue by djui** [uber-go/zap#545]
@akshayjshah Could you make a release for the latest commit, maybe `v1.8`? Given the latest commit is over two months ago, I could argue that this commit is rather stable.
We rely on https://github.com/uber-go/zap/commit/54bf686453bd64588ccdc1c8a8e1f175f6d40f03 And would like to go back to Go dep’s semver support instead of using a specific revision.

**Comment by akshayjshah** [comment]
Doing this today - apologies for the long, long delay. I've been a bit consumed with internal work :/
