### ISSUE TITLE
Is that possible to hide some information when print log

### ISSUE THREAD

**Issue by liu1700** [uber-go/zap#547]
the standard output of each log is something like this：
2018-01-09T15:30:54.454+0800	INFO	config/config.go:47	HelloHere
2018-01-09T15:31:54.454+0800	INFO	config/config.go:48	HelloThere

Is that possible to make it print like this：
HelloHere
HelloThere

Print content only

**Comment by billf** [comment]
[zapcore.EncoderConfig](https://godoc.org/go.uber.org/zap/zapcore#EncoderConfig) determines which keys (such as time, level, and caller) are written per-entry. 

See https://godoc.org/go.uber.org/zap#ex-package--BasicConfiguration on using a configuration-driven declarative way of specifying [zapcore.EncoderConfig](https://godoc.org/go.uber.org/zap/zapcore#EncoderConfig). https://godoc.org/go.uber.org/zap#Config documents the format.

See https://godoc.org/go.uber.org/zap#ex-package--AdvancedConfiguration for details on constructing a [zapcore.EncoderConfig](https://godoc.org/go.uber.org/zap/zapcore#EncoderConfig) and combining that with [zapcore.NewConsoleEncoder](https://godoc.org/go.uber.org/zap/zapcore#NewConsoleEncoder), [zapcore.Encoder](https://godoc.org/go.uber.org/zap/zapcore#Encoder), and [zapcore.NewCore](https://godoc.org/go.uber.org/zap/zapcore#NewCore) to construct a logger with your preferred encoding.

**Comment by liu1700** [comment]
Thanks a lot! I should read the documents carefully
