### ISSUE TITLE
zaptest.ShortWriter documentation is unclear

### ISSUE THREAD

**Issue by danielbprice** [uber-go/zap#551]
The documentation for zaptest.ShortWriter states:

"ShortWriter is a WriteSyncer whose write method never fails, but nevertheless fails to the last byte of the input."

Is there a missing verb?  From the implementation it looks like the intent was "fails to write the last byte".  Perhaps the text could be clarified to something like:

```ShortWriter is a WriteSyncer whose write method never fails.  It discards the input b (similar to Discarder) and reports that it wrote len(b) - 1 bytes (i.e. a "short" write).```

... even with this clarification I couldn't really work out why I might want this 😐

**Comment by akshayjshah** [comment]
You probably don't want this; it's only useful when trying to simulate a variety of error conditions for code that accepts an `io.Writer`.

I'm happy to merge a PR that rewords the docs to be clearer :)
