### ISSUE TITLE
cannot import zap via go dep (https://golang.github.io/dep)

### ISSUE THREAD

**Issue by nayakravi** [uber-go/zap#552]
The error message is: 
"ensure Solve(): No versions of github.com/uber-go/zap met constraints:
	v1.7.1: Could not introduce github.com/uber-go/zap@v1.7.1, as its subpackage github.com/uber-go/zap does not contain usable Go code (*pkgtree.NonCanonicalImportRoot).. (Package is required by (root).)"

The possible cause is logged here: https://github.com/golang/dep/issues/899
There may be relative paths in your import statements. Any chance you can make zap go dep compliant?

**Comment by dstrop** [comment]
try `dep ensure -add go.uber.org/zap`

**Comment by Tri125** [comment]
I've had the same issue and I can confirm that setting the constraint ``name`` to ``go.uber.org/zap`` solved it.

**Comment by nayakravi** [comment]
Thank you @dstrop - that worked! I'm closing this issue.
