### ISSUE TITLE
Ability to have custom sinks

### ISSUE THREAD

**Issue by dimroc** [uber-go/zap#553]
Hi all,
We need finer grained control of our console output. This led me to do some investigation around `OutputPaths` and `Open` in `writer.go`:

https://github.com/uber-go/zap/blob/master/writer.go#L60

```golang
	for _, path := range paths {
		switch path {
		case "stdout":
			writers = append(writers, os.Stdout)
			// Don't close standard out.
			continue
		case "stderr":
                        ...
```

After perusing some other PRs and issues, I noticed that there's growing consensus around the need for "syslog", which ended up with this draft adding `case "syslog"` to the switch statement.

https://github.com/uber-go/zap/pull/506/files#diff-dc03dbc53655fac7a4c8d16b1b4144c1R70

Rather than adding string after string in the case statement, we could introduce an interface that returns an `zapcore.WriteSyncer` and a `close` method. That way we could register new sinks like syslog or my customized `Stdout`, and not increase the number of special cases.

Quick outside-in proposal:

```golang
func (cfg Config) BuildWithSinkFactories(sinkMakers map[string]SinkFactory, opts ...Option) (*Logger, error) {
   ...
}

func (cfg Config) Build(opts ...Option) (*Logger, error) {
    BuildWithSinkFactories(DefaultSinkFactories, opts)
}

...

func Open(sinkMakers map[string]SinkFactory, ...) {
        sinks := make([]Sink, 0, len(paths))
	for _, path := range paths {
            factory, ok := sinkMakers[path]
            if ok {
                // sink{writer, closer}
                sinks = append(writers, sink)
            }
            ...
```

Any other ideas or approaches around this would be great.

---

There could be a discussion around me finding a place outside of zap to customize my stdout, but for this issue, I would like to focus on the viability of customizing sinks in `writer.go` or extending zap.

**Comment by etsangsplk** [comment]
@akshayjshah or other reviewers
What is the status on this? And on the associated PR?

**Comment by akshayjshah** [comment]
landed, cutting a release shortly. Sorry for the long delay!
