### ISSUE TITLE
How to chane runtime log level 

### ISSUE THREAD

**Issue by juesexingqiu** [uber-go/zap#556]
The code is as below

w := zapcore.AddSync(&lumberjack.Logger{
  Filename:   "/var/log/myapp/foo.log",
  MaxSize:    500, // megabytes
  MaxBackups: 3,
  MaxAge:     28, // days
})
core := zapcore.NewCore(
  zapcore.NewJSONEncoder(zap.NewProductionEncoderConfig()),
  w,
  zap.InfoLevel,
)
logger := zap.New(core)

As code shows, the default log level is Info, so how to change runtime log level to print Debug level log

**Comment by akshayjshah** [comment]
To change the log level dynamically, you'll have to use a `zap.AtomicLevel` instead of the plain `zap.InfoLevel`. There are usage examples in [the package docs](https://godoc.org/go.uber.org/zap#AtomicLevel).

Of course, you can also supply your own implementation of `zap.LevelEnabler`.
