### ISSUE TITLE
Change library url

### ISSUE THREAD

**Issue by snovichkov** [uber-go/zap#559]
Hello, please change library url from go.uber.org/zap to github.com/uber-go/zap, because usually go.uber.org host is unavailable and it's broke all pipelines. For example, right now :

```
> dep ensure -v
The following issues were found in Gopkg.toml:

  ✗ unable to deduce repository and source type for "go.uber.org/zap": unable to read metadata: unable to fetch raw metadata: failed HTTP request to URL "http://go.uber.org/zap?go-get=1": Get http://go.uber.org/zap?go-get=1: dal tcp: lookup go.uber.org on 10.0.4.251:53: no such host

ProjectRoot name validation failed
```

**Comment by akshayjshah** [comment]
Sorry for the outage - we had an issue with our DNS setup last night. In general, `go.uber.org` is up and roughly as available as Github.

We're not going to change the package import path, since it's a large breaking change.
