### ISSUE TITLE
Output to the console of Jetbrains IDEA, text color exception

### ISSUE THREAD

**Issue by dxvgef** [uber-go/zap#560]
Zap output log to Jetbrains IDEA Run panel, IDEA is identified as an error message, all log text is red, but in VS Code console, everything is normal.

```Go
package main

import (
	"go.uber.org/zap"
)

func main() {
	logger, _ := zap.NewProduction()
	logger.Debug("debug")
	logger.Info("info")
	logger.Warn("warn")
	logger.Error("error")
}
```

![image](https://user-images.githubusercontent.com/5192264/37045264-7eecc8a2-21a0-11e8-9849-111035ae55b6.png)

**Comment by akshayjshah** [comment]
I'm not sure what zap can do about this - it's writing out perfectly valid JSON, so this sounds like a Jetbrains configuration issue.

**Comment by dxvgef** [comment]
@akshayjshah I reset all settings for Jetbrains IDEA and only enabled the Go plugin, the problem persists.

**Comment by akshayjshah** [comment]
@dxvgef Unfortunately, there's nothing we can do about this from zap. Zap is logging valid JSON; if that's causing problems in JetBrains IDEs, you'll have to file a ticket with them.

I'm sorry, this is just outside the control of zap.

**Comment by prashantv** [comment]
This is likely because the `NewProductionConfig` writes out logs to `stderr`:
https://github.com/uber-go/zap/blob/master/config.go#L124

I'm guessing the the IDE is showing output to `stderr` in red. If you change the output to go to `stdout` instead, it should stop being displayed in red.
