### ISSUE TITLE
Bump version to 1.8

### ISSUE THREAD

**Issue by djui** [uber-go/zap#561]
Please consider bumping to a new minor version, including the latest changes to the API such as https://github.com/uber-go/zap/commit/54bf686453bd64588ccdc1c8a8e1f175f6d40f03

I think it's a good time to do so, as the activity seems to have ebbed for a few months now, so the expectations on seeing a stable version are given.

**Comment by akshayjshah** [comment]
Doing it today - sorry for the long, long delay!
