### ISSUE TITLE
Flush manually

### ISSUE THREAD

**Issue by bharathramh92** [uber-go/zap#562]
From what I see in the document, all the logs will get flushed when Fatal or Panic happens. But, is there a way to flush all the logs manually?

**Comment by rhymes** [comment]
@bharathramh92 that's what logger.Sync() does: https://godoc.org/go.uber.org/zap#Logger.Sync

**Comment by bharathramh92** [comment]
Thank you so much. I was checking in FAQ and not in readme. Sorry for that. Closing this issue.
