### ISSUE TITLE
log.Panic should not be executed when logger is set to the Fatal level

### ISSUE THREAD

**Issue by pmzajaczkowski** [uber-go/zap#564]
As a user I expect that when I have a logger set to the highest level (fatal) then calling log.panic does nothing. Currently it does not log a message (that's OK) but panics either way (that's not OK).

```go
func main() {
	config := zap.Config{
		Level:             zap.NewAtomicLevelAt(zapcore.Level(zapcore.FatalLevel)), // FATAL level
		Encoding:          "json",
		OutputPaths:       []string{"stdout"},
		ErrorOutputPaths:  []string{"stdout"},
		InitialFields:     map[string]interface{}{},
		DisableStacktrace: false,
		DisableCaller:     false,
		EncoderConfig: zapcore.EncoderConfig{
			CallerKey:      "caller",
			LevelKey:       "level",
			LineEnding:     "\n",
			MessageKey:     "message",
			NameKey:        "logger",
			StacktraceKey:  "stacktrace",
			TimeKey:        "timestamp",
			EncodeLevel:    zapcore.CapitalLevelEncoder,
			EncodeCaller:   zapcore.ShortCallerEncoder,
			EncodeName:     zapcore.FullNameEncoder,
			EncodeDuration: zapcore.NanosDurationEncoder,
			EncodeTime:     zapcore.ISO8601TimeEncoder,
		},
	}
	logger, _ := config.Build()
	defer logger.Sync()
	sugar := logger.Sugar()
	sugar.Error("Some error - it should not appear") // OK, message not appears
	sugar.Panic("Some severe error - it should not appear") // OK, message not appears but panics :(
}
```

**Comment by akshayjshah** [comment]
I can definitely see why you'd expect this behavior. We considered this, but ended up choosing to always panic to keep control flow predictable.

Imagine the alternative, where `log.Panic` doesn't always panic. In that case, any code calling `log.Panic` needs to be prepared to continue execution, which defeats the point of using `panic` in the first place. This is really awkward - in practice, I suspect you'd end up following every call to `log.Panic` with a plain `panic`.

This is documented on [`Logger.Panic`](https://godoc.org/go.uber.org/zap#Logger.Panic), but perhaps this warrants an entry in the [FAQ](https://github.com/uber-go/zap/blob/master/FAQ.md). If you'd like to open a PR to add a FAQ, I'm happy to merge it!
