### ISSUE TITLE
Log level field as int

### ISSUE THREAD

**Issue by wujiang** [uber-go/zap#568]
Is it possible to customize the `level` field to output `int` instead of `string`? Thanks.

**Comment by wujiang** [comment]
Or what's the best way to add a new field to all the logs, via `Hooks`?

**Comment by akshayjshah** [comment]
You can customize the way levels are serialized by implementing [`zapcore.LevelEncoder`](https://godoc.org/go.uber.org/zap/zapcore#LevelEncoder) and plugging it into your `zap.Config` or `zapcore.EncoderConfig`.

You'd add a new field to all your logs by using `With`. For example, this adds `"key": "value"` to all your logs:

```
logger := zap.NewExample()
logger = logger.With(zap.String("key", "value"))
// now pass around logger
```
