### ISSUE TITLE
Add an http.Handler to make runtime logging changes

### ISSUE THREAD

**Issue by akshayjshah** [uber-go/zap#58]
Add a constructor that takes a zap logger and returns an HTTP handler to manage common runtime changes (e.g., changing the log level). Applications can mount that handler wherever they like.

**Comment by pravj** [comment]
Hi @akshayjshah, I have worked on a prototype for this. Am I allowed to send a PR?

**Comment by akshayjshah** [comment]
Of course! I'd love to take a look at what you have.

Please make sure to [sign Uber's Contributor License Agreement](https://docs.google.com/a/uber.com/forms/d/1pAwS_-dA1KhPlfxzYLBqK6rsSWwRwH95OCCZrcsY5rk/viewform) when you open the PR.

**Comment by akshayjshah** [comment]
Added in #71 and #72.
