### ISSUE TITLE
How to configure NewProduction() to log to stdout?

### ISSUE THREAD

**Issue by sugarjig** [uber-go/zap#584]
The `NewProduction()` convenience function configures the logger with `OutputPaths` set to `stderr`. Is there an easy way to configure this with `stdout` without creating an entirely new config?

**Comment by sugarjig** [comment]
This turned out to be much easier than I thought. I was looking at the Basic Configuration example in the docs, and I wasn't crazy about the idea of unmarshalling JSON to configure the logger. This was much simpler:

```go
config := zap.NewProductionConfig()
config.OutputPaths = []string{"stdout"}
zapLogger, err := config.Build()
```

Sorry for the noise!

**Comment by gtato** [comment]
It still shows that using this logger is so counterintuitive.

**Comment by zaddok** [comment]
So basically, to get a simple stdout logger one must do:

```
func StdoutLogger() (*zap.Logger) {
	config := zap.NewProductionConfig()
	config.OutputPaths = []string{"stdout"}
	log, _ := config.Build()
	return log
}
```

Perhaps a helper function can be added to the standard library to do this?
