### ISSUE TITLE
undefined:zap.Level zap.CheckedMessage

### ISSUE THREAD

**Issue by ansongit** [uber-go/zap#585]
when i replace the libary "github.com/uber-go/zap" to  "go.uber.org/zap" in  _**gorouter**_ project, i still get follow message, like that:
```
logger\logger.go:9:8: undefined: zap.Level
logger\logger.go:9:28: undefined: zap.CheckedMessage
logger\logger.go:10:6: undefined: zap.Level
logger\logger.go:31:9: undefined: zap.NewJSONEncoder
logger\logger.go:32:3: undefined: zap.LevelString
logger\logger.go:33:3: undefined: zap.MessageKey
logger\logger.go:34:3: undefined: zap.EpochFormatter
logger\logger.go:75:28: undefined: zap.Level
logger\logger.go:100:29: undefined: zap.LevelFormatter
logger\logger.go:108:24: undefined: zap.Level
```

can someone tell me how to solve this problem?

**Comment by billf** [comment]
c.f. #352, #401, #535 and [FAQ: import go.uber.org](https://github.com/uber-go/zap/blob/master/FAQ.md#what-does-the-error-expects-import-gouberorgzap-mean)

If you are importing gorouter code into a local project, all of the imports in your project will have to match theirs. You may need to submit a pull request to change all references to stop using `github.com/uber-go/zap` in favor of `go.uber.org/zap`.
