### ISSUE TITLE
It seems lost data when I use zap with Gin. What's wrong of my code?

### ISSUE THREAD

**Issue by fcce** [uber-go/zap#588]
I'm newbie for Go, It seems lost data when I use zap with Gin. What's wrong of my code?
```go

package main

import (
	"fmt"
	"sync/atomic"

	"github.com/gin-gonic/gin"
	"go.uber.org/zap"
)

var logger *zap.Logger
var count int64 = 0

func ZapTest(c *gin.Context) {
	defer logger.Sync()
	logger.Info("zap test", zap.Int64("count", count))
	atomic.AddInt64(&count, 1)
	fmt.Println(count)
	c.String(200, "success")
}

func main() {
	cfg := zap.NewProductionConfig()
	cfg.OutputPaths = []string{"zap.log"}
	logger, _ = cfg.Build()

	gin.SetMode("debug")
	router := gin.Default()
	router.GET("zap", ZapTest)
	router.Run(":8080")
}


```

test the code with [wrk](https://github.com/wg/wrk)

```shell
wrk -t1 -c1 -d 1s http://localhost:8080/zap
```

for my computer, the result is below:

```
Running 1s test @ http://localhost:8080/zap
  1 threads and 1 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   246.79us  704.84us   9.94ms   96.55%
    Req/Sec     7.19k     1.39k    8.39k    81.82%
  7876 requests in 1.10s, 0.92MB read
Requests/sec:   7159.98
Transfer/sec:    860.04KB
```

I'm sure it's request 7876 times, but the zap.log file only 276 lines data.

```shell
wc -l zap.log
# 276 zap.log
```

So, what's wrong?

**Comment by Gyllsdorff** [comment]
The default ProductionConfig uses the sampling feature to silently drop some log rows.

https://github.com/uber-go/zap/blob/master/config.go#L118-L121

https://godoc.org/go.uber.org/zap#SamplingConfig
> SamplingConfig sets a sampling strategy for the logger. Sampling caps the global CPU and I/O load that logging puts on your process while attempting to preserve a representative subset of your logs.

> Values configured here are per-second. See zapcore.NewSampler for details.

**Comment by fcce** [comment]
@Gyllsdorff Thanks. The result is correct after I set Sampling to 'nil'

```go
    cfg.Sampling = nil
```
