### ISSUE TITLE
add zap.Type field constructor for the type of some value

### ISSUE THREAD

**Issue by nhooyr** [uber-go/zap#589]
E.g.

```go
logger, err := zap.NewDevelopment()
must(err)

logger.Info("the sky is beautiful", zap.Type("type_of_1", 1))
```

would print 

```json
{"msg":"the sky is beautiful","type_of_1":"int"}
```

**Comment by akshayjshah** [comment]
`zap.Any` is almost certainly the fastest option if you don't know the type of your object: in many cases, it avoids any reflection at all.

**Comment by nhooyr** [comment]
@akshayjshah I don't want to print the object itself, only its type.

**Comment by prashantv** [comment]
Reopening since it was closed due to misunderstanding of the request.

**Comment by akshayjshah** [comment]
Ah, I see - sorry, I totally misread the issue. From outside zap, you can implement this either using the `reflect` package, as you suggest, or a bit more simply:

```
func Type(key string, i interface{}) zap.Field {
  return zap.String(key, fmt.Sprintf("%T", i))
}
```

This uses reflection under the hood, of course.

**Comment by nhooyr** [comment]
What do you think of having a field that allows:

```go
zap.StringerFunc("some_key", func() string {
    return fmt.Sprintf("%T", sometime)
})
```

This would make it really easy to optimize some zap prints because the function would only be called lazily if the log was enabled.

**Comment by akshayjshah** [comment]
I don't think I'd make that a zap concern; intstead, I'd define a small type that implements `fmt.Stringer`.

```go
type StringerFunc func() string

func (f StringerFunc) String() string { return f() }
```

which should make this possible:

```go
zap.Stringer("some_key", StringerFunc(func() string {
  return fmt.Sprintf("%T", sometime)
})
```

**Comment by nhooyr** [comment]
Going to close as it has been a long time and I'm not sure if this is relevant anymore.
