### ISSUE TITLE
Add support for `Stringers` field type

### ISSUE THREAD

**Issue by JeanMertz** [uber-go/zap#598]
Zap has support for [`Stringer`](https://github.com/uber-go/zap/pull/32), which indeed makes the log entries a bit more simple to construct. However, the real power to me would be if it also had a `Stringers` (plural) function.

Right now, if you have an array of objects that implement `fmt.Stringer`, you have to manually loop them, extract the strings, and then call `zap.Strings`. It would be a lot cleaner if we could simply pass them as-is to `Stringers` and let Zap handle the rest.

**Comment by saurabh95** [comment]
With generics, this is possible to implement now.
The PR to add this functionality is already merged and released in the latest version: https://github.com/uber-go/zap/pull/1155

**Comment by abhinav** [comment]
Yep! Done with #1155. Thanks, @saurabh95.
