### ISSUE TITLE
Logger not safe for concurrent use

### ISSUE THREAD

**Issue by glyn** [uber-go/zap#604]
The [documentation](https://github.com/uber-go/zap/blob/7e7e266a8dbce911a49554b945538c5b950196b8/logger.go#L34-L35) of `Logger` states:
> All methods are safe for concurrent use.

However, [this](https://gist.github.com/glyn/9ade8ee0ace9227251d60831d064c34a) simple test shows that running `Info` calls concurrently loses logs.

Example output:
> 193 logs produced, 200 expected

Environment:
* go version go1.10.1 darwin/amd64
* macOS High Sierra 10.13.5

**Comment by prashantv** [comment]
This is likely sampling (enabled by default in the production config) at play, see similar issue: https://github.com/uber-go/zap/issues/588

**Comment by glyn** [comment]
Closing. The testcase was invalid. Apologies.

**Comment by glyn** [comment]
Thanks @prashantv. I updated the testcase to use a `sync.WaitGroup` to ensure goroutines terminate and I also set `cfg.Sampling = nil` to avoid sampling. Now works perfectly.
