### ISSUE TITLE
[question] Is there a function provided that can flatten map[string]interface{} and map[string]string to Key/Value Fields

### ISSUE THREAD

**Issue by etsangsplk** [uber-go/zap#608]
Hi, I am not sure if there is a builtin-encoder / functions already provided in the package to correctly detect, flatten map[string]interface{} and map[string]string to Fields. I am not looking for nested structure.

I don't want to use reflect to detect and then try to pieces together an array of Field if it cn be done more effectively.

Form a glance it looks like the package already contains pieces (encoder???)
If you know any examples, please point it out.

**Comment by jcorbin** [comment]
For the `map[string]interface{}` case, you could write a simple utility outside of zap:
```
func map2fields(m map[string]interface{}) []zap.Field {
  fields := make([]zap.Field, 0, len(m))
  for k, v := range m {
    fields = append(fields, zap.Any(k, v))
  }
  return fields
}
```

You could do a similar by driving `zap.String` over a `map[string]string`.
