### ISSUE TITLE
Go Modules

### ISSUE THREAD

**Issue by jerome-laforge** [uber-go/zap#639]
Hello,
Are you plan to support Go Modules with go.mod file?

Thx in adv

**Comment by akshayjshah** [comment]
Yes! We'll definitely support modules once 1.12 lands; in the meantime, we'll add support as time permits.

**Comment by cocorambo** [comment]
If you find the time it could be really cool :)

**Comment by A-limon** [comment]
Any new updates ?

**Comment by tx1920** [comment]
Almost a year...

**Comment by kidlj** [comment]
Please...
