### ISSUE TITLE
Add a `Must` function to zap

### ISSUE THREAD

**Issue by slnt** [uber-go/zap#640]
I often find myself doing something as such

```
l, _ := zap.NewProduction()
log := l.Sugar()
```

It would be nice if Zap had functionality similar to, for example, aws.Session, as seen here: https://github.com/aws/aws-sdk-go/blob/master/aws/session/session.go#L279

This would simplify logger creation to a single, and in my opinion, more readable line of

```
log := zap.Must(zap.NewProduction()).Sugar()
```

**Comment by nhooyr** [comment]
How can creating a development or production logger error anyway?

**Comment by jcorbin** [comment]
Two current primary ways are:
- [broken encoder config](https://github.com/uber-go/zap/blob/master/encoder.go#L64)
- failure to [open sinks](https://github.com/uber-go/zap/blob/master/config.go#L172) (output files)
