### ISSUE TITLE
How to make calls to the standard log package be handled by zap

### ISSUE THREAD

**Issue by krostar** [uber-go/zap#651]
Hi,

I was a `logrus` user and I was able to easily make the default logger use it with the following example:
```
logger := logrus.WithField("std", "unhandled call to standard log package")
log.SetPrefix("")
log.SetOutput(logger.WriterLevel(logrus.LevelError))
```

Setting this helps with the formatting of logs (for example json), and helps to quickly discover unhandled calls to the standard log package.

From what I get reading the doc, I didn't see a way to retrieve a io.Writter from a zap.Logger, or zapcore.Core.

Do you have any idea of how I can achieve this ?
Thanks for your help,
krostar

**Comment by NWilson** [comment]
This can be achieved using `RedirectStdLog` to change the log library's global logger, or `NewStdLog` to obtain a standard `log.Logger` from a `zap.Logger`.

You can't get an io.Writer from the Logger, instead by calling RedirectStdLog, the io.Writer is created internally and set on the log.Logger.

This issue can be closed, the requested functionality is provided.

**Comment by krostar** [comment]
Hi,

Nice, I missed this function in the doc.
Thx for pointing it to me.

**Comment by akshayjshah** [comment]
Thank you for answering this issue, @NWilson!
