### ISSUE TITLE
What is the purpose of the DPanic level?

### ISSUE THREAD

**Issue by nhooyr** [uber-go/zap#668]
Why would I want to panic in dev but just error in prod?

**Comment by jcorbin** [comment]
A good analog can be seen in thinking around assertions:
- frequently enabled in debug builds
- usually disabled in the shipping version of the software
- they're frequently used for "inconceivable" branches or data corruption states; usually reality proves that that those "inconceivable" cases do crop up

Now, that's more an answer to "Why do we (Uber) want to not `panic()` in prod" when such things happen; ymmv ;-)
