### ISSUE TITLE
Is it possible to log to a different file based on a rule

### ISSUE THREAD

**Issue by grzkv** [uber-go/zap#672]
Is it possible to write the log to a different file when a certain condition is fulfilled?

E.g. write to file `a.out` by default, but write to `b.out` when the log has field `tag: x` or level is `ERROR`.

Thanks in advance for the answers.

**Comment by NathanZook** [comment]
I believe that https://godoc.org/go.uber.org/zap#example-package--AdvancedConfiguration encompasses your needs.

**Comment by grzkv** [comment]
It does indeed. Thanks.
