### ISSUE TITLE
Is there a convenient way to set dynamic output filename?

### ISSUE THREAD

**Issue by virezox** [uber-go/zap#673]
The BasicConfiguration Sample Code
```
rawJSON := []byte(`{
	  "level": "debug",
	  "encoding": "json",
	  "outputPaths": ["stdout", "/tmp/logs"],
	  "errorOutputPaths": ["stderr"]
	  "encoderConfig": {
	    "messageKey": "message"
	  }
	}`)

var cfg zap.Config
if err := json.Unmarshal(rawJSON, &cfg); err != nil {
    panic(err)
}
logger, err := cfg.Build()
```
I'm working with global logger `zap.S()`
Is there a convenient way to set log filename by date (e.g.  filename:` outputlog20190101`).

**Comment by NathanZook** [comment]
Not really.  If you've not already wrapped the zap.Logger type, you're going to have to do that now.  WrapCore will become your friend, I think...

**Comment by khanakia** [comment]
@virezox how did you achieve that ? I want to have the logs by date also
