### ISSUE TITLE
Log via struct tags

### ISSUE THREAD

**Issue by slnt** [uber-go/zap#683]
This would be an enhancement.

Sometimes I have a data structure that I would like to log in several different log messages. Yes I could just copy the code to do this, but if the structure has many fields it is often unwieldy and large.

It would be nice to be able to tag a struct for logging via zap, kind of like the following:

```go
type Foo struct {
  IntField    int    `zap:"int_field"`
  StringField string `zap:"string_field"`
  Optional    string `zap:"optional, omitempty"
}

log.Infow("my message", zap.Struct(&foo))
```

**Comment by abhinav** [comment]
Hello! Would the [zapcore.ObjectMarshaler][1] interface suffice your needs?

You can implement the relevant method on your struct,

```go
func (f *Foo) MarshalLogObject(enc zapcore.ObjectEncoder) error {
    enc.AddInt("int_field", f.IntField)
    enc.AddString("string_field", f.StringField)
    if f.Optional != "" {
        enc.AddString("optional", f.Optional)
    }
    return nil
}
```

Then you can log the struct with [zap.Object][2].

    log.Infow("my message", zap.Object("foo", &foo))
    
An advantage of this technique is that you don't have to pay the cost of
reflection to enumerate the struct fields and read their tags.

[1]: https://godoc.org/go.uber.org/zap/zapcore#ObjectMarshaler
[2]: https://godoc.org/go.uber.org/zap#Object

**Comment by slnt** [comment]
Would that turn up in the logs as follows?

```json
{
  "foo": {
    "int_field": 0,
    "string_field": "test"
  }
} 
```

**Comment by slnt** [comment]
We send our logs to https://www.honeycomb.io/ and I'm not sure if they allow for nested JSON searching like that

**Comment by slnt** [comment]
If it came out as several log fields, that would be best! Something like

```json
{
  "foo.int_field": 0,
  "foo.string_field": "test"
}
```

**Comment by abhinav** [comment]
Yes, it would encode as,

```
{
  "foo": {
    "int_field": 0,
    "string_field": "test"
  }
}
```

Unfortunately, the format you're suggesting is fundamentally different from
Zap's standard JSON encoder, so it would be a significant breaking change to
the library.

That said, I checked Honeycomb's documentation and they support receiving
nested JSON structures and flattening them on their end
(see https://docs.honeycomb.io/getting-data-in/integrations/json/). So you
should be able to use Zap's standard JSON encoder as-is.

**Comment by abhinav** [comment]
Looks like the issue has been resolved. Closing.
Feel free to reopen or create a new issue for follow up questions.
