### ISSUE TITLE
Define my own Field type?

### ISSUE THREAD

**Issue by orai-arturo** [uber-go/zap#693]
I'd like to create my own Field types for my own objects. Is that possible?

**Comment by abhinav** [comment]
Hello! Can you elaborate on your use case, please? Fields that don't boil down
to one of the types in [zapcore.FieldType][1] isn't quite feasible but there
may still be extension points enough to accomplish what you're trying to do.

[1]: https://godoc.org/go.uber.org/zap/zapcore#FieldType

**Comment by orai-arturo** [comment]
In the past, I've created "Fields" that would provide a consistent view of a type.

Say I have a type User that has a dozen or two fields.  Whenever I log it I only want to log some of those fields.  I do something like log.Debug("user has requested bonus points", logUser(user))

It provides consistency of logging for a particular type.  It's a more compact syntax vs  log.Debug("user has requested bonus points", String(user.Name), String(user.id), <etc>)

**Comment by abhinav** [comment]
Ah, that makes sense.

You can do something similar by implementing the [zapcore.ObjectMarshaler][1]
interface on your type. The interface lets you customize how objects are
represented when logged with [zap.Object][2].

```go
func (u *User) MarshalLogObject(enc zapcore.ObjectEncoder) error {
  enc.AddString("id", u.ID)
  enc.AddString("name", u.Name)
  return nil
}
```

With that in place, `zap.Object("user", user)` will be logged as the field,

    "user": {"id": user.ID, "name: user.Name}

Similarly, Zap provides a [zapcore.ArrayMarshaler][3] interface for use with
[zap.Array][4] that can be used when you want a custom type to be logged as an
array instead.

[1]: https://godoc.org/go.uber.org/zap/zapcore#ObjectMarshaler
[2]: https://godoc.org/go.uber.org/zap#Object
[3]: https://godoc.org/go.uber.org/zap/zapcore#ArrayMarshaler
[4]: https://godoc.org/go.uber.org/zap#Array

**Comment by orai-arturo** [comment]
The interaction between `zap.Array` and an array of custom types would do the obvious thing?  Or are you saying I'd need both MarshalLogObject and another one for arrays of a custom type?

**Comment by abhinav** [comment]
If you use `zap.Array`, you must provide an object that implements
ArrayMarshaler. The type system doesn't allow for it to accept arbitrary
slices so yeah, you'd have to implement ArrayMarshaler for a new type that
wraps a slice of your custom type.

Zap provides array helpers for many types defined in the standard library; you
may want to replicate the [same pattern][1] if you end up needing to log an
array of your custom types.

The added boilerplate isn't perfect but FWIW, in practice we have found that
we need to log arrays of objects far less often than arrays of primitives.

[1]: https://github.com/uber-go/zap/blob/badef736563f8135e0add3232b06f58656da03c8/array.go#L103

**Comment by abhinav** [comment]
Closing because the question was answered.

Feel free to re-open if you disagree or create a new issue

**Comment by abhinav** [comment]
Closing because the question was answered. Feel free to re-open if you disagree, or create a new issue if you have more questions.
