### ISSUE TITLE
feature request : interface around time.Now

### ISSUE THREAD

**Issue by ran-berenfeld** [uber-go/zap#694]
we use some clock testing packages like 
https://github.com/jonboulle/clockwork
that relies on the tested code not calling directly time.Now()
can we have some interface in the encoder configuration ?

for example TimeSource interface that implemented the time.Now(), and in the zap encoder configuration an option to put your own interface to supply time ?

**Comment by prashantv** [comment]
This may not be exactly what you're looking for, but perhaps it'll solve your problem: There is a testing package in zap which creates a logger that captures logs in-memory: [observer](https://godoc.org/go.uber.org/zap/zaptest/observer).

```
core, logs := observer.New(zap.ErrorLevel)
logger := zap.New(core)

// pass in logger to code you'r testing
```


You can use `logs.All()` to get all logs, with timestamps, or use `AllUntimed()` to get all logs without timestamps.
