### ISSUE TITLE
Interface to implement for custom encoding of non-objects?

### ISSUE THREAD

**Issue by slnt** [uber-go/zap#698]
I'm looking for something similar to the `ObjectMarshaller` interface, but for simpler types.

I have an enum type defined, `type MyEnum int` that has a `String` method. I'd like to define some function such that whenever Zap goes to encode something fo this type, it will use `zap.Stringer` to do so.

Perhaps something like `func (e MyEnum) ZapField(key string) zap.Field`? From my scanning of the docs I haven't found anything as such.

**Comment by prashantv** [comment]
If you implement the [`TextMarshaler`](https://golang.org/pkg/encoding/#TextMarshaler) interface, then it should be used by the JSON encoder.

Try implementing `func (e MyEnum) MarshalText() ([]byte, error)`

**Comment by slnt** [comment]
Awesome, that worked! Is that documented at all somewhere?
