### ISSUE TITLE
Add a Sentry hook

### ISSUE THREAD

**Issue by akshayjshah** [uber-go/zap#70]
This isn't a blocking issue for 1.0, but we should provide a Sentry hook (either in a subpackage or a completely separate repo). It'll be useful for internal users and as an example of hook-based external integrations.

**Comment by belak** [comment]
I'd be happy to work on this, but it looks like this would need to be added using `hook` and/or `Option`, both of which aren't public.

**Comment by sectioneight** [comment]
What's the priority on this? I've heard rumors we're moving off Sentry internally

**Comment by akshayjshah** [comment]
Priority here depends entirely on whether we're planning to migrate our internal midi-repo to zap. We integrate with Sentry via a logger hook, so we'd need a similar mechanism for zap.

Even if we don't actually ship a Sentry hook, it'd be good to rough one out - that way we're sure that the public API is sufficient to support this kind of use case. For external users, integrating with Sentry/Rollbar/Bugsnag/etc is often important.

**Comment by akshayjshah** [comment]
Closing this, since we've decided to go in another direction internally.

I'd strongly prefer not to accumulate plugins for every exception/error reporting service (Sentry, Bugsnag, Rollbar, etc.) in zap - these should ship as external hooks or wrappers.

**Comment by belak** [comment]
We recently cleaned up our internal logging and decided to start using raven-go directly anyway, as it gives us much more control than a logging plugin, particularly because of stack traces and other complications.

Anyway, Hook is a thing now anyway, so it should be simple to implement this hook if a user wants it.
