### ISSUE TITLE
can I change the place in output ?

### ISSUE THREAD

**Issue by shawmraz** [uber-go/zap#701]

**Comment by shawmraz** [comment]
Now is: {"level":"info","time":"","caller":"main.go:11","msg":"working"}
==>
{"level":"info","time":"","msg":"working", "caller":"main.go:11"}

**Comment by abhinav** [comment]
Hello, can you clarify what you are asking, please?

**Comment by prashantv** [comment]
I think the request is to reorder the JSON field serialization order (currently we encode caller, then message, and the request seems to be message, then caller).

From [json.org,](http://json.org/)
> An object is an unordered set of name/value pairs.

For quick inspection, the ordering is definitely useful, but making this flexible sounds overly complex, given that the format shouldn't care about order.

**Comment by shawmraz** [comment]
@abhinav @prashantv thank you for your help
"currently we encode caller, then message, and the request seems to be message, then caller"
That is actually what I need. 
now my log format is like this , with  console-mode of zap
`2019-04-26T16:57:22.300+0800	INFO	server/test/main.go:54	this is a message`
I think mostly the message field is more important, so I wanna find a way to prepose it.

**Comment by prashantv** [comment]
You can clone the console encoder, change the ordering to what you'd like, and use that in your logger. If you don't care about the other fields, you can probably set the `TimeKey`, `LevelKey`, etc to be empty strings, in which case they won't be encoded.

Changing the order within the existing console encoder would be a backwards incompatible change, and providing flexibility seems overly complex.

**Comment by linlih** [comment]
Same question here. I think the caller info is too long, the msg string is more important than the caller info。
