### ISSUE TITLE
block writing log

### ISSUE THREAD

**Issue by Sunfengcheng** [uber-go/zap#703]
I write a new grpc service,then i invoke it many times,if no log print,it works ok,when i print one log,the service is blocked,I found trace like this:

```
goroutine 4953 [semacquire, 19 minutes]:
sync.runtime_SemacquireMutex(0xc0001ed844, 0x0)
	C:/Go/src/runtime/sema.go:71 +0x44
sync.(*Mutex).Lock(0xc0001ed840)
	C:/Go/src/sync/mutex.go:134 +0x106
nextfin.com/vendor/go.uber.org/zap/zapcore.(*lockedWriteSyncer).Write(0xc0001ed840, 0xc000354000, 0x43, 0x400, 0x1680360, 0xc000216e00, 0x13)
	D:/gonfworkspace/src/nextfin.com/vendor/go.uber.org/zap/zapcore/write_syncer.go:65 +0x38
nextfin.com/vendor/go.uber.org/zap/zapcore.(*ioCore).Write(0xc000206b40, 0x0, 0xbf287f8af9b72134, 0x376dde8a9d, 0x1680360, 0xc000216e00, 0x13, 0xf1bfa2, 0xc, 0x0, ...)
	D:/gonfworkspace/src/nextfin.com/vendor/go.uber.org/zap/zapcore/core.go:90 +0x10d
nextfin.com/vendor/go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc00031e000, 0x0, 0x0, 0x0)
	D:/gonfworkspace/src/nextfin.com/vendor/go.uber.org/zap/zapcore/entry.go:215 +0xf0
nextfin.com/vendor/go.uber.org/zap.(*Logger).Info(0xc0000b7c80, 0xf1bfa2, 0xc, 0x0, 0x0, 0x0)
	D:/gonfworkspace/src/nextfin.com/vendor/go.uber.org/zap/logger.go:187 +0x86
nextfin.com/nfplatform/locallive/serv.(*localliveServer).GetStatus(0xc0000ad300, 0x1036b40, 0xc000364c00, 0xc000091b40, 0xc0000ad300, 0xe40760, 0xc00056c6d0)
	D:/gonfworkspace/src/nextfin.com/nfplatform/locallive/serv/serv.go:131 +0x5b
nextfin.com/nfplatform/locallive/api._LocalliveService_GetStatus_Handler.func1(0x1036b40, 0xc000364c00, 0xea90c0, 0xc000091b40, 0xc00056c800, 0xc00042da01, 0x40e4cf, 0x20)
	D:/gonfworkspace/src/nextfin.com/nfplatform/locallive/api/locallive.service.pb.go:370 +0x8d
nextfin.com/local-live/app/serv.Run.func1(0x1036b40, 0xc000364c00, 0xea90c0, 0xc000091b40, 0xc000091b60, 0xc000091b80, 0xc00042db18, 0x40e4cf, 0x70, 0xed1c80)
	D:/gonfworkspace/src/nextfin.com/local-live/app/serv/init.go:140 +0x1a5
nextfin.com/nfplatform/locallive/api._LocalliveService_GetStatus_Handler(0xeed7a0, 0xc0000ad300, 0x1036b40, 0xc000364c00, 0xc0002f9260, 0xc00020f0f0, 0x0, 0x0, 0x442f87, 0x442cda)
	D:/gonfworkspace/src/nextfin.com/nfplatform/locallive/api/locallive.service.pb.go:372 +0x15f
nextfin.com/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000c3760, 0x1039780, 0xc0002ca000, 0xc0001ee780, 0xc000206e70, 0xd3e730, 0x0, 0x0, 0x0)
	D:/gonfworkspace/src/nextfin.com/vendor/google.golang.org/grpc/server.go:920 +0x776
nextfin.com/vendor/google.golang.org/grpc.(*Server).handleStream(0xc0000c3760, 0x1039780, 0xc0002ca000, 0xc0001ee780, 0x0)
	D:/gonfworkspace/src/nextfin.com/vendor/google.golang.org/grpc/server.go:1142 +0x130f
nextfin.com/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0002640b0, 0xc0000c3760, 0x1039780, 0xc0002ca000, 0xc0001ee780)
	D:/gonfworkspace/src/nextfin.com/vendor/google.golang.org/grpc/server.go:637 +0xa6
created by nextfin.com/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	D:/gonfworkspace/src/nextfin.com/vendor/google.golang.org/grpc/server.go:635 +0xa8
```

**Comment by Sunfengcheng** [comment]
Does anyone can give a help?

**Comment by prashantv** [comment]
Unfortunately there's not enough information to help you out here. Zap uses a lock to ensure that it doesn't call `Write` in parallel, see [`zap.CombineWriteSyncers`](https://godoc.org/go.uber.org/zap#CombineWriteSyncers).

If you see a goroutine blocked on the `Lock`, it means that some other goroutine has acquired the lock, has called `Write`, but the `Write` has not returned. If you are dealing with files, then the disk write could be blocked (disk issues, full disk, etc). If you're dealing with stdout/stderr, perhaps the pipe is full.
 
If you dump all goroutines, you should find some other goroutine blocked in the `Write`.

**Comment by Sunfengcheng** [comment]
> Unfortunately there's not enough information to help you out here. Zap uses a lock to ensure that it doesn't call `Write` in parallel, see [`zap.CombineWriteSyncers`](https://godoc.org/go.uber.org/zap#CombineWriteSyncers).
> 
> If you see a goroutine blocked on the `Lock`, it means that some other goroutine has acquired the lock, has called `Write`, but the `Write` has not returned. If you are dealing with files, then the disk write could be blocked (disk issues, full disk, etc). If you're dealing with stdout/stderr, perhaps the pipe is full.
> 
> If you dump all goroutines, you should find some other goroutine blocked in the `Write`.

Thanks for your reply，log was printed to stdout ,I found one  goroutine blocked in the write, the stack trace like this:
goroutine 4937 [syscall, 3 minutes, locked to thread]:
syscall.Syscall6(0x7ffe805f1370, 0x5, 0xd1c, 0xc00009a000, 0x43, 0xc0003cb57c, 0x0, 0x0, 0x0, 0x0, ...)
	C:/Go/src/runtime/syscall_windows.go:185 +0xfc
syscall.WriteFile(0xd1c, 0xc00009a000, 0x43, 0x400, 0xc0003cb57c, 0x0, 0xc0001e2680, 0xc0003cb500)
	C:/Go/src/syscall/zsyscall_windows.go:328 +0xd5
syscall.Write(0xd1c, 0xc00009a000, 0x43, 0x400, 0xc0003cb5d8, 0x5907f8, 0xc000074440)
	C:/Go/src/syscall/syscall_windows.go:320 +0x6f
internal/poll.(*FD).Write(0xc0000a4280, 0xc00009a000, 0x43, 0x400, 0x0, 0x0, 0x0)
	C:/Go/src/internal/poll/fd_windows.go:650 +0x17a
os.(*File).write(0xc0000a2008, 0xc00009a000, 0x43, 0x400, 0x0, 0xc0003cb678, 0x5ad3e2)
	C:/Go/src/os/file_windows.go:224 +0x55
os.(*File).Write(0xc0000a2008, 0xc00009a000, 0x43, 0x400, 0x0, 0x0, 0x10)
	C:/Go/src/os/file.go:145 +0x70
nextfin.com/vendor/go.uber.org/zap/zapcore.(*lockedWriteSyncer).Write(0xc0001fd680, 0xc00009a000, 0x43, 0x400, 0x1683360, 0xc00020eda0, 0x13)
	D:/gonfworkspace/src/nextfin.com/vendor/go.uber.org/zap/zapcore/write_syncer.go:66 +0x6d

Can you give a help why it happens?And how can i deal with the block? Thanks

**Comment by prashantv** [comment]
Unfortunately that's not an issue with zap, you to have some issue with the file write blocking on your OS. You may want to look into whether your disk is in a good state (has space, is writable, isn't being too heavily used, etc).

**Comment by youguanxinqing** [comment]
I have met the issue today. Did you slove it ?

**Comment by youguanxinqing** [comment]
@Sunfengcheng   I have met the issue today. Did you slove it ?

**Comment by l-iberty** [comment]
@Sunfengcheng I have met the same issue...
