### ISSUE TITLE
Kubernetes Logging with newline in json format

### ISSUE THREAD

**Issue by Iaskebba** [uber-go/zap#712]
I changed the zapConfig Encoding to json but a newline is printed at the end of the log. This causes fluentd to have a lot of problems as it isn't a valid json object while parsing. I can replace the newline with EncoderConfig LineEnding but it doesn't accept an empty string and if it's something else the buffer isn't flushed properly. Is there anyway to stop zap from printing a newline in with the rest of the log message?

An example of what is being logged:
`{"log":"{\"level\":\"INFO\",\"ts\":\"2019-05-14T22:25:48.166Z\",\"file\":\"websocket/publish.go:51\",\"message\":\"Websocket Brokers changed to rabbit:1 \"}\n","stream":"stderr","time":"2019-05-14T22:25:48.166562459Z"}`

**Comment by prashantv** [comment]
Unfortunately zap defaults to `\n` when the `LineEnding` is not set, and we cannot change that as it would be backwards incompatible.

You may want to try using a value like `","` or `" "` to see if it helps, but this isn't something we can change in zap.

**Comment by navono** [comment]
use jq
