### ISSUE TITLE
Removing "level" and "message" fields when logging

### ISSUE THREAD

**Issue by juicemia** [uber-go/zap#724]
I was trying to figure out how to remove the `"level"` and `"message"` keys from log output and I couldn't find anything in the documentation.

After going through the source code, I found these lines in the JSON encoder's implementation of `EncodeEntry`:

```go
	if final.LevelKey != "" {
		final.addKey(final.LevelKey)
		cur := final.buf.Len()
		final.EncodeLevel(ent.Level, final)
		if cur == final.buf.Len() {
			// User-supplied EncodeLevel was a no-op. Fall back to strings to keep
			// output JSON valid.
			final.AppendString(ent.Level.String())
		}
	}
```
```go
	if final.MessageKey != "" {
		final.addKey(enc.MessageKey)
		final.AppendString(ent.Message)
	}
```

While it works for our use case, this behavior isn't documented anywhere and the `Encoder` interface doesn't specify that it should do that. I'm worried that because of this, at some point it'll change and we'll have to reevaluate how we do this.

I'd like to submit a PR that adds this documentation to the `Encoder` interface, as well as a constant (like `const OmitKey = ""`) to make this behavior explicitly part of the interface.

I wanted to get your feedback on this before submitting the PR.

**Comment by jdheyburn** [comment]
Is this still an issue? Looks like merged PR closes it

**Comment by prashantv** [comment]
Yes this is done, here's an example on how to skip the message / level keys:
```go
package main

import (
	"go.uber.org/zap"
	"go.uber.org/zap/zapcore"
)

func main() {
	cfg := zap.NewProductionConfig()
	cfg.EncoderConfig.MessageKey = zapcore.OmitKey
	cfg.EncoderConfig.LevelKey = zapcore.OmitKey

	logger, err := cfg.Build()
	if err != nil {
		panic(err)
	}

	logger.Info("this is a message", zap.String("field", "field-value"))
}
```
[playground](https://play.golang.org/p/jQTXb36BSW5)

Output:
```
{"ts":1257894000,"caller":"sandbox906972517/prog.go:18","field":"field-value"}
```
