### ISSUE TITLE
Add an option for setting stack skip

### ISSUE THREAD

**Issue by segevfiner** [uber-go/zap#727]
Sometimes you log from internal functions and want the stack trace to point to their caller, for example: a panic recovery middleware/wrapper. This is especially important when directing errors logged to zap to an error collection service such as Sentry/Rollbar/Bugsnag/etc as they rely on the stack trace to identify and merge similar errors.

I'm proposing a new field factory `func StackSkip(key string, skip int) Field` that also allows controlling the stack skip, that is the number of frames to skip from the top of the stack. And a new option `func SetStackSkip(skip int) Option` that can be used to set the stack skip for the automatic stack traces.

**Comment by mfridman** [comment]
@segevfiner Would the `AddCallerSkip` option be useful for you in this case?

https://godoc.org/go.uber.org/zap#AddCallerSkip

**Comment by segevfiner** [comment]
That's only for the caller, we need something similar for the stack trace. Those two will have similar functionality so we might want to consider that it's likely the user will want to set both to the same value. So maybe we should also have an `AddSkip` options which sets both.

**Comment by westwin** [comment]
Yes, I need the same feature as how java does, find maxDepthPerThrowable in https://github.com/logstash/logstash-logback-encoder/tree/logstash-logback-encoder-6.3#customizing-stack-traces

**Comment by prashantv** [comment]
This is similar to the request in #512

I agree that aligning caller skip and stack traces makes sense, but there's also some concerns on backwards compatibility. I think adding an option to align the caller skip and stack trace pruning might be a good way to solve this problem.
