### ISSUE TITLE
Fix LICENSE formatting so GitHub recognizes the license

### ISSUE THREAD

**Issue by pgohite** [uber-go/zap#731]
It would be nice if LICENSE file can be fixed so that github and license checker tools can recognize license type for this repository.

https://help.github.com/en/articles/adding-a-license-to-a-repository

I'll be happy to submit a pull request if needed.

**Comment by prashantv** [comment]
Thanks for flagging this -- do you know what exactly is causing the current LICENSE file to not be recognized?

**Comment by shiranyo** [comment]
Which license is it? MIT?
