### ISSUE TITLE
how to redirect panic(stderr) to logfile?

### ISSUE THREAD

**Issue by Lonenso** [uber-go/zap#738]
I am using zaplog with lumberjack to save log to file. 
I used zap.RedirectStdLog , redirect built-in log to file. 
But I wonder how to redirect panic to logfile easily.

I tried syscall.Dup2, is there a bettey way to do it?
My English is poor, sorry if it troubles you.

**Comment by prashantv** [comment]
Unfortunately there isn't any way to redirect panic output to a log file, see https://github.com/golang/go/issues/16340

We can't run any custom code on any unhandled panic, the best you can do is `defer` a `recover` at the start of any goroutines, and log the panic from there.
