### ISSUE TITLE
Why does zap.Err() have a hardcoded key name?

### ISSUE THREAD

**Issue by jmunson** [uber-go/zap#74]
I noticed that of all the functions that return a zap.Field,  Err is the only one that doesn't let you specify the name.

I don't have any use case where this is a problem, but it just popped out at me as inconsistent and I didn't see any comments or docs around it explaining why it is different.

**Comment by akshayjshah** [comment]
That's a good question - I'll leave an explanatory comment. In using zap (and its internal precursors), we found ourselves often writing `logger.Error("Operation failed.", zap.String("error", err.Error()))`. The `Err` field is just a shortcut for that common pattern.
