### ISSUE TITLE
Trigger Debug Logging At Run Time

### ISSUE THREAD

**Issue by postables** [uber-go/zap#741]
Hello, is there some way of triggering debug logging at runtime via an environment variable, or is this something that has to be done via those implementing zap?

**Comment by prashantv** [comment]
You'll need to handle this yourself. You can also use [`AtomicLevel`](https://godoc.org/go.uber.org/zap#AtomicLevel) to change the level at runtime.

For backend services, we expose HTTP pages (like `net/http/pprof`) to toggle the log level at runtime.

Closing this issue as it's something that should be done outside of zap at a "framework" level.

**Comment by postables** [comment]
Awesome thanks for the quick response
