### ISSUE TITLE
Add Global SetLevel function

### ISSUE THREAD

**Issue by bigmate** [uber-go/zap#755]
Hello everybody!
My project structure is like following:
* cmd
* app
* pkg
  * logger
  * config

In my logger package I have following peace of code which just creates a Logger and replaces zap's global logger

```go
var logger *zap.Logger
var atomicLevel zap.AtomicLevel

func init() {
	lmb := config.NewLumberjack()
	atomicLevel = newAtomicLevel()
	logger = newLogger(lmb, atomicLevel)
	zap.ReplaceGlobals(logger)
	setRotation(lmb)
	onLogLevelChange()
}

func SetLevel(l string) {
	atomicLevel.SetLevel(config.ParseLevel(l))
}
```

and in my main codebase in `app package` where business logic is placed I should sometimes change logging level and I do it like this

```go	
logger.SetLevel("debug")
zap.L().Debug("Message", zap.Duration("exec_time", time.Second))
```

The problem is I don't want to call function from another package to change the behavior of an object which is located completely in different package.
Are there any other better approaches to this problem?

**Comment by prashantv** [comment]
You can create a wrapper type
```
type LoggerWithLevel struct {
  *zap.Logger
  level zap.AtomicLevel
}

func (l *LoggerWIthLevel) SetLevel(...) 
```

And pass the `LoggerWithLevel` around, and set the level by calling it on that instance directly.

That said, this is a more general application design question, so others can feel free to chime in, but I'll close this as there's no zap issues or questions here.

**Comment by celesteking** [comment]
`logger.SetLevel("debug")` doesn't work. 
How do you override the global log level for global logger `zap.L()`?
