### ISSUE TITLE
Change out satori/go.uuid for gofrs/uuid

### ISSUE THREAD

**Issue by coderste** [uber-go/zap#756]
Seems like satori/go.uuid is generating some non-random numbers as seen in this ticket: https://github.com/satori/go.uuid/issues/73

Maybe we should switch it out to use a forked version of the package located here: https://github.com/gofrs/uuid

**Comment by prashantv** [comment]
Zap does not use uuid directly. It's mentioned in `benchmarks/go.sum` so it's likely a transitive dependency of one of the other logging libraries that the benchmarks depend on, but core zap does not have have any dependency on uuid packages.
