### ISSUE TITLE
Option to update logger config for NewDevelopment and NewProduction logger presets

### ISSUE THREAD

**Issue by creatorisback** [uber-go/zap#757]
Need a way to update logger config via options

**Comment by abhinav** [comment]
Can you clarify your request? The NewDevelopment and NewProduction presets
rely on the [NewDevelopmentConfig][1] and [NewProductionConfig][2] functions.
You can retrieve those configurations and modify them in place to build a
different kind of logger based on those presets.

[1]: https://godoc.org/go.uber.org/zap#NewDevelopmentConfig
[2]: https://godoc.org/go.uber.org/zap#NewProductionConfig

**Comment by creatorisback** [comment]
Thanks for clarification
