### ISSUE TITLE
Programatically change output stream

### ISSUE THREAD

**Issue by sethvargo** [uber-go/zap#761]
Similar to the atomic log level, it would be really helpful if you could control the log output stream _after_ the logger is created. This is especially useful when building a client library that uses zap, but end users might want to do some additional customization like setting log level and output paths.

**Comment by jcorbin** [comment]
So you should be able to achieve this by writing a `zapcore.Core` that supports changing destination dynamically. We could then link to such an extension if you publish one in https://github.com/uber-go/zap/blob/master/FAQ.md#extensions, but will likely not be interested in adding and supporting such functionality directly in zap.

In particular, re:
> when building a client library ... end users might want to do some additional customization like setting log level and output paths.
Shouldn't the end user by in control of the config that's getting used by such a library?

**Comment by ansel1** [comment]
You may find some use from https://github.com/gemalto/flume

It's a library we built wrapping zap, but adding things like globally, atomically changing log levels and outputs.  It has a global registry of loggers, and functions for globally reconfiguring them in a concurrency-safe way.  Libraries can create and use loggers, while the main() function retains control over global configuration.  It's not really go's idiomatic pattern (which would prefer constructing the loggers in main, and having libraries treat loggers as injected dependencies), but for logging, we found this easier.  And if you *are* following the dependency injection idiom, it still adds value by letting you dynamically reconfigure those loggers at runtime.
