### ISSUE TITLE
How to update an exists field value?

### ISSUE THREAD

**Issue by axiaoxin** [uber-go/zap#765]
Such as a logger like: `logger = logger.With(zap.String("myfield", "v1"))`
Is there any way to update the myfield's value?

**Comment by prashantv** [comment]
No, there isn't a way to update existing fields, as zap encodes fields as they're added to the logger.

You can add the same field multiple times (#81), but that may lead to undefined behaviour, so I'd recommend using a separate log field.

**Comment by sc-atompower** [comment]
what if the value is a function that returns something or if the value is a pointer to a struct field?
