### ISSUE TITLE
[Feature] log add a forbiddenPrefix

### ISSUE THREAD

**Issue by wanghaoyu1** [uber-go/zap#766]
we always coding base on other modules or libs, but we don't care about the other modules debug or info level logs, so if have a forbiddenPrefix slice, we can solve it

(log *Logger) check
add this code
if log.forbiddenPrefix != nil {
		for _, prefix := range log.forbiddenPrefix {
			if strings.HasPrefix(ce.Caller.FullPath(), prefix) {
				return nil
			}
		}
	}
maybe solve it

https://github.com/whybangbang/zap/blob/921e1c8c56e7af67a98410155ac29ee46865f6c7/logger.go

**Comment by prashantv** [comment]
This feature can be implemented outside of zap by using `WrapCore` to decorate a core. The decorator can filter out entries (similar to your provided snippet).

Since this should be possible without changing zap, we likely won't build this into zap.

**Comment by wanghaoyu1** [comment]
thanks

**Comment by wanghaoyu1** [comment]
> This feature can be implemented outside of zap by using `WrapCore` to decorate a core. The decorator can filter out entries (similar to your provided snippet).
> 
> Since this should be possible without changing zap, we likely won't build this into zap.

we hooked a custom a core, but **checkedEntry.Caller is undefined**.
then i check the zap code ,  i found the **caller is added after all core check** (log *Logger) check(lvl zapcore.Level, msg string)

we can invoke runtime.Caller again in out custom core,but i think it's not fine

how do we solve it? thank you

below is my custom core code

func (s *zloggerCore) Check(ent zapcore.Entry, ce *zapcore.CheckedEntry) *zapcore.CheckedEntry {
	checkedEntry := s.Core.Check(ent, ce)
	fmt.Println(checkedEntry)
	fmt.Println("caller: ", checkedEntry.Caller)
	fmt.Println("hiddenPrefix: ", s.hiddenPrefixs)
	if checkedEntry.Level == zapcore.DebugLevel || checkedEntry.Level == zapcore.InfoLevel {
		if checkedEntry.Caller.Defined && s.hiddenPrefixs != nil {
			for _, prefix := range s.hiddenPrefixs {

				if strings.HasPrefix(checkedEntry.Caller.FullPath(), prefix) {
					return nil
				}
			}
		}
	}


	return checkedEntry
}
