### ISSUE TITLE
Support creating just the core with zaptest and/or export testingWriter

### ISSUE THREAD

**Issue by coryrc** [uber-go/zap#768]
Hello,

I'd like tee logging going into the zaptest logger with some cores I already have, but zaptest creates the whole logger. If testingWriter were TestingWriter or zaptest had a method that provided just the core (and let me specify the level), I could do this without just copying the testingWriter code into my own stuff.

I'm willing to make the PR to do either, if desired.

Thanks,
Cory

**Comment by prashantv** [comment]
It doesn't, but you can easily get the core using the [`.Core()` method](https://godoc.org/go.uber.org/zap#Logger.Core) on the `*Logger`.

Given that it's possible, I'm not sure it's worth expanding the API surface by exporting the core separately.

**Comment by coryrc** [comment]
Oh, I missed that. That is sufficient. Thanks!
