### ISSUE TITLE
> This feature can be implemented outside of zap by using `WrapCore` to decorate a core. The decorator can filter out entries (similar to your provided snippet).

### ISSUE THREAD

**Issue by wanghaoyu1** [uber-go/zap#769]
> This feature can be implemented outside of zap by using `WrapCore` to decorate a core. The decorator can filter out entries (similar to your provided snippet).
> 
> Since this should be possible without changing zap, we likely won't build this into zap.

we hooked a custom a core, but **checkedEntry.Caller is undefined**.
then i check the zap code ,  i found the **caller is added after all core check** (log *Logger) check(lvl zapcore.Level, msg string)

we can invoke runtime.Caller again in out custom core,but i think it's not fine

how do we solve it? thank you

below is my custom core check method
![image](https://user-images.githubusercontent.com/50820046/69774816-f6857580-11d1-11ea-9fd4-0dedadb72dc4.png)

_Originally posted by @wanghaoyu1 in https://github.com/uber-go/zap/issues/766#issuecomment-559326261_

**Comment by prashantv** [comment]
Unfortunately, there isn't any easy solution here. The caller is added at the very end to avoid the performance penalty of looking up the caller if the log isn't going to be written.

One suggestion that avoids the performance penalty:
 * Disable the add caller feature of the logger
 * Caller `runtime.Caller` inside of your `Check`, and manually set the caller on the `Entry` when creating the `CheckedEntry`
