### ISSUE TITLE
Change LogLevel without creating a new core

### ISSUE THREAD

**Issue by weeco** [uber-go/zap#774]
I'd like to create a new subLogger which only logs messages at the `WarnLevel` instead of the `InfoLevel` (which is desired for the rest of the application). I read the other issues about doing so, but they implied creating a new zapcore.

I do not want to create a new zapcore for my sublogger, because my logger's core has hooks which should still be used for the sublogger. So is there any way to create a sublogger which reuses my existent zapcore but only emits log messages at the WarnLevel+?

```go
stripeLogger := logger.
	With(zap.String("source", "stripe")).
	WithOptions(zap.WrapCore(/** Help **/))
stripe.Logger = zap.NewStdLog(stripeLogger)
```

**Comment by prashantv** [comment]
This is possible to do using `WrapCore` and a custom core wrapper, but we don't have an easy way to do it as part of zap today.

I've provided an example here:
https://play.golang.org/p/0uA7ck8mhKx

Given similar requests (#763), I think maybe we should include something as part of zap to simplify this, but would have to make it very clear that it can only ever be used to increase the log level (e.g., decrease the number of logs that would be logged).
