### ISSUE TITLE
BUG: Set key name appends to the previous name

### ISSUE THREAD

**Issue by adibrastegarnia** [uber-go/zap#778]
When we use  zap.New(core).Named(name),  it appends to the previous name if it is already set. Is there any logic behind that? I would expect when we change the name, it gets a new name.

**Comment by prashantv** [comment]
This is working as intended, as explained in the documentation:
https://godoc.org/go.uber.org/zap#Logger.Named
> Named adds a new path segment to the logger's name.

The goal is to capture information about the component, including the hierarchy of how the component got initialized.

For example, an application may have multiple instances of a "connection" for different services that it talks to.
* Connection to user service
* Connection to payment service

In this case, the user client may do `logger.Named("user")` and then pass that logger when creating a connection, which would further add `.Named("connection")`. The payment client would do something similar. If the name replaced the previous name, we would have 2 loggers called `connection`, but by appending the name, the separate loggers can be identified by their name being `user.connection` and `payment.connection`.
