### ISSUE TITLE
Colored output encoder- garbage output

### ISSUE THREAD

**Issue by adibrastegarnia** [uber-go/zap#779]
I enabled the Capital level color encoder but in my console I am seeing some random characters and numbers. Is there any specific setting is needed? I am using zsh on MAC OS

```
{"level":"\u001b[34minfo\u001b[0m","ts":"2020-01-28T10:23:34.691-0800","controller":"controller","msg":"[controller logger]"}
{"level":"\u001b[31merror\u001b[0m","ts":"2020-01-28T10:23:34.691-0800","controller/change/network":"controller/change/network","msg":"[3- change controller/change/network log level]"}
```

**Comment by adibrastegarnia** [comment]
@prashantv 
I am wondering this is a valid issue?

**Comment by prashantv** [comment]
Those odd characters are the escape codes used to set colors for your console. It seems like your console is showing the escape codes, are you piping the output through some intermediate process like less?

Zap is outputting escape codes as expected, it seems like an issue with your set up.

**Comment by adibrastegarnia** [comment]
@prashantv 
I don't use any intermediate process. I use zsh on MAC OS but not sure that could be an issue.

**Comment by prashantv** [comment]
Sorry, I just realized that the output is JSON -- and so the JSON encoder is probably escaping the color-related escape codes.

Colored output will not work with the JSON encoding, you must set the `Encoding` to `"console"` for colored output to work.

**Comment by adibrastegarnia** [comment]
@prashantv 
Good to know. If you want to close it that is fine or you can keep it open if you want to fix it in nearly future.
