### ISSUE TITLE
Zap log level Hierarchy

### ISSUE THREAD

**Issue by adibrastegarnia** [uber-go/zap#780]
I am looking for Zap log level Hierarchy. It looks like independent of level INFO level will be printed all the times. Is that correct. Do you follow the following log level Hierarchy
```

OFF
FATAL
ERROR
WARN 
INFO
DEBUG
TRACE
ALL
```

**Comment by prashantv** [comment]
The level precedence can be seen in the documentation here:
https://godoc.org/go.uber.org/zap/zapcore#Level

Debug, Info, Warn, Error, DPanic, Panic, Fatal

We don't have an "all" or "off". If you want all logs, the level of the logger is set to debug, and then debug and higher (which is all) are printed.

The highest level supported today is fatal, which will still print fatal logs.

**Comment by adibrastegarnia** [comment]
@prashantv 
Thanks for your response. If I set the level to Warn, based on your description, the logs at Error, DPanic, Panic and Fatal should be printed not Info and Debug correct? I set it to Warn level, I still see Info level messages are printed. Am I missing something?

**Comment by abhinav** [comment]
> Thanks for your response. If I set the level to Warn, based on your description, the logs at Error, DPanic, Panic and Fatal should be printed not messages at Info and Debug levels correct?

Correct.

> I set it to Warn level, I still see Info level messages are printed.

That should not be the case. If you're experiencing that, please file a bug report in a separate issue demonstrating how you're configuring the logger, preferably with a reproduction of the issue.
