### ISSUE TITLE
BUG: level precedence- Setting to any level higher than Info level still prints Info level 

### ISSUE THREAD

**Issue by adibrastegarnia** [uber-go/zap#781]
@prashantv 
Follow up on #780 to report a bug. 
 We are implementing a hierarchical logger using Zap in this PR. 
https://github.com/onosproject/onos-lib-go/pull/2

There is a working example in that PR which shows that after changing the level of logger to Fatal  level (or any other levels higher than Info level), logger still prints Info level. 

We have a set level function like this which assigns a new level to all children of a parent logger. 

```
// SetLevel change level of a logger and propagates the change to its children
func SetLevel(level Level, names ...string) {
	name := buildTreeName(names...)
	logger := Log{}
	loggers.ForEachPrefix(art.Key(name), func(node art.Node) bool {
		if node.Key() != nil {
			loggerNode := node.Value().(Log)
			newLevel := intToAtomicLevel(level)
			newLogger := loggerNode.stdLogger.WithOptions(
				zp.WrapCore(
					func(zc.Core) zc.Core {
						return zc.NewCore(loggerNode.encoder, loggerNode.writer, &newLevel)
					}))
			newLogger.Named(string(node.Key()))
			loggerNode.stdLogger = newLogger
			logger = Log{newLogger, loggerNode.encoder, loggerNode.writer, string(node.Key())}
			loggers.Insert(node.Key(), logger)
		}
		return true
	})
}
```

**Comment by prashantv** [comment]
Would you able to provide a minimal reproducible example that just interacts with the zap APIs, ideally without any additional abstractions. For example, I don't know what `loggers.Insert` does, where `loggers` is defined etc.

**Comment by adibrastegarnia** [comment]
@prashantv 
I will get back to you on this. I was busy so I could not to write a simple code. I will do my best to provide it by end of weekend.

**Comment by adibrastegarnia** [comment]
@prashantv 
It looks like this example works fine but I should debug my code to see what is going on.

**Comment by adibrastegarnia** [comment]
@prashantv 
It looks like the following code works fine but I should debug my code to see what is going on. 

```
atomLevel := zap.AtomicLevel{}
	atomLevel = zap.NewAtomicLevelAt(zc.ErrorLevel)
	rawJSON := []byte(`{	
	  "encoding": "json",
	  "outputPaths": ["stdout", "/tmp/logs"],
	  "errorOutputPaths": ["stderr"],
	  "initialFields": {"foo": "bar"},
	  "encoderConfig": {
	    "messageKey": "message",
	    "levelKey": "level",
	    "levelEncoder": "lowercase"
	  }
	}`)

	var cfg zap.Config
	if err := json.Unmarshal(rawJSON, &cfg); err != nil {
		panic(err)
	}
	logger, err := cfg.Build()
	if err != nil {
		panic(err)
	}
	defaultEncoder := zc.NewJSONEncoder(cfg.EncoderConfig)
	defaultWriter := zc.Lock(os.Stdout)
	newLogger := logger.WithOptions(
		zap.WrapCore(
			func(zc.Core) zc.Core {
				return zc.NewCore(defaultEncoder, defaultWriter, &atomLevel)
			}))
```

**Comment by adibrastegarnia** [comment]
Resolved.

**Comment by prashantv** [comment]
> Resolved.

Can you provide a little context on what the issue was in case others run into the same issue? Thanks

**Comment by adibrastegarnia** [comment]
The issue was on my side that I didn't the update pointer to the logger to
use the new one. I couldn't find a method to get the current level of a
logger. Is there such method available?

**Comment by prashantv** [comment]
I see, there's no method to get the current level, but there are methods to check whether a specific level is enabled for logging through the underlying `Core`,
```go
enabled := logger.Core().Enabled(level)
```
