### ISSUE TITLE
Zap logger custom writer to a server 

### ISSUE THREAD

**Issue by adibrastegarnia** [uber-go/zap#788]
I would like to know if I want to customize the writer to write the logs to a remote server for sequencing the logs. Would you please provide me some pointers about it to see how can customize the logger to achieve the goal?

**Comment by prashantv** [comment]
Yes, it is possible to customize a logger to write to a remote server (or to do anything you'd like).

Zap uses the [`WriteSyncer` interface](https://godoc.org/go.uber.org/zap/zapcore#WriteSyncer) (which is similar to `io.Writer`, but adds a `Sync() error` method) for writing logs.

You can register a [custom factory](https://godoc.org/go.uber.org/zap#RegisterSink) for creating your own `WriteSyncer` based on a URI scheme. This factory would return a custom `WriteSyncer` that you implement to write to your remote server.

**Comment by adibrastegarnia** [comment]
@prashantv 
Thanks for your quick response. I will try it.
