### ISSUE TITLE
log filename and line number - caller

### ISSUE THREAD

**Issue by adibrastegarnia** [uber-go/zap#789]
I added a caller key to our custom logger but it looks like it prints the line number in the logger file instead of printing the line number of the main file (the file that I am using the logger)

```
{"level":"INFO","ts":"2020-02-20T06:55:57.680-0800","controller":"controller","caller":"logging/logger.go:103","msg":"controller logger at INFO level (default level)"}
{"level":"WARN","ts":"2020-02-20T06:55:57.681-0800","controller/change":"controller/change","caller":"logging/logger.go:178","msg":"cclogger"}
{"level":"INFO","ts":"2020-02-20T06:55:57.681-0800","controller/change/network":"controller/change/network","caller":"logging/logger.go:103","msg":"hello"}
```

Any ideas?

**Comment by prashantv** [comment]
See [`zap.AddCallerSkip`](https://godoc.org/go.uber.org/zap#AddCallerSkip),

> AddCallerSkip increases the number of callers skipped by caller annotation (as enabled by the AddCaller option). When building wrappers around the Logger and SugaredLogger, supplying this Option prevents zap from always reporting the wrapper code as the caller.

**Comment by adibrastegarnia** [comment]
@prashantv 
Thanks for your response. Still not clear for if I add that, what skip number should be passed? I added and tried a few different skip numbers but still printing the logger line number.

**Comment by adibrastegarnia** [comment]
Figured that out

**Comment by prashantv** [comment]
Can you post what the issue was here, and whether any documentation improvements can be made to help others in future? Thanks!

**Comment by adibrastegarnia** [comment]
It was not a big issue. Since I have implemented a hierarchical logger so
sometimes I miss the required changes. Setting to level 1 works. But that
would be great to include your response somewhere in readme because
developers can easily encounter with this issue.

**Comment by kalengbekas** [comment]
hi, how do you print file and line code ? i tried the AddCaller & WithCaller(true) but nil. This is my code

```go
	encoderConfig := map[string]string{
		"levelEncoder": "lowercase",
		"levelKey":     "level",
		"timeKey":      "date",
		"timeEncoder":  "iso8601",
		"callerKey":    "caller",
		"messageKey":   "message",
	}
	
	// code
	
	core := zapcore.NewCore(
		zapcore.NewJSONEncoder(encCfg),
		w,
		zap.InfoLevel)
		
	logger := zap.New(core, zap.WithCaller(true)
```
`{"level":"info","date":"2023-05-11 09:14:40","message":"App listening on localhost:8090"}`
