### ISSUE TITLE
Interaction with a logger using CLI at runtime

### ISSUE THREAD

**Issue by adibrastegarnia** [uber-go/zap#790]
@prashantv 
First of all sorry for my lots of questions. Suppose we have a custom logger which keeps a list of loggers, change the level of a logger,  Adds a sink to a logger, etc. I am thinking that what is the best way to interact with the logger (e.g. using a CLI) to perform some actions like setting a level, or adding a sink to the logger to redirect the logs to a sink at runtime. This feature is needed to be supported for different microservices so I am wondering what is the best way to proceed for this case? Any similar use case that I can take a look and get some ideas?

**Comment by prashantv** [comment]
Similar thread: https://github.com/uber-go/zap/issues/741#issuecomment-534876254

We expose HTTP endpoints to control our logger (e.g., changing the log level).

**Comment by adibrastegarnia** [comment]
@prashantv 
Thanks for your response.
