### ISSUE TITLE
Updating level a logger without creating a new pointer

### ISSUE THREAD

**Issue by adibrastegarnia** [uber-go/zap#793]
Currently, I was trying to update the level of a logger by creating a new one an assign it to the old one but I noticed these two are pointing to different addresses and won't be useful during runtime. Like this:
```

newLogger := loggerNode.stdLogger.WithOptions(
				zp.WrapCore(
					func(zc.Core) zc.Core {
						return zc.NewCore(loggerNode.encoder, loggerNode.writer, &newLevel)
					}))
```

I am wondering is it possible to change the level of a logger without recreating a new logger? Please consider that I wrote a custom logger.

**Comment by prashantv** [comment]
You can update the level of a logger by:

1. Creating an `AtomicLevel`, hold on to the reference to the `AtomicLevel`
2. Create logger by passing in the above `AtomicLevel` as the level to the logger
3. Update the level by using using `SetLevel` on the `AtomicLevel`:
https://godoc.org/go.uber.org/zap#AtomicLevel.SetLevel

**Comment by adibrastegarnia** [comment]
@prashantv 
Thanks. Let me try it.

**Comment by adibrastegarnia** [comment]
@prashantv 
That works fine. I have the same question for the writerSyncer. during runtime, I want to change it to a sink without recreating the logger.  I did almost the same thing by updating the pointer of the writer but it doesn't work. Any suggestions?

**Comment by prashantv** [comment]
We don't have official support for a write syncer that can be changed, but since it's an interface you can build your own implementation that does allow changing the underlying `WriteSyncer`, something like:

```go
type AtomicWriteSyncer struct{
  underlying atomic.Value // WriteSyncer
}

func NewAtomicWriteSyncer(ws zapcore.WriteSyncer) zapcore.WriteSyncer {
  return &AtomicWriteSyncer{ws}
}

func (w *AtomicWriteSyncer) writeSyncer() zapcore.WriteSyncer {
  return underlying.Load().(zapcore.WriteSyncer)
}

func (w *AtomicWriteSyncer) SetWriteSyncer(new zapcore.WriteSyncer) {
  w.underlying.Store(new)
}

func (w *AtomicWriteSyncer) Write(p []byte) (int, error) {
  return w.writeSyncer().Write(p)
}

func (w *AtomicWriteSyncer) Sync() error {
  return w.writeSyncer().Sync()
}

```

You would hold the reference to the above `AtomicWriteSyncer` so you can change it dynamically.

**Comment by adibrastegarnia** [comment]
@prashantv 
Thanks for your response. I will try it out.
