### ISSUE TITLE
Incorrect time value with zap.Time() when using a time far in the future

### ISSUE THREAD

**Issue by gkotian** [uber-go/zap#803]
I'm trying to log a time value that is set to something very far in the future. It is supposedly the largest time value possible according to https://stackoverflow.com/a/25065327/793930.

I'm using the plain `Logger`, and creating the field for the log message using `zap.Time()`.
https://play.golang.org/p/Nc8jv_8NkCs

If you run the code in the playground, you'll see that `t1` is the same in both the zap log and in the `fmt.Println` print. However, `t2` is reported incorrectly in the zap log as:
```
1754-08-30T22:43:41.128Z
```

**Comment by prashantv** [comment]
This is similar to #737

I think we should do the same fix as suggested there: if a value is out-of-range for `UnixNano`, then store a different representation internally.

**Comment by abhinav** [comment]
Resolved in #804
