### ISSUE TITLE
get the json output to a variable

### ISSUE THREAD

**Issue by luxuze** [uber-go/zap#809]
I want to get the sugared log (json) to a Golang variable, and send it to log server. how to do this?

**Comment by prashantv** [comment]
You can create a custom implementation of [`WriteSyncer`](https://pkg.go.dev/go.uber.org/zap/zapcore?tab=doc#WriteSyncer), and use this to create a [`Core`](https://pkg.go.dev/go.uber.org/zap/zapcore?tab=doc#NewCore), which is then used to create a [`Logger`](https://pkg.go.dev/go.uber.org/zap?tab=doc#New).

If you want to use the existing helper methods to create a logger like `NewProduction`, then you can register a specific URI scheme (e.g., to handle something like "custom://foo" to mean log to your server) using [`RegisterSink`](https://pkg.go.dev/go.uber.org/zap?tab=doc#RegisterSink).

**Comment by luxuze** [comment]
can u give me an example to build a costumer logger with WriteSyncer & Core
<img width="696" alt="image" src="https://user-images.githubusercontent.com/35137889/82660289-aeb14980-9c5c-11ea-88af-a0e8bd54abbf.png">

**Comment by prashantv** [comment]
Please read the documentation, it also has examples that can help:
https://pkg.go.dev/go.uber.org/zap?tab=doc#example-package-AdvancedConfiguration

You can strip out the unnecessary parts from the above example and end up with something like:
```go
jsonEncoder := zapcore.NewJSONEncoder(zap.NewProductionEncoderConfig())
core := zapcore.NewCore(jsonEncoder, os.Stderr, zap.WarnLevel),
logger := zap.New(core)
```

**Comment by luxuze** [comment]
fine. Thank you~
