### ISSUE TITLE
Increasing level is reset after With

### ISSUE THREAD

**Issue by mlitvin** [uber-go/zap#810]
IncreaseLevel work by using core of type levelFilterCore. This core doesn't explicitly implement With, so it is "inherited" by the underlying core.

The result is that when calling With, it revert to the original log level

**Comment by prashantv** [comment]
Looks like we are relying on the default `With` of the underlying core as we didn't implement a specific `With` on the increase-level core. Thanks for flagging this, I'll get a fix out.
