### ISSUE TITLE
Add an Option which watches a config file

### ISSUE THREAD

**Issue by evankanderson** [uber-go/zap#811]
I'd like to add a new [`Option`](https://godoc.org/go.uber.org/zap#Option): `WatchFile(configFile string)`. `WatchFile` would open the selected file if possible and then watch the file (using inotify if possible, polling if not) and update the logger's configuration when the config file changes.

**Comment by prashantv** [comment]
This is not something we think fits in zap, but can be done outside of zap:
 - Store a logger in an atomic variable
 - Expose it via a method `Logger() zap.Logger` that reads the atomic
 - Watch the config file (e.g, using inotify), and when it changes, create a new logger, and then replace the internal variable.
