### ISSUE TITLE
Zap supporting only recent minor versions of go?

### ISSUE THREAD

**Issue by bnarang** [uber-go/zap#815]
I think zap first version was around 2017. On the readme it shows that Zap only supports recent minor versions of Go. This is somewhat confusing to me

**Comment by abhinav** [comment]
Zap follows model used by the [Go Release Policy](https://golang.org/doc/devel/release.html#policy). We support the two most recent minor versions (as defined by semver) of Go. As of right now, that's Go 1.13.x and Go 1.14.x. Zap is not guaranteed to work on any release of Go older than that. Hope that answered your question.
