### ISSUE TITLE
Add FilterFieldKey method to observer in zaptest

### ISSUE THREAD

**Issue by migueLoureiro** [uber-go/zap#816]
As a suggestion, adding filter by field key, regardless of the field value, to the observer of zaptest, would allow for testing wether the fields exist regardless of their value.

I leave here the code snipet for github.com/uber-go/zap/zaptest/observer/observer.go

```
// FilterFieldKey filters entries to those that have the specified field key regardless of its value.
func (o *ObservedLogs) FilterFieldKey(key string) *ObservedLogs {
	return o.filter(func(e LoggedEntry) bool {
		for _, ctxField := range e.Context {
			if ctxField.Key == key {
				return true
			}
		}
		return false
	})
}
```

**Comment by abhinav** [comment]
This is a good idea.
We'll be happy to accept a PR implementing this solution.
Thanks!
