### ISSUE TITLE
zap logging for dumpRequest & dumpResponse

### ISSUE THREAD

**Issue by chandresh-pancholi** [uber-go/zap#818]
Hi, 

I have been trying to log the request/response of each request using zap. Unfortunately, zap treats is a string.

Is there a clean way to log the request/response using zap?

**Comment by prashantv** [comment]
Zap does not contain any helpers to log HTTP request/responses, but this is something that can be done outside of zap. I would recommend a custom type that implements the [`ObjectMarshaler`](https://pkg.go.dev/go.uber.org/zap/zapcore?tab=doc#ObjectMarshaler) interface.

E.g.,
```
type LoggableRequest http.Request

func (lr *LoggableRequest) MarshalLogObject(enc zapcore.ObjectEncoder) error {
  r := (*http.Request)(lr)
 enc.AddString("method", r.Method) 
 enc.AddString("url", r.URL) 
 [...]
}
```

The method would look similar to `DumpRequest` but would need to be specific to zap to encode all the fields.

Closing as this is something that can be done outside of zap.
