### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by JeffreyBool** [uber-go/zap#824]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x14f3594]

goroutine 598 [running]:
go.uber.org/zap.(*Logger).check(0x0, 0x2, 0x1aec5ce, 0x11, 0xc00173ae80)
	/Users/zhanggaoyuan/go/pkg/mod/go.uber.org/zap@v1.15.0/logger.go:263 +0xcc4
go.uber.org/zap.(*Logger).Error(0x0, 0x1aec5ce, 0x11, 0xc00173ae80, 0x2, 0x2)
	/Users/zhanggaoyuan/go/pkg/mod/go.uber.org/zap@v1.15.0/logger.go:202 +0x56
```

![image](https://user-images.githubusercontent.com/24415888/80575519-4e046780-8a36-11ea-84d3-157d6b4ce215.png)

What are the causes？

**Comment by blampe** [comment]
Hi Jeffrey, can you please include a code snippet (not a screenshot) with more detail? Things like how you're initializing your logger and other variables, their values, etc.

**Comment by JeffreyBool** [comment]
https://github.com/golearnku/sdk-zap------------------ 原始邮件 ------------------
发件人: "Bryce Lampe"<notifications@github.com>
发送时间: 2020年4月29日(星期三) 晚上11:11
收件人: "uber-go/zap"<zap@noreply.github.com>;
抄送: "JeffreyBool"<1402992668@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [uber-go/zap] panic: runtime error: invalid memory address or nilpointer dereference (#824)




 
Hi Jeffrey, can you please include a code snippet (not a screenshot) with more detail? Things like how you're initializing your logger and other variables, their values, etc.
 
&mdash;

**Comment by abhinav** [comment]
Hey, @JeffreyBool sorry, we can't dig into that project.

Can you share how you are setting up the Zap logger? Specifically, how
are you calling `zap.New` or `zap.Configuration.Build`?

Panics on the line you've indicated can only happen when the
`*zap.Logger` is nil, or if it doesn't have a Core configured.

**Comment by JeffreyBool** [comment]
```go
func NewProductionConfig(filename string) zap.Config {
	encoderConfig := zap.NewProductionEncoderConfig()
	encoderConfig.EncodeTime = encodeTime
	encoderConfig.EncodeDuration = zapcore.StringDurationEncoder
	return zap.Config{
		Development:       false,
		DisableCaller:     true,
		DisableStacktrace: false,
		Level:             zap.NewAtomicLevelAt(zapcore.InfoLevel),
		Encoding:          "json",
		EncoderConfig:     encoderConfig,
		OutputPaths:       []string{"stdout", filepath.Join(ii.opts.path, filename) + ".out.log"},
		ErrorOutputPaths:  []string{"stderr", filepath.Join(ii.opts.path, filename) + ".error.log"},
	}
}

func NewDevelopmentConfig(filename string) zap.Config {
	encoderConfig := zap.NewDevelopmentEncoderConfig()
	encoderConfig.EncodeTime = encodeTime
	return zap.Config{
		Development:       true,
		DisableCaller:     true,
		DisableStacktrace: true,
		Level:             zap.NewAtomicLevelAt(zapcore.DebugLevel),
		Encoding:          "json",
		EncoderConfig:     encoderConfig,
		OutputPaths:       []string{"stdout", filepath.Join(ii.opts.path, filename) + ".out.log"},
		ErrorOutputPaths:  []string{"stderr", filepath.Join(ii.opts.path, filename) + ".error.log"},
	}
}
```

```go
// New is similar to Config.Build except that info and error logs are separated
// only json/console encoder is supported (zap doesn't provide a way to refer to other encoders)
func NewLogger(cfg zap.Config) (logger *zap.Logger, err error) {
	sink, errSink, err := openSinks(cfg)
	if err != nil {
		return
	}

	var encoder zapcore.Encoder
	switch cfg.Encoding {
	case "json":
		encoder = zapcore.NewJSONEncoder(cfg.EncoderConfig)
	case "console":
		encoder = zapcore.NewConsoleEncoder(cfg.EncoderConfig)
	default:
		err = errEncodingNotSupported
		return
	}

	logLevel := cfg.Level.Level()
	stdoutPriority := zap.LevelEnablerFunc(func(lvl zapcore.Level) bool {
		return lvl >= logLevel && lvl < zapcore.ErrorLevel
	})
	stderrPriority := zap.LevelEnablerFunc(func(lvl zapcore.Level) bool {
		return lvl >= zapcore.ErrorLevel
	})

	core := zapcore.NewTee(
		zapcore.NewCore(encoder, sink, stdoutPriority),
		zapcore.NewCore(encoder, errSink, stderrPriority),
	)

	return zap.New(core, buildOptions(cfg, errSink)...), nil
}

func openSinks(cfg zap.Config) (zapcore.WriteSyncer, zapcore.WriteSyncer, error) {
	sink, closeOut, err := zap.Open(cfg.OutputPaths...)
	if err != nil {
		return nil, nil, err
	}
	errSink, _, err := zap.Open(cfg.ErrorOutputPaths...)
	if err != nil {
		closeOut()
		return nil, nil, err
	}
	return sink, errSink, nil
}

func buildOptions(cfg zap.Config, errSink zapcore.WriteSyncer) []zap.Option {
	opts := []zap.Option{zap.ErrorOutput(errSink)}

	if cfg.Development {
		opts = append(opts, zap.Development())
	}

	if cfg.DisableCaller {
		opts = append(opts, zap.AddCaller())
	}

	stackLevel := zap.ErrorLevel
	if cfg.Development {
		stackLevel = zap.WarnLevel
	}

	if cfg.DisableStacktrace {
		opts = append(opts, zap.AddStacktrace(stackLevel))
	}

	if cfg.Sampling != nil {
		opts = append(opts, zap.WrapCore(func(core zapcore.Core) zapcore.Core {
			return zapcore.NewSampler(core, time.Second, cfg.Sampling.Initial, cfg.Sampling.Thereafter)
		}))
	}

	if len(cfg.InitialFields) > 0 {
		fs := make([]zap.Field, 0, len(cfg.InitialFields))
		keys := make([]string, 0, len(cfg.InitialFields))
		for k := range cfg.InitialFields {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			fs = append(fs, zap.Any(k, cfg.InitialFields[k]))
		}
		opts = append(opts, zap.Fields(fs...))
	}

	return opts
}
```

**Comment by xiegeo** [comment]
I am also trying to get around the same panic. It is falling locally but passing in CI. 🤷‍♂️

**Comment by prashantv** [comment]
The panic indicates that the logger is `nil`:
```
go.uber.org/zap.(*Logger).check(0x0, 0x2, 0x1aec5ce, 0x11, 0xc00173ae80)
```

The first argument (`0x0`) is the `*Logger` and 0x0 is `nil`. This means that the logger is not being passed around properly, it doesn't indicate an issue with zap.

If you have a code snippet that reproduces the problem and shows a zap problem, we can investigate, but there's no code to run that reproduces the issue. If possible, please link to a snippet on the [Go Playground](https://play.golang.org/) that runs and panics.

**Comment by prashantv** [comment]
Closing due to lack of a reprp, and lack of activity.

**Comment by freakmaxi** [comment]
I also have this problem. After some analysis on the zap code, I realize that logger is cloned in logger.go file line 163. However, this cloning is happening only on logger structure but not in its inner structures who are already pointers. So because of that,  reason, you are only cloning the pointer address for the inner structure but not cloning the actual structure underlying. 

In the end, you are using the same core to assign to the new structure with some fields for sugar usage. 
logger.go file line 164 `l.core = l.core.With(fields)`

in core.go file line 73, you are cloning the core to a new variable and returning it. this "return" is assigning the newly created core to the cloned structure core variable. This core variable was holding the old core pointer address but now it is dereferenced. You may think that it is already part of the cloned structure. But actually it is not and dereferenced structure is in the memory kicking around. So the old structure holding the address of the ghost memory (currently holding the abonded core structure) and as long as this part of the memory is not written, it continues to work and when that part of the memory is changed, first structure core variable turn to broken byte order for the structure and it is creating invalid memory address exception after some time. 

It is happening when you use the logger with sugar function together along with the structured logger. 

For now, I'm running the service without using Sugar function anywhere and the system has not crashed yet. When I'm sure this is the real problem causing an invalid memory address exception, I'll create a pull request for the fix.

**Comment by JeffreyBool** [comment]
```go
// NewLogger New is similar to Config.Build except that info and error logs are separated
// only json/console encoder is supported (zap doesn't provide a way to refer to other encoders)
func NewLogger(cfg zap.Config) (logger *zap.Logger, err error) {
	sink, errSink, err := openSinks(cfg)
	if err != nil {
		return
	}

	var encoder zapcore.Encoder
	switch cfg.Encoding {
	case "json":
		encoder = zapcore.NewJSONEncoder(cfg.EncoderConfig)
	case "console":
		encoder = zapcore.NewConsoleEncoder(cfg.EncoderConfig)
	default:
		err = errEncodingNotSupported
		return
	}

	logLevel := cfg.Level.Level()
	stdoutPriority := zap.LevelEnablerFunc(func(lvl zapcore.Level) bool {
		return lvl >= logLevel && lvl < zapcore.ErrorLevel
	})
	stderrPriority := zap.LevelEnablerFunc(func(lvl zapcore.Level) bool {
		return lvl >= zapcore.ErrorLevel
	})

	core := zapcore.NewTee(
		zapcore.NewCore(encoder, sink, stdoutPriority),
		zapcore.NewCore(encoder, errSink, stderrPriority),
	)

	return zap.New(core, buildOptions(cfg, errSink)...), nil
}
```
