### ISSUE TITLE
How to enable only error/warning/info logs  during runtime ?

### ISSUE THREAD

**Issue by mjmanav4** [uber-go/zap#830]
Use case : If a servcie is having high tps, then i would only like to enable error logs to reduce time spent in logging . 
Is it possible to enable/disbale during runtime

**Comment by prashantv** [comment]
You can change log levels dynamically

See previous answer on this https://github.com/uber-go/zap/issues/793#issuecomment-592110758

The `AtomicLevel` is also a HTTP handler that can be registered which provides a way of changing the log level via HTTP.
