### ISSUE TITLE
Feature Request: Dynamic Encoder

### ISSUE THREAD

**Issue by rustysys-dev** [uber-go/zap#831]
Although potentially a smaller usecase, right now you can only register (to my knowlege) a single set of field configurations per encoder.  You cannot for instance use one set of fields per log level using a single encoder.  

I know you can use a Tee to use multiple encoders,  But then I cannot see how you can use AtomicLevels. 

Say I have the following field sets:

```json
{
  "level": "info", 
  "time": "1234567890",
  "ref_id": "xxxxxxxxxx", 
  "msg": "my message"
}
```

```error
{ 
  "level": "error", 
  "time": "1234567890", 
  "caller": "xxxxxxx",
  "stack": "xxxxxxx",
  "msg": "my message"
}
```

and you want to be able to dynamically switch between them using the `ServeHTTP` method of the `AtomicLevel` struct. 

I feel like there should be an easy way to set fields on an encoder based on the current log level... maybe I am missing something?

**Comment by prashantv** [comment]
Is the request specifically to configure the caller and stack fields based on the level?

The `stack` field can be configured by level already:
https://pkg.go.dev/go.uber.org/zap?tab=doc#AddStacktrace

The `caller` field does not have the same configuration though, is the request to support the same for caller?

**Comment by rustysys-dev** [comment]
@prashantv Thank you for your reply, I am ridiculously late in getting back to you.. sorry..

that being said, my original meaning was not just for a single field, but for any field/custom field.

for example when creating a new logger you add fields to it directly as a global field.

```golang

logr := zap.New(
        zapcore.NewCore(
                zapcore.NewJSONEncoder(
                        zap.NewProductionEncoderConfig()
                ),
                zapcore.Lock(os.Stdout),
                zap.NewAtomicLevelAt(zap.InfoLevel),
        ),
        zap.fields(
                zapcore.Field{
                        Key: "myfield",
                        Type: zapcore.StringType,
                        String: "mystring",
                },
        ),
        zap.AddCaller(),
)
```

So yes, as you deduced it is a request for adding similar functionality for caller, but also for any `zapcore.Field{}` on a per level basis.

Let me know if you have any more questions.. I will try to answer them quickly this time. :sob:

**Comment by prashantv** [comment]
It's not possible to do this with globally added fields, since zap encodes fields as soon as they are added to a logger. The log level is not known till later, so the field has already been encoded by then.

However, this can be done by maintaining different loggers,
```
baseLogger := zap.New(...)

debugLogger := baseLogger.With(zap.String(...))
```

Use the `debugLogger` when you want the additional fields, or `baseLogger` otherwise. You could even create a single service-specific logger type that will wrap the underlying loggers, using the appropriate logger based on the level being logged.

**Comment by rustysys-dev** [comment]
Thank you @prashantv This seems sufficient for my usecase, and I don't see the merit in changing anything anymore.  Closing issue.
