### ISSUE TITLE
MarshalLogObject is not respected when nested

### ISSUE THREAD

**Issue by sethvargo** [uber-go/zap#836]
Given the following:

```go
type A struct {
  Name string
}

func (a *A) MarshalLogObject(enc zapcore.ObjectEncoder) error {
  return enc.AddString("name", "nope")
}

type B struct {
  A A
}

b := &B{A: A{Name: "foobar"}}
logger.With("b", b).Info("did a thing")
```

This will print the value of A's name as "foobar" instead of "nope". It appears that the interface check is not applied to nested structs. Is this by design?

**Comment by sethvargo** [comment]
While this is a contrived example, the docs note "selectively omit information which shouldn't be included in logs (e.g., passwords).", and that's the actual use case here:

```go
type DatabaseConfig struct {
  // other fields
  Password string
}

type AppConfig struct {
  Database Database

  // other fields
}
```

We'd like to log the application's config at startup, but doing so currently logs the database password, despite the Database struct defining a `MarshalLogObject` function.

**Comment by tylitianrui** [comment]
struct B dont implements the interface  `ObjectMarshaler`

**Comment by sethvargo** [comment]
Correct, so it defaults to the reflect-based marshaller. However, when reflecting, A _does_ implement `ObjectMarshler` and that should be used instead of generic reflection.

**Comment by prashantv** [comment]
Zap looks at the top-level object to determine whether it should:
 - Use a reflection based approach that is encoder specific
 - Use the `MarshalLogObject`

There's not support for mixing a top-level object encoded with reflection that then has fields that want `MarshalLogObject` to be used, as the encoders rely on existing struct encoders like `json.Marshal` and `yaml.Marshal`.

To solve your problem, you'll either need to:
 - Use a custom tag for the underying encoder to skip that field (E.g., `json:""` struct tag)
 - Or implement `MarshalLogObject` on the the top-level struct

**Comment by sethvargo** [comment]
> Use a custom tag for the underying encoder to skip that field (E.g., json:"" struct tag)

This is what we've done for now.

> Or implement MarshalLogObject on the the top-level struct

This isn't really feasible when that struct is included in 100+ other structs.

At the very least, I believe this should be documented somewhere. It was very shocking to me that implementing the interface is only applicable on an embedded struct.

**Comment by tylitianrui** [comment]
@sethvargo It was shocking to me too when  i  encountered   the  same  problem.

**Comment by prashantv** [comment]
I've added documentation to make this clearer, please take a look to see there's anything else that the documentation should mention.

**Comment by killwing** [comment]
i encountered the same problem.

> Use a custom tag for the underying encoder to skip that field (E.g., json:"" struct tag)

This isn't really feasible when that struct needs to be serialized.

> Or implement MarshalLogObject on the the top-level struct

This isn't really feasible when that struct is included in 100+ other structs.

**Comment by prashantv** [comment]
Unfortunately it's not possible to plug a custom log marshal function to be invoked when using the standard library's JSON marshaller. Custom-building our own reflect-based JSON marshaller to support `MarshalLogObject` would be a lot of additional code and complexity in zap, which I think should be avoided.
