### ISSUE TITLE
Performance hit with adding caller (Question)

### ISSUE THREAD

**Issue by MohitKS5** [uber-go/zap#847]
whats the performance hit on adding caller info on log using encoding config's callerKey ? I am using a non-sugarred logger. But if adding caller info takes the performance back to that sugarred logger there is no point.

**Comment by prashantv** [comment]
The performance impact depends on the specific configuration you use (E.g., which encoder you have), so we recommend that users benchmark the specific scenarios they care about. It also changes based on the Go version, so we can't give you an exact number.

Getting caller information typically does allocate, so it will definitely have some impact. For guidance on how to profile, there's existing resources such as this [blog post](https://jvns.ca/blog/2017/09/24/profiling-go-with-pprof/) or a [talk I've given]( or a talk I've given in the past.) in the past.
