### ISSUE TITLE
Custom object guide?

### ISSUE THREAD

**Issue by tgsmith61591** [uber-go/zap#848]
I'm sorry if this has been asked before, but is there any way/a guide to creating a custom object I can log with zap? This is a crude example, but it illustrates the idea:

```golang
type Foo struct {
        bar Bar
}

func (f Foo) doBaz(ctx context.Context) Baz {
        log := Log(ctx).With("funcName", "doBaz")
        log.Info("Doing baz", zap.Foo("fooObj", f))
}
```

Obviously, `zap.Foo` is not a thing. But would it be as simple as implementing some interface so that something like

```golang
        log.Info("Doing baz", internal.Foo("fooObj", f))
```

would be valid? Hope this makes sense.

**Comment by tgsmith61591** [comment]
Digging into it a bit more, the face that [the `Field` object](https://github.com/uber-go/zap/blob/master/zapcore/field.go#L100) is a struct and not an interface does not give me much hope that this can be accomplished, since it appear it will [panic](https://github.com/uber-go/zap/blob/master/zapcore/field.go#L174)

**Comment by blampe** [comment]
Hi @tgsmith61591, would implementing [ObjectMarshaler](https://godoc.org/go.uber.org/zap/zapcore#ObjectMarshaler) do what you need?

**Comment by abhinav** [comment]
What @blampe stated is correct. `Foo` needs to implement `ObjectMarshaler` to be logged as an object with [`zap.Object`](https://pkg.go.dev/go.uber.org/zap?tab=doc#Object).

Inside the MarshalLogObject, use the [ObjectEncoder](https://pkg.go.dev/go.uber.org/zap/zapcore?tab=doc#ObjectEncoder) to add individual fields to the object.

```
type Foo struct {
  name string
  bar  Bar
}

func (f Foo) MarshalLogObject(enc zapcore.ObjectEncoder) error {
  enc.AddString("name", f.name)
  
  // Assuming bar is an object:
  if err := enc.AddObject("bar", f.bar); err != nil {
    return err
  }
}
```
