### ISSUE TITLE
Any schedule for next release tag

### ISSUE THREAD

**Issue by lixingwang** [uber-go/zap#849]
Just want to check when will be the next release tag for zap?   I want to have an official release tag to bundle zap into our project to have recent changes in.

**Comment by prashantv** [comment]
We have a few other pending changes (https://github.com/uber-go/zap/pulls) so we'll cut a release once those land, hopefully in the next week or two.

**Comment by lixingwang** [comment]
Thanks @prashantv

**Comment by lixingwang** [comment]
@prashantv  Any release tag schedule in the coming days/week?

**Comment by prashantv** [comment]
Sorry for the delay, we had a few changes that we wanted to try and get in. We are planning on the release today.

**Comment by lixingwang** [comment]
Thanks for the update. sounds great.

**Comment by prashantv** [comment]
[1.16.0](https://github.com/uber-go/zap/releases/tag/v1.16.0) has been released with all the latest changes.
