### ISSUE TITLE
Why SugaredLogger is faster than StructuredLogger?

### ISSUE THREAD

**Issue by rezakamalifard** [uber-go/zap#850]
From package documentation 
> In contexts where performance is nice, but not critical, use the SugaredLogger. 

I created a [simple project](https://github.com/rezakamalifard/TestLoggingWithZap/tree/master) to benchmark Zap to help us choose between two logger options, we wanted to see how performance is affected with the SugeredLogger but surprisingly found out that it is faster than StructuredLogger contrary to what the benchmark in the documentation states.

Why is this happening?

**Comment by prashantv** [comment]
Your test is using a default configuration which has a sampler, which drops logs above a certain amount.

In the case of the sugar logger, the fields are not converted to `zap.Field` unless they are actually logged, and when all your logs are dropped, it seems like this has a small performance benefit.

If you turn off sampling, the results are more similar to what's shown in the documentation.

**Comment by rezakamalifard** [comment]
Thanks for your reply. I think it's a very good idea to add more details about preset configs. I couldn't find anything about the sampler thing in the package documentation.

**Comment by prashantv** [comment]
The documentation could definitely be expanded a little, right now it's hidden under 
https://pkg.go.dev/go.uber.org/zap?tab=doc#NewProductionConfig

> It uses a JSON encoder, writes to standard error, and **enables sampling**. Stacktraces are automatically included on logs of ErrorLevel and above.

It's very easy to miss, and I think a few people have been surprised by this. The documentation for `NewProduction` should also mention sampling, and maybe more explicitly.

**Comment by rezakamalifard** [comment]
I'm going to add more details about sampling to this part of the documentation and send you a PR.

I've added other types of loggers to my benchmark project, and surprisingly, when I disable sampling and write the log result into stderr, the sugared logger is faster than the structured logger. You check my code and results here: https://github.com/rezakamalifard/BenchmarkZapLoggers
Is it because I'm benchmarking the io, or there's any other reason for that?
