### ISSUE TITLE
Unexpected memory usage

### ISSUE THREAD

**Issue by wyxloading** [uber-go/zap#851]
Here cloned a `jsonEncoder` (which actually get from `_jsonPool`), but never put back to `_jsonPool` after use.  

https://github.com/uber-go/zap/blob/53a387079b46cce51bbb6d360d9c57f86977addb/zapcore/console_encoder.go#L131-L145

Perhaps we need something like below to decrease memory allocations.

```go
context := c.jsonEncoder.Clone().(*jsonEncoder) 
defer func() {
    context.buf.Free()
    putJSONEncoder(context)
}
```

**Comment by prashantv** [comment]
From a quick glance, this seems reasonable. Can you send a PR, and ensure the race detector doesn't find any issues once the above change is made. Thanks!

**Comment by wyxloading** [comment]
I would like to send PR for this (FYI, PR link #852)

**Comment by abhinav** [comment]
#852 was merged so we can resolve this.
