### ISSUE TITLE
[Question] Is it possible to ignore nils?

### ISSUE THREAD

**Issue by Jleagle** [uber-go/zap#856]
I am moving from a different logging library where log.Error(nil) would not output anything.
Is there anyway i can replicate this behaviour with Zap?
Meaning I don't have to add `if err != nil {` around thousands of log calls.

Thanks.

**Comment by prashantv** [comment]
If I understand correctly, you want to use the Sugar logger, and you want to do `Error(nil)` using this method:
https://pkg.go.dev/go.uber.org/zap?tab=doc#SugaredLogger.Error

And in that case, the log should be skipped?

**Comment by Jleagle** [comment]
Correct. Mostly just curious to see if it's possible using some kind of hook/intercept. Thanks.

**Comment by prashantv** [comment]
It's non-trivial but possible: You would need to implement a custom `Core` wrapper that would check the message, and drop it if it was a specific value.

You have access to the message in the `Check` method, and if you don't want to log, you would just not call the underlying core's Check.  You can use the sampling core as an example,
https://github.com/uber-go/zap/blob/v1.15.0/zapcore/sampler.go

When the same message has been logged too many times, it doesn't call the underlying core and just returns the passed-in `*CheckedEntry`.

**Comment by Jleagle** [comment]
Thanks!
