### ISSUE TITLE
Fix logrus dependency

### ISSUE THREAD

**Issue by alexppg** [uber-go/zap#858]
When using the function `zap.NewDevelopment()` it requires the `docker` package, which requires `logrus` package. There's some problem because of how logrus did manage the case sensitiveness. The error I get is:

> go: finding module for package github.com/docker/docker/daemon/logger
go: found github.com/docker/docker/daemon/logger in github.com/docker/docker v1.13.1
go: finding module for package github.com/Sirupsen/logrus
go: found github.com/Sirupsen/logrus in github.com/Sirupsen/logrus v1.6.0
go: gitlab.com/drymerisnothere/antisocial/internal/fediverse imports
	gitlab.com/drymerisnothere/antisocial/internal/database imports
	github.com/docker/docker/daemon/logger imports
	github.com/Sirupsen/logrus: github.com/Sirupsen/logrus@v1.6.0: parsing go.mod:
	module declares its path as: github.com/sirupsen/logrus
	        but was required as: github.com/Sirupsen/logrus

The devs from logrus say, from it's README:

> Seeing weird case-sensitive problems? It's in the past been possible to import Logrus as both upper- and lower-case. Due to the Go package environment, this caused issues in the community and we needed a standard. Some environments experienced problems with the upper-case variant, so the lower-case was decided. Everything using logrus will need to use the lower-case: github.com/sirupsen/logrus. Any package that isn't, should be changed.

It seems that this is changed in the `docker` package, as far as I can see in [here](https://github.com/moby/moby/blob/4e9cffae051a85e045d72f1fc048846edfb31db4/daemon/graphdriver/lcow/lcow.go). I guess the problem is zap is requiring an older version of the docker package, the 1.13. It's now over 1.19, so I guess that upgrading it would solve the problem.

**Comment by alexppg** [comment]
It seems that manually executing the next fixes the issue:
`go get -u -v github.com/docker/docker@v18.09.6`

**Comment by abhinav** [comment]
Hello! Sorry, there may be some confusion here. Zap does not have a direct or
indirect dependency on docker or moby, and using `zap.NewDevelopment` doesn't
change that. A different system you are using may be adding that dependency.

With Go modules, you can use `go mod why` to find out why you have that
dependency:

  $ go mod why github.com/docker/docker/daemon/logger

Closing because Zap doesn't have this dependency.

**Comment by alexppg** [comment]
My bad, thanks for pointing that.
