### ISSUE TITLE
New fields on console encoder are output in JSON

### ISSUE THREAD

**Issue by michelaquino** [uber-go/zap#869]
Hi there,

I'm creating a config that uses `Encoding: "console"` and adding an extra field when logging the message, but this extra field is logging in JSON format, like the example below.

For example, this code:
```
l.Info("message", []zapcore.Field{zap.String("extra_field", "value")}...)
```

produces this message:
`2020-10-20T18:48:37.862-0300    INFO    some_pkg/pkg.go:10  message        {"extra_field": "value"}`

Why is this happening? There is some config that I must set or this is the expected behavior?
Thanks

**Comment by prashantv** [comment]
This is intended behaviour, see the [docs](https://godoc.org/go.uber.org/zap/zapcore#NewConsoleEncoder),
> It serializes the core log entry data (message, level, timestamp, etc.) in a plain-text format and leaves the **structured context as JSON**.

**Comment by michelaquino** [comment]
Thank you!

**Comment by sid-ihycq** [comment]
@prashantv this behavior seems to be inconsistent with the intention of console encoder and we cannot change it manually

**Comment by abhinav** [comment]
@sid-ihycq This is something we're reconsidering in #1076
