### ISSUE TITLE
Setting OutputPaths: []string{"stdout"} does not send logs to stdout

### ISSUE THREAD

**Issue by noahtseng** [uber-go/zap#873]
Hi, I'm having some issues with setting OutputPaths as stdout. When I do so, logs do not get sent to stdout. I may be misunderstanding how OutputPaths works, but the description is:
```
OutputPaths is a list of URLs or file paths to write logging output to.
See Open for details.
```

How to reproduce:
```
config := zap.Config{
	Level:       zap.NewAtomicLevelAt(zap.InfoLevel),
	Development: false,
	Sampling: &zap.SamplingConfig{
		Initial:    100,
		Thereafter: 100,
	},
	Encoding:         "json",
	EncoderConfig:    zap.NewProductionEncoderConfig(),
	OutputPaths:      []string{"stdout"},
	ErrorOutputPaths: []string{"stderr"},
}
logger, e := config.Build()
if e != nil {
	panic(e)
}
logger.Info("This does not get logged.")
```

This may be related. I was also wondering why for all the configurations the OutputPath is stderr? It makes sense for all the configurations to have ErrorOutputPath to be stderr, but why don't we set the OutputPath to stdout?

Many thanks in advance!

**Comment by prashantv** [comment]
The code you provided *does* log to stdout,
```
> cat log-test.go
package main

import "go.uber.org/zap"

func main() {

        config := zap.Config{
                Level:       zap.NewAtomicLevelAt(zap.InfoLevel),
                Development: false,
                Sampling: &zap.SamplingConfig{
                        Initial:    100,
                        Thereafter: 100,
                },
                Encoding:         "json",
                EncoderConfig:    zap.NewProductionEncoderConfig(),
                OutputPaths:      []string{"stdout"},
                ErrorOutputPaths: []string{"stderr"},
        }
        logger, e := config.Build()
        if e != nil {
                panic(e)
        }
        logger.Info("This does not get logged.")
}
> go run log-test.go 2>/dev/null
{"level":"info","ts":1604706003.3037868,"caller":"tmp/log-test.go:23","msg":"This does not get logged."}
```

The `2>/dev/null` sends stderr to /dev/null so only stdout is shown.

**Comment by noahtseng** [comment]
Thanks for the response Prashant. 

Would you mind explaining why for all the configurations the OutputPath is stderr? It makes sense for all the configurations to have ErrorOutputPath to be stderr, but why don't we set the OutputPath to stdout?

**Comment by prashantv** [comment]
I don't have a good reason for that actually, I think it might just be to align with the go library's log package [which defaults to stderr](https://golang.org/src/log/log.go?s=3306:3345#L76). cc @abhinav in case he has more context.

Internally, we do use stdout for output as well.

Unfortunately we can't change this now as it would affect backwards compatibility.
