### ISSUE TITLE
Option `zap.OnFatal(zapcore.WriteThenNoop)` does not take effect.

### ISSUE THREAD

**Issue by xvrzhao** [uber-go/zap#879]
I want to customize my logger instance with no os.Exit when call Fatal method, and here is my code:

```go
logger := zap.New(core, zap.AddCaller(), zap.AddCallerSkip(1), zap.IncreaseLevel(level), zap.OnFatal(zapcore.WriteThenNoop))
```
But, the option `zap.OnFatal(zapcore.WriteThenNoop)` did not take effect.

When I dive into the code, I found the snippet in `logger.go:283`

```go
	case zapcore.FatalLevel:
		onFatal := log.onFatal
		// Noop is the default value for CheckWriteAction, and it leads to
		// continued execution after a Fatal which is unexpected.
		if onFatal == zapcore.WriteThenNoop {
			onFatal = zapcore.WriteThenFatal
		}
		ce = ce.Should(ent, onFatal)
```

In my program, when a panic is recovered, I just want the output level is FATAL and do not want exiting my program. Why design like this?

**Comment by prashantv** [comment]
logger.{Fatal,Panic} are expected to stop execution. Example:
```go
resp, err := http.Get(...)
if err != nil {
  logger.Fatal(err)
}

defer resp.Body.Close()
```

This example code expects that `if err != nil`, the `Fatal` call will cause the execution to stop (similar to a return). This code is similar to many uses of `Fatal` where there's an expectation that execution does not continue after `logger.Fatal` or `logger.Panic`. Using no-op would break this reasonable assumption, so we don't allow no-op as an option for `OnFatal`. This is not something we'll change in zap.

You can choose to `WriteThenPanic`, and then use `defer` to recover from the panic instead. If you really want to write a log level of `FATAL` without stopping execution in anyway, you can get the core (`logger.Core()`) and use that to write an entry directly.
