### ISSUE TITLE
The string type does not automatically add spaces.

### ISSUE THREAD

**Issue by FH0** [uber-go/zap#889]
```go
a := "a"
zap.S().Debug(a, a)
fmt.Println(a, a)
```

zap will print "aa"
fmt will print "a a"

**Comment by johnaoss** [comment]
@FH0 The [SugaredLogger.Debug documentation states](https://pkg.go.dev/go.uber.org/zap#SugaredLogger.Debug) that `Debug` uses `fmt.Sprint` internally for creating strings. 

The behaviour of [fmt.Sprint](https://golang.org/pkg/fmt/#Sprint) is:
> Sprint formats using the default formats for its operands and returns the resulting string. **Spaces are added between operands when neither is a string**.

Whereas you show [fmt.Println](https://golang.org/pkg/fmt/#Println) which says:
> Println formats using the default formats for its operands and writes to standard output. **Spaces are always added between operands** and a newline is appended. It returns the number of bytes written and any write error encountered.

**Comment by FH0** [comment]
There may be people like me who would choose another log library for this issue.
