### ISSUE TITLE
Send logs to external URI without blocking

### ISSUE THREAD

**Issue by akaNightmare** [uber-go/zap#891]
Hello,

Is it possible to somehow send logs to a specific URL (for example, Loggly)? As far as I understand, I can add WriteSyncer and send logs in the Write method, also will make an HTTP request in Write method block the thread?

Thanks

**Comment by prashantv** [comment]
Your custom `Write` method can make the HTTP request asynchronously (e.g., create a goroutine to make the HTTP request, or using a channel to communicate with a long-running background goroutine which does the HTTP call).

Please note the requirements of `Write` as [documented in `io.Writer`](https://pkg.go.dev/io#Writer):
> Write must not modify the slice data, even temporarily.
>
> Implementations must not retain p.

A custom `Write` method that wants to make a HTTP request with the message asynchronously must /copy/ the bytes, as it cannot retain `p` as documented.

**Comment by akaNightmare** [comment]
@prashantv thanks for the explanation. However, if I want to send logs to Loggly in a batch (100-500 logs per 1 HTTP call) I have to store all of those []byte in some storage([][]byte), and what exactly I should return as `n` param (`Write(p []byte) (n int, err error)`)?

**Comment by prashantv** [comment]
From zap's perspective, the `Write` method only copies the bytes into some in-memory batch, and then it's done, so the return will indicate whether the copy succeeded. Assuming you just append the bytes to some in-memory batch, then it can't fail so can `return len(p), nil`.

You will need to separately monitor for errors on the HTTP calls, as zap will not see these errors.
