### ISSUE TITLE
The log rotation package lumberjack.v2 will deeply decrease zap efficiency

### ISSUE THREAD

**Issue by ShanQincheng** [uber-go/zap#892]
I followed the Zap FAQ , Usage section, and integrate _gopkg.in/natefinch/lumberjack.v2_ with Zap to achieve rotation function.
After that, I realized that _lumberjack_ will extremely slow performance of logging. 

Here are my PPROF results.

With _lumberjack_
![with_lumberjack](https://user-images.githubusercontent.com/20834526/102448590-71cff880-406d-11eb-97a0-ad297f744f7f.png)

Remove _lumberjack_
![without_lumberjack](https://user-images.githubusercontent.com/20834526/102448617-7f857e00-406d-11eb-9938-cf4359a43e60.png)

**Comment by phuslu** [comment]
for low latency app, lumberjack(and zap) is not good choice. You're better look for a ringbuffer logger.  zerolog + diode is not the best, but you could give a try first.

**Comment by ShanQincheng** [comment]
Sorry, it's my problem. There are some slight differences in performance when using lumberjack or not.
