### ISSUE TITLE
Static analysis tool for detecting sugared errors

### ISSUE THREAD

**Issue by sethvargo** [uber-go/zap#899]
Hey there. I wrote a static analyzer that detects common errors with sugared "With" fields (incomplete KV pairs, non-string keys) at https://github.com/sethvargo/zapw.

There's quite a lot of open and closed issues around the topic, so I figured I'd bring it to your attention in case you want to link or note it somewhere. If not, no problem. Have a great day.

**Comment by abhinav** [comment]
Hello! This looks great and yes, we would be happy to list it under the [FAQ](https://github.com/uber-go/zap/blob/master/FAQ.md). Please feel free to make a PR to add it. Thank you!
