### ISSUE TITLE
Allow providing custom stack that overrides regular stacktrace 

### ISSUE THREAD

**Issue by HaraldNordgren** [uber-go/zap#901]
I’m want to log a stacktrace from where an error is returned (but not where zap.Error is called), and it would be useful if I could instruct zap to show the custom stacktrace as stacktrace.

My program uses pkg/errors, but I believe that this could apply to stacktraces generated in any way.

**Comment by prashantv** [comment]
For errors created using `pkg/errors`, zap automatically adds a field `errorVerbose` which should contain the stacktrace of where the error was created.

There are also a few existing issues about customized stacktrace reporting, https://github.com/uber-go/zap/issues?q=is%3Aissue+is%3Aopen+stack

**Comment by lucasoares** [comment]
> errorVerbose

By pkg/errors you mean this read-mode repository? https://github.com/pkg/errors

I'm not using this package but I want to have zap logging my error's stacktrace instead of the stacktrace where `Error` function was called. How to do it?

**Comment by lucasoares** [comment]
> For errors created using `pkg/errors`, zap automatically adds a field `errorVerbose` which should contain the stacktrace of where the error was created.
> 
> There are also a few existing issues about customized stacktrace reporting, https://github.com/uber-go/zap/issues?q=is%3Aissue+is%3Aopen+stack

By pkg/errors you mean this read-mode repository? https://github.com/pkg/errors

I'm not using this package but I want to have zap logging my error's stacktrace instead of the stacktrace where `Error` function was called. How to do it?

**Comment by hannutho** [comment]
@lucasoares Did you ever find a solution to this?

**Comment by lucasoares** [comment]
> @lucasoares Did you ever find a solution to this?

Not so far, stopped looking for it
