### ISSUE TITLE
AtomicLevel unmarmal failed

### ISSUE THREAD

**Issue by will-beta** [uber-go/zap#906]
conf.yaml
```yaml
logging:
  level: "info"
  encoding: "json"
```

main.go
```go
package main

import (
	"log"

	"github.com/spf13/viper"

	"github.com/mitchellh/mapstructure"

	"go.uber.org/zap"
)

func main() {
	initConfig()
}

func initConfig() {
	viper.SetConfigName("conf")
	viper.AddConfigPath("./")
	viper.SetConfigType("yaml")

	err := viper.ReadInConfig()
	if err != nil {
		panic(err)
	}

	var cfg zap.Config
	err = viper.UnmarshalKey("logging", &cfg, func(config *mapstructure.DecoderConfig) {
		config.TagName = "yaml"
	})
	if err != nil {
		panic(err)
	} else {
		log.Println(cfg)
	}
}
```

Failed with `"'level' expected a map, got 'string'"`.

Thanks in advance.

**Comment by prashantv** [comment]
This doesn't seem like a zap issue, but a viper issue. The `AtomicLevel` type implements `UnmarshaslText`,
https://pkg.go.dev/go.uber.org/zap#AtomicLevel.UnmarshalText

This works fine with YAML / JSON unmarshalling, so I think viper may not be using `UnmarshalText` and instead expecting any custom struct type to use a map.

**Comment by abhinav** [comment]
To get mapstructure to consider the encoding.TextUnmarshaler interface, the [TextUnmarshallerHookFunc](https://pkg.go.dev/github.com/mitchellh/mapstructure#TextUnmarshallerHookFunc) must be installed.

Closing since this isn't a Zap issue.
