### ISSUE TITLE
multicore logs to all cores if one returns true for Enabled

### ISSUE THREAD

**Issue by mrothroc** [uber-go/zap#916]
The Advanced example shows that we should be able to use NewTee to log to several cores, each of which have a unique LevelEnablerFunc, like so:
```
	core := zapcore.NewTee(
		zapcore.NewCore(kafkaEncoder, topicErrors, highPriority),
		zapcore.NewCore(consoleEncoder, consoleErrors, highPriority),
		zapcore.NewCore(kafkaEncoder, topicDebugging, lowPriority),
		zapcore.NewCore(consoleEncoder, consoleDebugging, lowPriority),
	)
```

However, the code in zap/tee.go has this:
```
func (mc multiCore) Enabled(lvl Level) bool {
	for i := range mc {
		if mc[i].Enabled(lvl) {
			return true
		}
	}
	return false
}
```

So, if any of the cores Enabled return true, then it enables the entry for all of the cores.

**Comment by prashantv** [comment]
The multicore will return `true` for `Enabled`, but this does not mean that all the cores will log the entry -- the cores will check for the level again as part of `Check` + `Write` so only the enabled cores will log the entry.

We cannot return `false` for `Enabled` in the case that not all cores enable the level, since that is often used to short-circuit the log entry completely, and would result in no logs, even if some cores have the level enabled.

**Comment by mrothroc** [comment]
Unfortunately, this behavior (check level during Check + Write) doesn't happen.  If one of the cores in the tee is enabled, then they all get the message.

If I modify the code to manually call Level during Write, then it works as expected:
```
func (mc multiCore) Write(ent zapcore.Entry, fields []zapcore.Field) error {
	var err error
	for i := range mc {
		if mc[i].Enabled(ent.Level) {
			err = multierr.Append(err, mc[i].Write(ent, fields))
		}
	}
	return err
}
```

**Comment by prashantv** [comment]
Can you provide a repro of where you're running into this? `Write` is not expected to check the level specifically, from the docs:
```
 	// If called, Write should always log the Entry and Fields; it should not
	// replicate the logic of Check.
```

However, `Check` is expected to check the level,
```
	// Check determines whether the supplied Entry should be logged (using the
	// embedded LevelEnabler and possibly some extra logic).
```

The `Check` should make sure that only enabled cores are logged to, but there may be a bug somewhere, so a repro would be helpful.

**Comment by mrothroc** [comment]
Sure, see below, here is the output of "go test" with stderr redirected to a file:
```
% go test  2>error.out
2021/03/01 13:11:46 Running
This should go only to stdout
This should go only to stderr
PASS
ok      zaptest 0.311s
```

The line "This should go only to stderr" is printed to stdout.  The file error.out is empty.

Here is the code:
```
package zaptest

import (
	"go.uber.org/zap"
	"go.uber.org/zap/zapcore"
	"log"
	"os"
	"testing"
)

func TestName(t *testing.T) {
	log.Printf("Running")
	logger, err := makeLogger(infoAndLowerLevel, errorAndHigherLevel)
	if err != nil {
		t.Errorf("Error making logger: %v", err)
	}

	logger.Sugar().Debug("This should go only to stdout")
	logger.Sugar().Error("This should go only to stderr")
}

var (
	normalStream = os.Stdout
	errorStream = os.Stderr
)

var errorAndHigherLevel = zap.LevelEnablerFunc(func(lvl zapcore.Level) bool {
	return lvl >= zapcore.ErrorLevel
})

var infoAndLowerLevel = zap.LevelEnablerFunc(func(lvl zapcore.Level) bool {
	return lvl < zapcore.ErrorLevel
})

func makeLogger(outLevel zap.LevelEnablerFunc, errLevel zap.LevelEnablerFunc) (*zap.Logger, error) {
	encoderConfig := zapcore.NewConsoleEncoder(zapcore.EncoderConfig{
		MessageKey: "msg",
		LevelKey:   "level",
	})
	stdOutCore := zapcore.NewCore(encoderConfig, zapcore.Lock(normalStream), outLevel)
	stdErrCore := zapcore.NewCore(encoderConfig, zapcore.Lock(errorStream), errLevel)

	return zap.New(zapcore.NewTee(stdErrCore, stdOutCore)), nil
}
```

**Comment by mrothroc** [comment]
While creating the repro I found it was my own mistake.  Sorry about that!

**Comment by pbabbicola** [comment]
> While creating the repro I found it was my own mistake. Sorry about that!

what was your error? facing a very similar issue!
