### ISSUE TITLE
Possible to set exec.Command Stdout and Stderr to zap?

### ISSUE THREAD

**Issue by polds** [uber-go/zap#929]
Is it possible to use a zap.Logger for anything that provides its own Stdout / Stderr?

Given something like this:
```
cmd := exec.Command("echo", "hello world")
cmd.Stdout = zap.LoggerSomething
cmd.Stderr = zap.LoggerSomething
cmd.Run()
```

It doesn't look like it's possible to fetch the io.Writer from zap, but wondering if its possible another way?

**Comment by prashantv** [comment]
There is no native way to do this, but we can take advantage of zap's [support for the stdlib `log.Logger`](https://pkg.go.dev/go.uber.org/zap#NewStdLog) which exposes [the underlying `Writer()`](https://pkg.go.dev/log#Logger.Writer):
```go
	logger, _ := zap.NewDevelopment()
	w := zap.NewStdLog(logger).Writer()

	cmd := exec.Command("echo", "hello world")
	cmd.Stdout = w
	cmd.Stderr = w
	cmd.Run()
```

output of the above:
```
2021-05-12T21:20:31.186-0700	INFO	exec/exec.go:311	hello world
```

Given that we already support a way to create a `Writer` from a logger in this roundabout way, I think it makes sense to expose a `(*zap.Logger) WriterAt(level) io.Writer` to get a writer directly.

@abhinav What do you think?

**Comment by abhinav** [comment]
That sounds reasonable. This is functionality I've felt need for occasionally as well.

**Comment by abhinav** [comment]
However, how we handle line breaks will have to be more solid than what we do for test implementations of io.Writer backed by Zap.

    w.Write([]byte("foo"))
    w.Write([]byte("bar\nbaz"))
    w.Write([]byte("qux"))
    
This should result in two log entries:

    Info("foobar")
    Info("bazqux")

The returned Writer will probably also want to implement `Flush` to bypass line-buffered writing.

So we may want to expose the `Writer` type as a struct to expose `Flush` and other similar methods.

**Comment by prashantv** [comment]
Good point, there may also be cases where we want `w.Write([]byte("foo"))` to immediately create a log message, so we may want to accept some options on how to deal with newlines.
