### ISSUE TITLE
How to implement a custom encoder?

### ISSUE THREAD

**Issue by gfaia** [uber-go/zap#937]
Background:
We want to print traceID in the log and use console encoder. The format of the log is:

```
ts level caller traceid msg other
```

We found the default console encoder can't provided the ability above, so we try to implement a custom encoder. Can zap provide some advice for us.

**Comment by prashantv** [comment]
You can implement your own implementation of the `Encoder` interface:
https://pkg.go.dev/go.uber.org/zap/zapcore#Encoder

Take a look at how the console encoder is implemented, you may be able to borrow a lot of pieces:
https://github.com/uber-go/zap/blob/v1.16.0/zapcore/console_encoder.go#L58

**Comment by s3rj1k** [comment]
@prashantv This is unfortunate that `"go.uber.org/zap/internal/bufferpool"` and `"go.uber.org/zap/internal/pool"` are internal.
