### ISSUE TITLE
Nested fields

### ISSUE THREAD

**Issue by KaluTheKova** [uber-go/zap#938]
Helloes,

I want to create a logger where output contains a nested field like this:

```{"time":"2021-05-03T10:53:48+03:00", "level":"DEBUG", "log":{"class":"zapLogger/main.go:12", "message":"PlsSendHelpTheyKeepMeChainedToTheOfficeChairAndTheCoffeeTastesStale"}, "timezone":"EEST", "type":"log"}```

where "log" contains nested fields "class" and "message".

I already have this:
```
func ZapCreateLogger() *zap.Logger {
	cfg := zap.Config{
		Encoding:         "json",
		Level:            zap.NewAtomicLevelAt(zapcore.DebugLevel),
		OutputPaths:      []string{"stderr"},
		ErrorOutputPaths: []string{"stderr"},
		EncoderConfig: zapcore.EncoderConfig{

			LevelKey:    "level",
			EncodeLevel: zapcore.CapitalLevelEncoder,

			TimeKey:    "time",
			EncodeTime: zapcore.ISO8601TimeEncoder,

			CallerKey:    "class",
			EncodeCaller: zapcore.ShortCallerEncoder,
		},
	}
	logger, err := cfg.Build()
	if err != nil {
		panic(err)
	}
	defer logger.Sync()

	return logger
}
```
How can I add that those nested fields so that they are included in every log output by the logger?

**Comment by prashantv** [comment]
Unfortunately zap's encoder doesn't have the ability to support the nesting the level/caller/message, they are only encoded as top-level fields. To achieve the above, you would need to create your own encoder implementation.
