### ISSUE TITLE
Using zapcore.WriteThenNoop in onFatal

### ISSUE THREAD

**Issue by rthier** [uber-go/zap#946]
I tried to make some unit tests with log fatal message using `zap.OnFatal(zapcore.WriteThenNoop)` option.

But, for some reason, the unit test exit with a FAIL.
I was looking for some explanation and I found this between lines 288:292 (https://github.com/uber-go/zap/blob/d9a4dcc9a61879f83d1d58d584486aa404b8296e/logger.go#L290)
```
// Noop is the default value for CheckWriteAction, and it leads to
// continued execution after a Fatal which is unexpected.
if onFatal == zapcore.WriteThenNoop {
	onFatal = zapcore.WriteThenFatal
}
```

I guess that this is not the expected behavior, because is possible to disable using a simple int8 outside the enum (const) like `zap.OnFatal(5)`.

**Comment by prashantv** [comment]
`WriteThenNoop` is not a supported option for OnFatal, as call sites using `logger.Fatal` expect execution to be stopped (at least for the goroutine). You should use `WriteThenPanic` instead in unit tests, and use `recover()` and perform validation.

Behaviour of using unsupported enum values is undefined behaviour that may change in future versions, so I would strongly recommend against that option.

**Comment by rthier** [comment]
Thank for the explanation @prashantv !

I totally agree that using unsupported enum values is not a good a choice (maybe another issue about this should be opened)

But, using `WriteThenPanic` and put a `recover` in the unit test is too expansive, and also create a different behavior (following your comment about `logger.Fatal`), because the standard Golang Log's just call a `os.Exit(1)` instead a `panic(s)`.

In the other hand, both "solutions" are workarounds and probably a some assertion that handles the `os.Exit(1)` is the better choice.

**Comment by prashantv** [comment]
Yes, `WriteThenPanic` is still different behaviour, but we thought it was more similar as it exits the parent goroutine.

We did consider other alternatives for testing fatal when this option was selected, see #846 for more details.

**Comment by r0fls** [comment]
Are there any examples of using this? I'm having trouble implementing it.

**Comment by prashantv** [comment]
You can see an example of how this can be used in the tests when `OnFatal` was added:
https://github.com/uber-go/zap/pull/861/files#diff-55a2db70576eb079880167200221ea3787a01fa4bbc958503769eba24084d842

Use the `OnFatal` option to`WriteThenPanic` to cause the goroutine running the log to panic, run the test in a new goroutine, and use a defer to recover the panic (which would indicate the Fatal call).
