### ISSUE TITLE
Does Zap logger support escape character '\n' and '\t' to print new line or tabs in the log output.

### ISSUE THREAD

**Issue by Swapnils1996** [uber-go/zap#963]
I am using zap logger's sugared logger, I have initialized the zap logger as followed:
```
func InitLogger() {
	loggerMgr, err := logger.NewProduction()
	if err != nil {
		log.Println("error")
	}
	logger.ReplaceGlobals(loggerMgr)
	defer loggerMgr.Sync()
	logger := loggerMgr.Sugar()
	logger.Debug("START!")
}
```

I have used the log statement as follows:
```
zap.S().Errorf("Invalid thing_key: %s \n Please enter correct thing_key", payload.ThingKey)
```
I get the following output:

    {"level":"error","ts":1623216910.6660104,"caller":"db/water_meter.go:40","msg":"Invalid thing_key: 123 \n Please enter correct thing_key"}

But I am expecting the out put as follows:

    {"level":"error","ts":1623216910.6660104,"caller":"db/water_meter.go:40","msg":"Invalid thing_key: 123 
    Please enter correct thing_key"}

Please provide any suggestions on how to get this output

**Comment by prashantv** [comment]
No, it's not possible to use literal new lines and tabs, as that is not valid JSON. In JSON, all control characters (U+0000 through U+001F) must be escaped, look for "2.5 Strings" in the spec: https://www.ietf.org/rfc/rfc4627.txt
