### ISSUE TITLE
[Proposal] add a helper package with short names for zap fields

### ISSUE THREAD

**Issue by DheerendraRathor** [uber-go/zap#968]
I propose to add a helper package in zap like `go.uber.org/zap/z` which will have short names for common zap fields.

E.g.
```go
// z.S is alias to zap.String
z.S("a", "b")

// internally in package go.uber.org/zap/z
func S(key, val string) { zap.String(key, val) }
```

Other aliases can be:
1. `Sp` for Stringp
2. `I` for Int
3. `I32` for Int32 
etc

**Comment by tylitianrui** [comment]
i  dont  think so.  zap fields  are  so  short  and human-readable .

**Comment by prashantv** [comment]
Since this is easy to build and consume from outside of zap, I'd suggest starting there, and if there's significant interest / usage, then we can consider something similar in zap.

I think there's a balance to be had between `z.S` and `zap.String`, e.g., `z.Str`.
