### ISSUE TITLE
Question: Rate Limiting ?

### ISSUE THREAD

**Issue by midnightexigent** [uber-go/zap#969]
Consider the following use case 

`zap.RedirectStdLog(aZapLogger)`

where the std logger will be **highly** verbose. Since levels don't apply, all the logs will be written. Sampling is no good either since the messages will be different. 

Ideally I would like to write something like this

`zap.RedirectStdLog(aZapLogger.WithOption(someRateLimitingOption))`

Basically saying: "I don't want more than N logs per M seconds" 

Does `zap` provide some sort of primitive to accomplish this, that I missed while reading the docs ?

**Comment by midnightexigent** [comment]
answering my own question: 

I ended up implementing a `zapcore.Core` using the [rate](https://pkg.go.dev/golang.org/x/time/rate) package 

```go
func main(){
	zap.RedirectStdLog(logger.WithOptions(zap.WrapCore(func(c zapcore.Core) zapcore.Core {
		return &rateZapCore{
			Core:    c,
			limiter: rate.NewLimiter(rate.Every(time.Second), 5),
		}
	})))
}

type rateZapCore struct {
	zapcore.Core
	limiter *rate.Limiter
}

func (rzc *rateZapCore) Check(e zapcore.Entry, ce *zapcore.CheckedEntry) *zapcore.CheckedEntry {
	if rzc.limiter.Allow() {
		return rzc.Core.Check(e, ce)
	}
	return ce
}

```

**Comment by prashantv** [comment]
The sampler is the closest related feature, but as you mentioned, it doesn't help with the messages are variable, as it's used to throttle specific message/level combinations.

The sampler could be extended to accept a custom hash function, but what you're using seems like a good simple option.
