### ISSUE TITLE
Add support for []byte

### ISSUE THREAD

**Issue by magicalbanana** [uber-go/zap#97]
Are there any plans to add support for []byte type? I'm not gonna lie, I did a TL;DR on the source code.

**Comment by prashantv** [comment]
What would be the expected output (in a terminal, or in a JSON log file) for a binary blob?

Some options:
 - base64 encoded string
 - string with a bunch of escape characters

I don't know if binary blobs would be useful in terminal output though.

**Comment by magicalbanana** [comment]
I guess it would be Marshalled into a JSON object. It's more for objects that you can marshal into JSON that this feature would be needed for. So you don't have to do this `zap.String("marshalled_object", strings([]byte)`.

**Comment by belak** [comment]
The `encoding/json` package encodes `[]byte` as a base64 encoded string. I think if support was added, that might be the best option.
