### ISSUE TITLE
how to create logger on windows

### ISSUE THREAD

**Issue by itziklavon** [uber-go/zap#970]
Hi, we have multiple OS that people are using, some ubuntu, some windows and some mac OS
how we can create logger on windows?
zap.Logger file is not in the binary

**Comment by prashantv** [comment]
I'm not really sure what this question is asking, what do you mean by "file is not in the binary"?

You can pass a filename like "out.log" and it should work across Linux/Mac OS/Windows.

**Comment by itziklavon** [comment]
in general, we had an issue that intellij was not recognizing logger file from repo, not that it was not writing to external log file(*zap.Logger not found was the error), and read it as text file, thought it was due to build limitations, anyways, it was an issue with intellij, we found a workaround for it, thanks!

closing the issue
