### ISSUE TITLE
Is there a way to only add caller info when log with error level?

### ISSUE THREAD

**Issue by owarai** [uber-go/zap#982]
Hello, Appreciate for your effort to make this amazing package.

As the title states, I want to add the `caller: filename:line_num` kv pair in entry output only when the entry log level is error.

I wonder if there is a way to do it?

**Comment by prashantv** [comment]
Thanks for kind words @owarai!

We don't have an option to only enable the "caller" field for specific levels today (though we do support it for stacktraces).

However, you may be able to achieve this by [wrapping the core](https://pkg.go.dev/go.uber.org/zap#WrapCore). You can implement a custom core that wraps the real core and modifies the `Entry`. If level is < error, then set `entry.Caller = zapcore.EntryCaller{}` before calling the underlying core,

```go
type removeCallerCore struct {
        zapcore.Core
}

func (c *removeCallerCore) Check(entry zapcore.Entry, ce *zapcore.CheckedEntry) *zapcore.CheckedEntry {
        if ce := c.Core.Check(entry, ce); ce == nil {
                return nil
        }

        return ce.AddCore(entry, c)
}

func (c *removeCallerCore) Write(entry zapcore.Entry, fields []zapcore.Field) error {
        if entry.Level < zapcore.ErrorLevel {
                entry.Caller = zapcore.EntryCaller{}
        }

        return c.Core.Write(entry, fields)
}
```

Test:
```go

        l, _ := zap.NewProduction(zap.WrapCore(func(c zapcore.Core) zapcore.Core {
                return &removeCallerCore{c}
        }), zap.AddStacktrace(zap.FatalLevel))

        l.Info("hi")
        l.Error("both")
```

Output:
```
{"level":"info","ts":1627357179.1594052,"msg":"hi"}
{"level":"error","ts":1627357179.1594415,"caller":"zap/ex1_test.go:78","msg":"both"}
```

**Comment by owarai** [comment]
Thank you for your quick response. After some test, it seems not work well with NewTee(or say, multiCore). 

my log destination config like this:
```
zapcore.NewTee(
		zapcore.NewCore(encoder, writeSyncerForErr, zapcore.ErrorLevel),
		zapcore.NewCore(encoder, writeSyncerForAll, zapcore.InfoLevel),
	)
```

No matter where I use `WrapCore`, such as NewTee, NewCore or zap.New(*), there will still be unexpected output entries.
Did I miss something?

**Comment by prashantv** [comment]
Ah, if you wrap the tee'd core, then it doesn't work, and this is more of a limitation of the design of `CheckedEntry`. The above `removeCallerCore` implementation calls assumes that if the underlying `Core` returns a checked entry, then it's safe to call `Write`. However, the tee core is a little special, as it may return a checked entry with just a subset of cores, but if you call `Write` on the core, it triggers a write on all cores. This results in additional logs as you mentioned.

However, with a small change to the `Check` method, and by wrapping *before* the `NewTee`, it should work as expected.

updated `removeCallerCore` that calls `Check` on the underlying core on an independent `CheckedEntry`,
```go
type removeCallerCore struct {
        zapcore.Core
}

func (c *removeCallerCore) Check(entry zapcore.Entry, ce *zapcore.CheckedEntry) *zapcore.CheckedEntry {
        if c.Core.Check(entry, nil) == nil {
                return ce
        }

        return ce.AddCore(entry, c)
}

func (c *removeCallerCore) Write(entry zapcore.Entry, fields []zapcore.Field) error {
        if entry.Level < zapcore.ErrorLevel {
                entry.Caller = zapcore.EntryCaller{}
        }

        return c.Core.Write(entry, fields)
}
```

sample repro:
```
        encCfg := zap.NewDevelopmentEncoderConfig()
        consoleEnc := zapcore.NewConsoleEncoder(encCfg)
        jsonEnc := zapcore.NewJSONEncoder(encCfg)

        infoCore := zapcore.NewCore(jsonEnc, os.Stdout, zapcore.InfoLevel)
        errCore := zapcore.NewCore(consoleEnc, os.Stderr, zapcore.ErrorLevel)

        multiCore := zapcore.NewTee(
                &removeCallerCore{infoCore},
                &removeCallerCore{errCore},
        )

        l := zap.New(multiCore, zap.AddStacktrace(zap.FatalLevel), zap.AddCaller())

        l.Info("this is an info")
        l.Error("this is an error")
```

Output:
```
2021-07-27T21:20:57.880-0700    ERROR   zap/ex1_test.go:89      this is an error

{"L":"INFO","T":"2021-07-27T21:20:57.880-0700","M":"this is an info"}
{"L":"ERROR","T":"2021-07-27T21:20:57.880-0700","C":"zap/ex1_test.go:89","M":"this is an error"}
```

**Comment by owarai** [comment]
Works like a charm! Thank you very much for taking the time to answer patiently.

**Comment by owarai** [comment]
Sorry to bother again. If I use `With(fields)` to create a sub-logger, the `Core.With()` also need to be overwritten too, right? otherwise, sub-logger will regain `caller` in all level outputs.

```
func (c *removeCallerCore) With(fields []zap.Field) zapcore.Core {
	return &removeCallerCore{c.Core.With(fields)}
}
```

**Comment by prashantv** [comment]
Yes, the `removeCallerCore` should also implement `With` in the way you mentioned!
