### ISSUE TITLE
How should I avoid performance depression even log level is not debug

### ISSUE THREAD

**Issue by davix** [uber-go/zap#986]
I'm newbie to zap, and wondering how performance is not affected by debug log when level is info.

In below example

```
packet is a complicated struct{} type
			logger.Z.Debug("packetHandler", zap.Any("packet", packet))
```
even if level is info, this line of code consumes lots of cpu.
Is it because the packet struct itself is marshaled before the loglevel check?
What's the proper way to log here, so that no any performance impact when level is not debug?

Thanks!

**Comment by prashantv** [comment]
You should use the `Check` API, take a look at this example:
https://pkg.go.dev/go.uber.org/zap#example-Logger.Check

**Comment by davix** [comment]
Thank you @prashantv
