### ISSUE TITLE
Bug: Incorrect encoding of complex numbers

### ISSUE THREAD

**Issue by hemantjadon** [uber-go/zap#995]
`zap.Complex128` and `zap.Complex64` field types incorrectly formats complex numbers with negative imaginary component. Extra `+` sign is added before the actual `-` sign 
Eg. `2-3i` is formatted as `2+-3i`

```go
package main

import (
	"go.uber.org/zap"
)

func main() {
    l, _ := zap.NewProduction()

    l.Info("test", zap.Complex128("key", complex(2, -3)))
}
```

### Got output

```
{"level":"info","ts":1257894000,"caller":"sandbox516008598/prog.go:10","msg":"test","key":"2+-3i"}
```

### Expected output

```
{"level":"info","ts":1257894000,"caller":"sandbox516008598/prog.go:10","msg":"test","key":"2-3i"}
```

### Reference

https://play.golang.org/p/xz9b8kz_hCR

**Comment by abhinav** [comment]
Thanks for reporting @hemantjadon. This appears to be a legitimate bug.
We'll fix it shortly unless you already have a fix inbound.
