### ISSUE TITLE
gccgo compilation error

### ISSUE THREAD

**Issue by erDong01** [uber-go/zap#997]
gccgo compilation error

go build -compiler=gccgo  main.go

**Comment by yuko1225** [comment]
What's your GCC version? If it is too old, you might wanna try GCC 11.

> Note that zap only supports the two most recent minor versions of Go.

> ...
> The GCC 10 releases include a complete implementation of the Go 1.14.6 release.
> 
> The GCC 11 releases include a complete implementation of the Go 1.16.3 release.

**Comment by abhinav** [comment]
Thanks for the response @yuko1225!

It's been very long without a response from the author. Closing.
Please feel free to reopen or create a new issue if you run into more problems.
