### ISSUE TITLE
Question: Elegant way to autogenerate code?

### ISSUE THREAD

**Issue by shibumi** [uber-go/zap#998]
Hello,
is there any elegant way to generate code for implementing the MarshalLobObject function?
Imagine a struct like this (data types can be random of course):

```go
type Webhook struct {
	UPPMsgType            string `schema:"uppMsgType"`
	Status                string `schema:"status"`
	UPPTransactionID      string `schema:"uppTransactionId"`
	AuthorizationCode     string `schema:"authorizationCode"`
	MaskedCC              string `schema:"maskedCC"`
	Sign                  string `schema:"sign"`
	AliasCC               string `schema:"aliasCC"`
	ResponseCode          string `schema:"responseCode"`
	Mode                  string `schema:"mode"`
	EXPY                  string `schema:"expy"`
	MerchantID            string `schema:"merchantId"`
	AcqAuthorizationCode  string `schema:"acqAuthorizationCode"`
	Regtype               string `schema:"reqtype"`
	PayPalUseRestAPI      string `schema:"_paypalUseRestAPI"`
	Currency              string `schema:"currency"`
	Theme                 string `schema:"theme"`
	ReturnCustomerCountry string `schema:"returnCustomerCountry"`
	PayPalRestAPISellerID string `schema:"_paypalRestAPIsellerId"`
	UPPReturnTarget       string `schema:"uppReturnTarget"`
	EXPM                  string `schema:"expm"`
	RefNo                 string `schema:"refno"`
	Amount                string `schema:"amount"`
	Version               string `schema:"version"`
	CardNo                string `schema:"cardno"`
	PMethod               string `schema:"pmethod"`
	ResponseMessage       string `schema:"responseMessage"`
	TestOnly              string `schema:"testOnly"`
}
```

I wrote this manually:
```go
func (w Webhook) MarshalLogObject(enc zapcore.ObjectEncoder) error {
	enc.AddString("uppMsgType", w.UPPMsgType)
	enc.AddString("status", w.Status)
	enc.AddString("uppTransactionId", w.UPPTransactionID)
	enc.AddString("authorizationCode", w.AuthorizationCode)
	enc.AddString("maskedCC", w.MaskedCC)
	enc.AddString("sign", w.Sign)
	enc.AddString("aliasCC", w.AliasCC)
	enc.AddString("responseCode", w.ResponseCode)
	enc.AddString("mode", w.Mode)
	enc.AddString("expy", w.EXPY)
	enc.AddString("merchantId", w.MerchantID)
	enc.AddString("acqAuthorizationCode", w.AcqAuthorizationCode)
	enc.AddString("reqtype", w.Regtype)
	enc.AddString("_paypalUseRestAPI", w.PayPalUseRestAPI)
	enc.AddString("currency", w.Currency)
	enc.AddString("theme", w.Theme)
	enc.AddString("returnCustomerCountry", w.ReturnCustomerCountry)
	enc.AddString("_paypalRestAPIsellerId", w.PayPalRestAPISellerID)
	enc.AddString("uppReturnTarget", w.UPPReturnTarget)
	enc.AddString("expm", w.EXPM)
	enc.AddString("refno", w.RefNo)
	enc.AddString("amount", w.Amount)
	enc.AddString("version", w.Version)
	enc.AddString("cardno", w.CardNo)
	enc.AddString("pmethod", w.PMethod)
	enc.AddString("responseMessage", w.ResponseMessage)
	enc.AddString("testOnly", w.TestOnly)
	return nil
}
```

It would be so nice to have something to autogenerate this.. or am I just using the library wrong?!
I am doing this, because I want to log the whole struct.

**Comment by abhinav** [comment]
Hi! Yes, for cases where you'd like marshaling to be high performance,
implementing MarshalLogObject on the object is the only way.  We agree that it
can be a pain to implement these by hand, though, and in theory, it should be
possible to auto-generate these implementations. We're planning to build a
code generator for that in the near future. (Unfortunately, we haven't
started yet so I can't share any estimates.)

**Comment by shibumi** [comment]
@abhinav 

> Hi! Yes, for cases where you'd like marshaling to be high performance, ...

does this mean there is a more elegant solution for cases where I don't need performance? Can I just call `zap.Any()` on a struct and it auto-marshals it?

**Comment by abhinav** [comment]
Yes, @shibumi, if you don't care about performance, you can use one of the following:

- [zap.Any](https://pkg.go.dev/go.uber.org/zap#Any): This will inspect the type and try to use the most appropriate Zap serializer. If the type implements `String() string`, that will be preferred.
- [zap.Reflect](https://pkg.go.dev/go.uber.org/zap#Reflect): This will use the standard library's `encoding/json` package to serialize the struct. Use this if your struct also implements `String() string`, but you specifically want to serialize it as an object rather than a string.
